### ISSUE TITLE
Re-add r_shadows

### ISSUE THREAD

**Issue by theOneTrueFunniBoi** [ValveSoftware/halflife#3400] opened 2023-10-16 00:03 UTC
I know this is a duplicate, but I can't find any _**true**_ answers to _how to readd it_.

Simply put, as far as i can find, the code for these shadows exists nowhere. If someone can help me reimplement it, that would be great (im not very good with goldsrc).

**Comment by kisak-valve** [comment] 2023-10-16 00:10
Hello @theOneTrueFunniBoi, please do not intentionally open duplicate issue reports.

Closing as a duplicate of #451.

**Closed by kisak-valve** 2023-10-16 00:10 UTC
