### ISSUE TITLE
fps drops on Sven Co-Op

### ISSUE THREAD

**Issue by arthur4ik** [ValveSoftware/halflife#1674] opened 2016-01-31 21:33 UTC
is there still an issue with AMD cards + dynamic lights on goldsrc games?
in some situations its nearly unplayable..

**Comment by johnstt** [comment] 2016-02-01 05:49
As far as I know, this has been an issue since at least the 2013 update and Linux port. Lots of mods that inherit the dynamic light on rockets (from EF_LIGHT) can reproduce the same issue.

**Comment by arthur4ik** [comment] 2016-02-01 09:57
it happens using a Radeon or also with GeForce?
using an old version won't help i think.
http://wiki.sourceruns.org/wiki/Game_versions

With this Version in Crossfire without players no stable 250fps. it goes down to 190. with players it could drop to 100 in some cases.

**Comment by arthur4ik** [comment] 2016-02-01 10:03
// i meant NGHL (Half-Life Client Version 1.1.2.0 #3248) from 2005.

But in Sven-Co-Op its really annoying

**Comment by JoelTroch** [comment] 2016-02-11 19:11
Issues for Sven-Coop should be reported to the Sven-Coop forums not here. They have a custom GoldSource engine.

**Comment by SamVanheer** [comment] 2019-05-05 12:02
As stated above issues pertaining to Sven Co-op should be reported to their forums/Discord.

Also note:
`Removed r_dynamic from the list of cheat CVARs. (We now allow players access to this CVAR in multi-player for performance reasons on AMD hardware.)`

You can disable dynamic lights in multiplayer without needing cheats turned on.

This issue can be closed.

**Comment by kisak-valve** [comment] 2019-05-05 13:40
Closing in favor of #1578 and per the last comment.

**Closed by kisak-valve** 2019-05-05 13:40 UTC
