### ISSUE TITLE
[TFC] Oct 2 2024 build crashes on joining

### ISSUE THREAD

**Issue by MaZDuR** [ValveSoftware/halflife#3837] opened 2024-10-02 19:52 UTC
Update  game -> Launch game -> Join/Create server ->

![error](https://i.imgur.com/a3cpU9g.png)

more details can be found in #3835 but it looks like it is assumed that the issue effects specific maps when it is actually some new engine changes that prevent any gamedll that wasn't updated with these changes to crash with this error regardless of the map being played (You guys actually get content updates??)

**Comment by kisak-valve** [comment] 2024-10-02 20:15
Hello @MaZDuR, this is better off as a note on #3835 than fragmenting the discussion of the issue across multiple issue reports.

Closing as a duplicate of #3835.

**Closed as not planned by kisak-valve** 2024-10-02 20:15 UTC
