### ISSUE TITLE
[CS 1.6] bug crosshair 1920x1080

### ISSUE THREAD

**Issue by LKING01** [ValveSoftware/halflife#2791] opened 2019-11-18 23:37 UTC
![1920x1080](https://user-images.githubusercontent.com/57906618/69103063-133be380-0a43-11ea-9d72-36c90283d863.PNG)
![Large](https://user-images.githubusercontent.com/57906618/69103064-133be380-0a43-11ea-914e-d2df31a2b652.PNG)

**Comment by kisak-valve** [comment] 2019-11-19 00:16
Looks like there's an issue with the screenshot, but this is a duplicate of #416. Closing in favor of the existing issue report.

Also reported at #2305.

**Closed by kisak-valve** 2019-11-19 00:16 UTC
