### ISSUE TITLE
[Half-Life] Music Playback Issues for songs

### ISSUE THREAD

**Issue by mcl21014** [ValveSoftware/halflife#1651] opened 2015-09-06 17:58 UTC
I've noticed some issues with music in the GoldSRC version of Half-Life, at least while playing on my Ubuntu 15.04 box. May or may not be Linux specific.
Distro: Ubuntu 15.04 64 bit
Window Manager: Unity 7
Graphics driver: Open source AMD Radeon
Steam-provided System Info:
Processor Information:
    Vendor:  AuthenticAMD
    CPU Family:  0x14
    CPU Model:  0x2
    CPU Stepping:  0x0
    CPU Type:  0x0
    Speed:  1650 Mhz
    2 logical processors
    2 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 15.04 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.2.0-040200-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11701000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  X.Org Gallium 0.4 on AMD PALM

```
Driver Version:  3.0 Mesa 10.5.9
OpenGL Version: 3.0
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x1002
DeviceID:  0x9806
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1600 x 900
Desktop Resolution: 1600 x 900
Primary Display Size: 17.44" x 9.80"  (20.00" diag)
                                        44.3cm x 24.9cm  (50.8cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: ATI R6xx HDMI

Memory:
    RAM:  7473 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  217551 Mb
    Largest Free Hard Disk Block:  128731 Mb

Installed software:

Recent Failure Reports:
    Description and how to reproduce:
1) The "Unforeseen Consequences" song that plays directly after the Resonance Cascade will loop, and it will loop until I quit the game. Try lingering on the same map or continuing onto another one while investigating to see if it changes the behavior.
2) Sometimes, the "Residue Processing" song that plays as soon as the player comes to the end of a pipe in the beginning of the corresponding chapter where the security guard is dispatching of some headcrabs, and proceeds to run into a barnacle up ahead sometimes doesn't play.
3) The "Nuclear Mission Jam" song doesn't seem to play after several playthroughs for me at the beginning of Apprehension where the tram derails and HECU are shooting at the player.

**Comment by mcl21014** [comment] 2016-02-06 15:33
Not platform specific for the music not playing at the start of Apprehension. I suggest if you really want the game to feel like it should, directly after loading the first map of Apprehension, to open a dev console with the "`" key and typing in "cd play 15" (w/o quotations). That way, you'll get to hear one of the best tracks in Half Life, and the main reason I liked Apprehension so much and play HL1 to this day. As a note for others, typing in "cd play x", where x is a number, starting at 1 and going up, will play a non-looping version of any track. Hard to find that command on Google since this game is honestly getting to be so old.

**Comment by SamVanheer** [comment] 2019-04-24 05:07
Duplicate of #570

**Comment by kisak-valve** [comment] 2019-04-24 12:39
Closing as a duplicate of #570.

**Closed by kisak-valve** 2019-04-24 12:39 UTC
