### ISSUE TITLE
Noob Mapper Ents disappearing when loading OP4 again

### ISSUE THREAD

**Issue by djearthquake** [ValveSoftware/halflife#3089] opened 2021-04-04 14:28 UTC
Big ents like oceans of water disappearing. Started to map map for OP4, noticed everything looks prettier when loading Sven. When going back to OP4 ents are disappearing.

Edit: thanks NukemD removing gangs of ents resolved OP4 issue.  Other issues already had been through them already prior to this.

**Comment by NukemD** [comment] 2021-04-04 23:10
The issue you describe isn't related to the entities you listed, it's a problem with how the engine calculates the PVS (potential view set) of the client. When you compile a map into a BSP, one of the processes is visibility calculations, which determines which leafnodes can see which other leafnodes from any given location.

This process isn't perfect, and can result in things being rendered when they shouldn't be, and the inverse when things should be rendered but aren't. This process works fine on small entities, but when you're dealing with large entities like volumes of water, or when a mapper ties too many brushes to a single entity, like large stretches of railings, it can cause rendering errors.

In either situation, the bounding box of the entity is so large that the engine has trouble determining when and when not to render it, which can result as the entity blinking in and out of existence as the engine toggles its visibility to the client.

To fix this problem, the rendering system as a whole would have to be overhauled, there's really nothing that can be done with the specific entities you mentioned to make them any better, other than carefully planning how you use them in maps.

**Comment by djearthquake** [comment] 2021-04-05 12:50
When said map is played on Sven it has a way to compensate. Is that something regular Half-Life is willing to code? I have the problem 99% resolved by sacrificing many other map details. It does it on maps I am not involved in as well.

**Comment by NukemD** [comment] 2021-04-06 02:52
The SvenEngine doesn't compensate for anything, the PVS rendering is virtually identical. Maps with brush entity rendering issues in the vanilla HL engine will have the problem in SvenEngine.

**Comment by djearthquake** [comment] 2021-04-06 12:39
We are depicting 2 different phenomenons then. None of these things I have seen in Sven; all else being equal.

**Comment by NukemD** [comment] 2021-04-07 05:10
Probably because you didn't know what you were looking at. Here are two examples in SvenEngine:

the_daikon_warfare2 - The fake scrolling road func_train visible through the world.

![image](https://user-images.githubusercontent.com/1351169/113813170-005ba900-9735-11eb-8a07-742bcd1a8b79.png)

central_bunker - water and rails visible through the world.

![image](https://user-images.githubusercontent.com/1351169/113813358-61837c80-9735-11eb-943b-d80392b3b648.png)

In every case, it is caused by my explanation above. SvenEngine DOES NOT fix these issues. The same issue that causes entities to be visible when they shouldn't be, also causes them to blink in and out of existence.

**Comment by djearthquake** [comment] 2021-04-08 23:24
We _could_ glob this into anytime stuff we want to see disappear. Sven DOES DO the same thing. The map, SUSPENSION, is an example. Takes about as long as CS:GO to load. Both HL flavors can be run to --- total failure with ad_blockfull or ClipskyPolygon:MAX_CLIP_VERTS.  Only by nerds, not stock. Assuming it isn't a func_wall set to start invisible or an inadvertent holographic fade effect. Askew maximum viewable distance. Then there are  2 boundaries | same engine dilemma. That more and more we talk turns into a paradox. Luckily the map I care about no longer does that at all even with plain old HL. During the course of this I see the 256 ent limit per frame. Sven's ent limit has to be respectfully higher because when I had the map super rich in details all kinds stuff disappeared and there was a time I did not know what was going on. Went through hell with Hammer. Map corrupted compiling and doubled some ents. Removed them. Sure I can stop focusing on the gameplay and find a spot where stuff used to disappear to take snap shots. Instead I just leaned up the map. It's all over with. One year the edicts were expanded. It wouldn't hurt to have ent limit per sec expanded. That's not unrealistic. Sven did clean-up a mess I had and so I salute it. No complaints. Free. Just hoping someday generic HL gets a boost too.

**Comment by NukemD** [comment] 2021-04-09 08:35
Now it sounds like you're complaining about engine limits due to not knowing how to make maps properly. If you're hitting vertex limits and PVS entity limits, you're doing something very wrong. I've been making HL engine maps for 23 years, and very rarely do the complaints about limits I see are actually problems with the engine, it's usually something the mapper is doing incorrectly.

I don't see what the map Suspension has to do with this, I've never seen excessive loading times on it, unless you're trying to run it on an ancient machine.

**Comment by djearthquake** [comment] 2021-04-17 11:26
Everything I encountered was fixed by loading it in Sven. These other things please start your own thread with those. When I attempted to accommodate, you got defamous.

- larger size entities occasionally disappearing/reappearing, sometimes in a flash
- The issue you describe isn't related to the entities you listed
- We are depicting 2 different phenomenons then. None of these things I have seen in Sven; all else being equal.
- Probably because you didn't know what you were looking at.
- We could glob this into anytime stuff we want to see disappear
- djearthquake changed the title
- Now it sounds like you're complaining about engine limits due to not knowing how to make maps properly

**Comment by NukemD** [comment] 2021-04-17 12:09
Sorry, but you're making less and less sense the more you comment. Your statement of large entity PVS issues being fixed in SvenEngine is patently proven false by the above screenshots.

Are you sure you don't have a network issue? Constrained rates, network lag and low frame rates can cause similar issues. Check your rate setting in the console with the "rate" cvar, it should be at least 25000, when the default is 2500 or less. Servers can also mess with this variable and cause artificial choke and network lag.

**Comment by djearthquake** [comment] 2021-05-06 14:20
Low drive space, over-clocking tic, forgetting OP4 has the more ents  than HL/Sven are all factors.

https://www.svencoop.com/manual/changelog.html

Sven Co-op now uses a customized GoldSrc engine under licence from Valve.
Gives us the opportunity to improve upon common limitations in the GoldSrc engine.
Maps can now be up to ~1,000x larger! (131,072 units away from position zero instead of just 4,096)

**New limits (engine core):**
-Maximum base decals: Raised to 1,024 from 256.
-Maximum beams: Raised to 256 from 64.
-Maximum dynamic/entity lights: Raised to 256 from 64.
-Maximum edicts: Raised to 8,192 from 900 (though the engine may become unstable beyond ~2,500).
-Maximum frame rate: Raised to 200 from 100 (for 120Hz/144Hz monitors). You can still get up to 1,000 frames/second with developer mode enabled.
-Maximum heap memory size: Raised to 512MB from 128MB.
-Minimum heap memory size: Raised to 64MB from 14MB.
-Maximum models: Raised to 8,192 from 512.
-Maximum sounds: Raised to 4,096 from 512.
-Maximum weapon count: Raised to 64 from 32.
-Zone/hunk memory: Raised to 32MB from 2MB.
**New limits (for maps):**
-Maximum brushes: Raised to 32,767 from 8,192.
-Maximum edicts: Raised to 8,192 from 1,024 (though the engine may become unstable beyond ~2,500).
-Maximum entity key size: Raised to 256 from 32.
-Maximum entity value size: Raised to 4096 from 1024.
-Maximum entity data size: Raised to 1MB from 128kB.
-Maximum leafs: Raised to 65,536 from 8,192.
-Maximum light data: Raised to 64MB from 16MB.
-Maximum light maps: Raised to 512 from 64.
-Maximum light styles: Raised to 256 from 32.
-Maximum models: Raised to 4,096 from 400.
-Maximum nodes: Raised to 65,536 from 32,767.
-Maximum planes: Raised to 65,536 from 32,767.
-Maximum textures: Raised to 2,048 from 512.
-Maximum visibility data: Raised to 64MB from 16MB.

**Comment by djearthquake** [comment] 2023-03-15 13:28
If you do not update this I will just tell everybody to play the free Sven. Less money in your pocket and more credibility for me.

**Comment by NukemD** [comment] 2023-03-15 16:54
Who are you even talking to? I'm not a HL engine developer, and Valve has long since stopped caring about developing the HL engine further, your "demanded" changes are never going to be made. Sven Coop is also never going to be able to run the Op4 campaign completely unaltered due to missing entities and missing monsters.

You aren't any more credible than you were two years ago. You have no idea what you're talking about, and are trying to get blood from a stone.

**Comment by kisak-valve** [comment] 2023-03-17 12:29
It wasn't clear before, but this should be discussed along with other requests to increase various engine limits. Closing as a duplicate of #12.

**Closed by kisak-valve** 2023-03-17 12:29 UTC
