### ISSUE TITLE
Counter strike condition zero texture issue

### ISSUE THREAD

**Issue by Diegoparedeshd1** [ValveSoftware/halflife#3634] opened 2023-11-29 19:56 UTC
[https://www.youtube.com/watch?v=VoxGnCslWVM](url)

**Comment by kisak-valve** [comment] 2023-11-29 20:02
Hello @Diegoparedeshd1, making an issue report with two words and a link to another website is profoundly poor communication.

Setting that aside, this looks like a duplicate of #3631. Closing as a duplicate.

**Closed by kisak-valve** 2023-11-29 20:02 UTC
