### ISSUE TITLE
Default models preview images don't change colors in their current format

### ISSUE THREAD

**Issue by LucesEnBabel** [ValveSoftware/halflife#2391] opened 2019-05-04 21:56 UTC
This is a weird oddity in the player model selection screen, the user may use the two bars in this screen to change the colors of their player model along with a preview (`[modelname].bmp`), the game must update the preview changing the color of the indexes 160 to 175 for `topcolor` and indexes 192 to 223 for `bottomcolor`.

https://www.youtube.com/watch?v=4AcXH-GcrqY

It seems the engine can't edit those values in the bitmap format the files are currently saved. Opening one of these files in IrfanView and then saving them allows the game to change the color of the image.

**Comment by SamVanheer** [comment] 2019-05-04 21:57
Duplicate of #1477

**Comment by kisak-valve** [comment] 2019-05-04 22:04
Closing as a duplicate.

**Closed by kisak-valve** 2019-05-04 22:04 UTC
