### ISSUE TITLE
[Feature Request] Improve common limitations in the GoldSrc engine

### ISSUE THREAD

**Issue by djearthquake** [ValveSoftware/halflife#3335] opened 2023-03-17 11:38 UTC
@kisak-valve What would it take to merge what Sven has done with the standard GoldSrc engine?
[eg](https://www.svencoop.com/manual/changelog.html#code-engine)

_New limits (engine core):

    Maximum base decals: Raised to 1,024 from 256.
    Maximum beams: Raised to 256 from 64.
    Maximum dynamic/entity lights: Raised to 256 from 64.
    Maximum edicts: Raised to 8,192 from 900 (though the engine may become unstable beyond ~2,500).
    Maximum frame rate: Raised to 200 from 100 (for 120Hz/144Hz monitors). You can still get up to 1,000 frames/second with developer mode enabled.
    Maximum heap memory size: Raised to 512MB from 128MB.
    Minimum heap memory size: Raised to 64MB from 14MB.
    Maximum models: Raised to 8,192 from 512.
    Maximum sounds: Raised to 4,096 from 512.
    Maximum weapon count: Raised to 64 from 32.
    Zone/hunk memory: Raised to 32MB from 2MB.

New limits (for maps):

    Maximum brushes: Raised to 32,767 from 8,192.
    Maximum edicts: Raised to 8,192 from 1,024 (though the engine may become unstable beyond ~2,500).
    Maximum entity key size: Raised to 256 from 32.
    Maximum entity value size: Raised to 4096 from 1024.
    Maximum entity data size: Raised to 1MB from 128kB.
    Maximum leafs: Raised to 65,536 from 8,192.
    Maximum light data: Raised to 64MB from 16MB.
    Maximum light maps: Raised to 512 from 64.
    Maximum light styles: Raised to 256 from 32.
    Maximum models: Raised to 4,096 from 400.
    Maximum nodes: Raised to 65,536 from 32,767.
    Maximum planes: Raised to 65,536 from 32,767.
    Maximum textures: Raised to 2,048 from 512.
    Maximum visibility data: Raised to 64MB from 16MB.
    Maximum world size: Raised to +/-131,072 from +/-4,096: Only enabled if the game's liblist contains largemap_aware, as the game will need to be built use different data types for handling co-ordinates.

Networking changes:

    All datagrams now leave enough room for IPv6 headers.
    Default maximum network rate: Raised to 20,000 bytes/second instead of 2,500.
    Maximum datagram length: Raised to 65,536 bytes from 1,400.
    Maximum entities per packet: Raised to 512 from from 256.
    Maximum sign-on data length: Raised to double the datagram length.
    Maximum user (mod) message size: Raised to 512 bytes from 192 bytes.
    Message sequence size: Raised to 2 bytes from 1 byte.
    Fixed an unexpected disconnect if a custom network message couldn't be found. Instead a warning is printed to their console.
    Mod-level network messages are now loaded directly after the server has activated to prevent some missing message issues.

Smarter heap memory allocation mechanism:

    Default heap memory size is now half of all available virtually addressable memory but only up to 512MB from 40MB (for clients) or 32MB (for servers).
    Default heap memory size will step down by 16MB decrements until enough memory can be allocated by the host system.
    If the engine can't obtain the minimum required memory from the host system it will refuse to start.
    Compiled launchers with the large address aware flag so that up to 3GB of memory can be consumed on 32-bit Windows systems (if the /3GB boot switch is used), and up to 4GB on 64-bit Windows systems. Both up from their previous 2GB limit.
    Launch parameter -heapsize can now be written in MB/GB (i.e. -heapsize 256M or -heapsize 1G).
    Launch parameter -maxmemory will force the engine to take as much memory as it can from the host system.
    Launch parameter -minmemory will force the engine to take as little memory as it can from the host system.
    Launch parameter -showheap will notify you how much memory was successfully allocated from the host system.
    Stack size increased to 8MB from 1MB._

**Comment by kisak-valve** [comment] 2023-03-17 12:28
Hello @djearthquake, friendly reminder that I'm a moderator for Valve's issue trackers on Github, and not a goldsrc dev myself.

There's no value in fragmenting the discussion of this issue over multiple issue reports. Closing as a duplicate of #12.

**Closed by kisak-valve** 2023-03-17 12:28 UTC

**Comment by djearthquake** [comment] 2023-03-17 13:50
I just searched keyword engine again, and that thread does not populate. You won't be hearing from me again.
