### ISSUE TITLE
[Goldsrc] Add -high command line parameter

### ISSUE THREAD

**Issue by shoober420** [ValveSoftware/halflife#1410] opened 2013-11-08 01:12 UTC
Source games have a command line parameter to automatically set the process priority to high by using the -high command line parameter. Could you also add the -high command line parameter to Goldsrc games too? It gets annoying having to open the task manager and find the hl.exe and switch the priority to high everytime you play.

**Comment by SamVanheer** [comment] 2019-05-05 10:33
Duplicate of #709

**Comment by kisak-valve** [comment] 2019-05-05 12:52
Closing as a duplicate.

**Closed by kisak-valve** 2019-05-05 12:52 UTC
