### ISSUE TITLE
[CS 1.6] In regard of r_dynamic

### ISSUE THREAD

**Issue by LuckyStrikeOriginal** [ValveSoftware/halflife#1909] opened 2018-10-13 13:04 UTC
I'm using a laptop with Intel GMA 4500 , and i don't think i should be forced to upgrade just to enjoy counter-strike 1.6. 

What i'm trying to say is. Flashlights, HE Explosions, and dynamic lights overall Cripples my framerate, the command r_dynamic resets itself back to 1 and i can't put it to 0 at all. in the Sven-Coop i can turn it off and on easily and by posting this i hope in the next update to see r_dynamic unlocked . 

Thanks.

**Comment by shoober420** [comment] 2018-11-05 01:40
I disagree good sir, you should indeed upgrade your GPU lolol

**Comment by LuckyStrikeOriginal** [comment] 2018-11-05 02:15
I believe there is no reason for r_dynamic to be locked, so maybe in the next patch they could squeeze that change in.

**Comment by kisak-valve** [comment] 2019-11-28 12:48
Closing as a duplicate of #1578.

**Closed by kisak-valve** 2019-11-28 12:48 UTC
