### ISSUE TITLE
[CS 1.6] Scoreboard latency not visible

### ISSUE THREAD

**Issue by vipul713** [ValveSoftware/halflife#2595] opened 2019-07-18 13:10 UTC
Using latest beta:
Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
Exe build: 13:45:11 Jul 17 2019 (8301)

Resolution: 640*480

SS:
![Capture](https://user-images.githubusercontent.com/53047859/61459942-d8377f80-a97e-11e9-9cdf-2605a5850ce8.PNG)

**Comment by uniarch** [comment] 2019-07-18 13:37
try scoreboard_shortheaders 1

**Comment by dager10** [comment] 2019-07-18 13:49
if we have 16 or less players on server this is happen, scoreboard broke after the last correction of the avatars, with scoreboard_shortheaders 1 the same effect

![20190718164014_1](https://user-images.githubusercontent.com/40521420/61462421-4d08ba80-a97b-11e9-89f7-6d68c09e6633.jpg)
![20190718163954_1](https://user-images.githubusercontent.com/40521420/61462427-4ed27e00-a97b-11e9-80f0-531133aee688.jpg)

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-07-18 15:16
Also as @perforatorRu write in https://github.com/ValveSoftware/halflife/issues/702#issuecomment-486412533
![изображение](https://user-images.githubusercontent.com/9306996/61469402-2d2fc180-a990-11e9-9693-f550da620cac.png)
maybe we should remove unused x player/players? What else can be in tab? Cakes, canadians?

**Comment by eat1k** [comment] 2019-07-18 16:03
Why should it be removed? No reasons to remove it.

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-07-18 16:05
As you can see we just replaced(moved) it into bracket's.

**Comment by Maxi605** [comment] 2019-07-18 18:58
> Why should it be removed? No reasons to remove it.

Replacing it for (%d) it's a pretty good tbh.

**Comment by eat1k** [comment] 2019-07-18 19:30
Oh, I didn't notice that. Yes, maybe it's a good suggestion.

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-07-18 21:23
Nothing to do? Rly? If we reduce it, we can place one more column or make move hp and money to left and there will be free space for **old column's** too.

**Comment by mikela-valve** [comment] 2019-07-18 21:36
@afwn90cj93201nixr2e1re Just to check, do you think the `Counter-Terrorists - 9 players` is a column header that is pushing all of the other columns to the right? If so, it's not, that header shows over the top of the name column but it's not affecting the size of that column, all of that area is devoted to showing long player names. 

Even if it was reduced in size as you show the width of the name column is what would need to be reduced to fit another column in or resize the other columns.

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-07-18 21:51
No, i know how column's work. It's just idea.
You can set your name to 32 symbols(this is max length) and see that column header is wider than name field. And there is question, should we just reduce it or no?

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-07-18 21:57
Hm, strange, im wrong.
![изображение](https://user-images.githubusercontent.com/9306996/61494863-70a62200-a9c8-11e9-93c0-ddce22f70081.png)
Still not showing full name

![изображение](https://user-images.githubusercontent.com/9306996/61494878-7a2f8a00-a9c8-11e9-8fdf-396da6444c82.png)
Can't show last char.

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-07-18 22:07
![изображение](https://user-images.githubusercontent.com/9306996/61495296-a13a8b80-a9c9-11e9-9bdb-f3c7182614f4.png)


So, it's seem's like this work's fine. Tested on last beta too. Seem's like my nickname is 33 bytes with null byte, not 32.

![изображение](https://user-images.githubusercontent.com/9306996/61495314-ba433c80-a9c9-11e9-9fd9-9d1b8cd2f957.png)
So, maybe you can add name field reducer for auto limit? For example *hooking cvar change if this is name and length > 31 (32 if with null byte) remove less character's and set cvar->value = new_string ?

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-07-18 22:11
Also if you can just fix close button margin. Seem's like still not fixed. Strange.
And in setting's there no right border for last option (Lock), maybe you can make settings dialog 1-2 pixel wider?

![изображение](https://user-images.githubusercontent.com/9306996/61495548-5d945180-a9ca-11e9-8670-c002bbac08fb.png)

**Comment by h0lzed** [comment] 2019-07-19 09:16
@mikela-valve, sorry for writing this here, but it would be nice to have r_decals, max_shells, max_smokepuffs, cl_smoothtime archived.
I can create a new issue, if it's needed.

**Comment by SamVanheer** [comment] 2019-07-19 09:22
Issue #2237 tracked cvars to archive, you could post it there or create a new issue.

**Comment by Splatt581** [comment] 2019-07-19 13:10
As for the display of avatars of players at low resolutions, where they are cut off - maybe it is worth adjusting their size to the row space? Yes, in this case they will be more stretched, but they will be displayed fully.

**Comment by 10th** [comment] 2019-07-19 14:25
I was going to suggest the same thing. Or cut from the top and bottom, otherwise the text in the line is not centered.

**Comment by mikela-valve** [comment] 2019-07-19 17:14
@h0lzed I've added those to the tracked cvars as noted on #2237.

**Comment by mikela-valve** [comment] 2019-07-19 22:19
This should be fixed now in build 8303. I've also adjusted the avatar slightly in 640x480 and 800x600 to not cut off the lower part of the image.

**Comment by CS-PRO1** [comment] 2019-07-20 16:20
Fix confirmed. This can be closed

**Comment by agrastiOs** [comment] 2019-07-21 21:03
@kisak-valve Fixed. Can be closed.

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-07-21 21:07
Can't be closed. @mikela-valve my idea was just joke, but ok, can you add cvar or say something 'bout where is placed font size of new name column? I wanna patch it and check with which one is more comfortable.

**Comment by mikela-valve** [comment] 2019-07-23 04:53
@afwn90cj93201nixr2e1re That font size you're seeing was always there, you just may not have seen it due to not normally using such a long name. That is the fallback font that is used when a column has too many characters in it to be rendered with the regular font. If you set your name back to its original length it will have the original font again. I'll consider changes to that font as a future improvement but due to it being a preexisting thing I'm going to leave it as it is for the current release.

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-07-23 13:41
https://github.com/ValveSoftware/halflife/issues/2595#issuecomment-513004326

Where is this font there?
Same name.
31 characters.

**Comment by mikela-valve** [comment] 2019-07-23 18:07
It's not used there because the rest of the columns to the right are pushed off the edge of the scoreboard making the name column larger.

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-07-24 16:23
But now?

**Comment by mikela-valve** [comment] 2019-07-28 20:00
Closing this as fixed.

**Closed by mikela-valve** 2019-07-28 20:00 UTC
Labels: Counter-Strike
