### ISSUE TITLE
CS 1.6 - Scope crosshair problem

### ISSUE THREAD

**Issue by swhat242** [ValveSoftware/halflife#3010] opened 2020-12-10 14:12 UTC
I have a problem with scope (crosshair) on all sniper weapons. Red dot falls off the black line. Scope crosshair is laggy, jittering when i'm moving it slowly. Sometimes it won't move at all. I tried to change sensitivity, mouse dpi, zoom sensitivity ratio, resolution... I even tried to use a different mouse. Nothing helped. What should I do?

![20201208173757_1](https://user-images.githubusercontent.com/75794148/101782690-9ff78a80-3af9-11eb-8ab3-82bccf7adf85.jpg)

**Comment by BlackShadow** [comment] 2020-12-12 06:15
Duplicate of #154

**Comment by kisak-valve** [comment] 2020-12-12 12:49
Thanks @BlackShadow, closing as a duplicate.

**Closed by kisak-valve** 2020-12-12 12:49 UTC
Labels: Counter-Strike
