### ISSUE TITLE
[CS 1.6] hitbox problem

### ISSUE THREAD

**Issue by realeti** [ValveSoftware/halflife#3205] opened 2021-12-10 11:44 UTC
Hello! This old issue has already been reported here - https://github.com/ValveSoftware/halflife/issues/2154, but the comments were closed there and it's been almost 3 years now. The problem is very critical.

When will they be able to release the updated version?

Some people fixed it on the client - https://www.youtube.com/watch?v=llq_Nam9mf4

**Comment by kisak-valve** [comment] 2021-12-10 12:46
Hello @realeti, please do not intentionally open duplicate issue reports. Closing as a duplicate of #2154.

**Closed by kisak-valve** 2021-12-10 12:46 UTC
