### ISSUE TITLE
[CS] Counter Strike completely broken after 25th update

### ISSUE THREAD

**Issue by FEDERICOMB96** [ValveSoftware/halflife#3553] opened 2023-11-22 19:10 UTC
Hi, these are some things I found quickly when starting the game.

- Main menu half life style and sounds
- Options -> Crosshair appearance image broken
- Half Life movement
- CT's can't buy
- CT's start with only knife
- CT's can move during freezetime
- TT's starting weapon is USP
- When the terrorist die, a scientific scream is hear from half life and spawn gibs

https://www.youtube.com/watch?v=Clz-3rd17oA

![20231122160529_1](https://github.com/ValveSoftware/halflife/assets/41979395/9a1331e8-e0cd-44d0-bf27-e54f905bca97)

**Comment by kisak-valve** [comment] 2023-11-22 19:52
Hello @FEDERICOMB96, in general, multi-issue issue reports are bad for any issue tracker. These issues should be reported separately so that they can be tracked properly.

**Comment by stacksmash76** [comment] 2023-11-22 20:34
> CT's can't buy
> CT's start with only knife
> CT's can move during freezetime
> TT's starting weapon is USP
> When the terrorist die, a scientific scream is hear from half life and spawn gibs

Can't reproduce any of these on a fresh install in a new localhost game. Are you running a dedicated HLDS instance?

**Comment by di57inct** [comment] 2023-11-22 20:46
i can confirm all these problems. windows 11 "new game" tested with and without steam networking.

**Comment by CS-PRO1** [comment] 2023-11-22 21:06
Can confirm all of these. I'm pretty sure they never tested this update before rolling it out
The view bobbing from HL1 is here as well as the view roll, the HUD doesn't scale, the thumbnails in the VGUI menus are misaligned, the main menu background is scaled weirdly in 1080p, the settings menu is broken af.
And that's what i found in 3 minutes of just launching the game

**Comment by CS-PRO1** [comment] 2023-11-22 21:09
> Hello @FEDERICOMB96, in general, multi-issue issue reports are bad for any issue tracker. These issues should be reported separately so that they can be tracked properly.
> 
> For tracking purposes, only the first issue on the list will be tracked here.

@kisak-valve Genuine question, does anyone from the people working on Goldsrc updates right now even look at this github page for bugs?

**Comment by bjrkk** [comment] 2023-11-22 21:35
In regards to the strange game play changes: seems like whoever built the Windows binaries for Counter-Strike accidentally compiled with Terror-Strike (early L4D1 prototype) code enabled. Uhh..

Under Linux, everything works correctly.

**Comment by SirYodaJedi** [comment] 2023-11-22 23:30
Well, the Terror-Strike code seems to be disabled now.

**Comment by Eoin-ONeill-Yokai** [comment] 2023-11-23 03:41
CS 1.6 seems to crash immediately after pressing the tab key to view player scores on my Linux system. 

```
Distribution: Fedora Silverblue 39
Kernel: 6.5.11-300.fc39.x86_64 
DE: GNOME 
CPU: AMD Ryzen 7 5800X (16) @ 3.800GHz 
GPU: AMD ATI Radeon RX 590 
Memory: 7165MiB / 64205MiB 
```

**Comment by KarKarKarKarkarkar** [comment] 2023-11-23 06:40
@kisak-valve 
```
Unable to connect to Steam
Host_EndGame: Server disconnected
```
After 5 minutes playing on any servers.

**Comment by Maxi605** [comment] 2023-11-24 17:44
Do we know if the main menu changes intended? if so, they should be optional and default should be the steam_legacy menu.

**Comment by unattendedplayer** [comment] 2023-11-24 20:42
ClientScheme.res from an older version should restore the old menus.

**Comment by mlibre2** [comment] 2023-11-25 14:22
I assume that the developers of such updates are aware of the reports on [Steam](https://steamcommunity.com/app/10/discussions/) as well.

**Comment by shawns-valve** [comment] 2024-10-15 23:58
Closing -- CS was updated late last year to fix compatibility issues with the 25th anniversary update.

**Closed by shawns-valve** 2024-10-15 23:58 UTC
Labels: Counter-Strike
