### ISSUE TITLE
[CS 1.6] May 17 update : numerous issues 

### ISSUE THREAD

**Issue by ade-davey** [ValveSoftware/halflife#1141] opened 2013-05-17 13:50 UTC
CS 1.6 issues since May 17 update:
1. LH model only
2. Buy menu missing
3. SAY is just displaying %%1 : %%2
4. Gun fire sound is missing, however reload/ etc are fine
5. Radar is missing
6. Money value missing
7. Bind bought guns (as menu is missing) only 2 weapons available, eg pri and secondary, missing knife / nades, no switching on mouse wheel or keyboard numbers, only last/next switch.

**Comment by SamVanheer** [comment] 2019-05-05 09:37
This issue is a duplicate of #1140 and has the same solution. This can be closed as well.

**Comment by kisak-valve** [comment] 2019-05-05 12:44
Closing per the last comment.

**Closed by kisak-valve** 2019-05-05 12:44 UTC
