### ISSUE TITLE
[HL] Bugs regarding standard weapons

### ISSUE THREAD

**Issue by UCyborg** [ValveSoftware/halflife#617] opened 2013-02-26 12:29 UTC
### Crowbar

If you try to beat dead body with the crowbar, animation doesn't play and crowbar is rapidly hitting it until it gets gibbed. Also if cl_lw is disabled, swinging with it through the air makes it look like the animation and accompanying sound restart in the middle of it before they finish.
### Shotgun

Holding the +attack button prevents cocking sound from being heard after firing a shot, however it starts if you release the button while animation is still playing.
### Gluon gun

Beams fired from it look completely different, depending on the cl_lw setting. It looks correct with cl_lw disabled (but only in singleplayer, see comments below for details).
### Trip mine

The viewmodel appears zoomed in with cl_lw disabled right after you select it from inventory. It appears normal after you place one mine.
### Rocket launcher

After you fire a rocket and continue to hold +attack button after rocket has exploded, click sound (357_cock1.wav) loops rapidly, instead of just playing once. With cl_lw enabled, multiple instances of that sound are looping.
### Python

Similar problem as with rocket launcher, except that click sound is looping slower and weapon prediction attempts to start reload animation with every click.

**Comment by SamVanheer** [comment] 2016-09-15 18:19
The crowbar issue happens because dead entities being hit causes it to skip the code that sets the delay before the next attack.
See this if statement: https://github.com/ValveSoftware/halflife/blob/5d761709a31ce1e71488f2668321de05f791b405/dlls/crowbar.cpp#L266

The Egon gun sprite issue happens because the client doesn't handle it if cl_lw is on.

For multiplayer when cl_lw is off, it does create the sprite, but only shows it when it hits something it can damage. This is to reduce bandwidth usage.
See this if statement: https://github.com/ValveSoftware/halflife/blob/5d761709a31ce1e71488f2668321de05f791b405/dlls/egon.cpp#L269

**Comment by SamVanheer** [comment] 2016-11-04 23:35
The second issue with the Crowbar happens because the event for handling crowbar playback is played twice in close succession. I've fixed this issue in my codebase, here's the fix: https://github.com/SamVanheer/HLEnhanced/blob/3fe34139cebd6ded29ce690cae6026b661dfd0ca/game/shared/entities/weapons/CCrowbar.cpp#L128

Adding the if check here prevents the problem from occurring. This didn't happen in older versions of the game because events were added later.

**Comment by UCyborg** [comment] 2016-11-20 02:21
Nice work! So players can just take your codebase and benefit from numerous bugfixes.

**Comment by SamVanheer** [comment] 2016-11-20 09:16
Yup, that's the idea. There are also a bunch of new features added to it, i'm currently implementing VGUI2.

**Comment by SamVanheer** [comment] 2019-04-25 16:46
@mikela-valve Some of these issues can be fixed.

**Comment by rtxa** [comment] 2019-04-25 18:49
@SamVanheer check this issue with hornet gun
https://youtu.be/uKkJPFmDW9Q?t=269

**Comment by SamVanheer** [comment] 2019-04-25 19:16
I was unable to reproduce that issue, but i do remember it happening before. Has it happened to you recently?

**Comment by Matthaiks** [comment] 2019-04-25 20:02
https://youtu.be/uKkJPFmDW9Q?t=5m11s
It still "grinds" sometimes.

**Comment by mikela-valve** [comment] 2019-05-17 04:28
Fixed all but the crowbar hitting dead entities and the new hornet gun report. Will be included in next beta update.

**Comment by mikela-valve** [comment] 2019-05-21 19:16
Fixed in 'Exe build: 11:11:14 May 21 2019 (8244)'.

**Comment by agrastiOs** [comment] 2019-05-21 20:51
Indeed they're all fixed(except crowbar and hornet gun).

**Comment by oaus** [comment] 2019-05-21 20:57
> Indeed they're all fixed(except crowbar and hornet gun).

https://github.com/ValveSoftware/halflife/issues/617#issuecomment-493315229

**Comment by Matthaiks** [comment] 2019-05-21 21:16
> 
> 
> Indeed they're all fixed(except crowbar and hornet gun).

And the Gluon Gun?

**Comment by Sockman1** [comment] 2019-05-21 22:31
Gluon Gun doesn't appear to have been fixed in the newest beta. The energy cloud still only appears with cl_lw 0

**Comment by mikela-valve** [comment] 2019-05-22 01:04
@Sockman1 I intentionally skipped modifying the Gluon Gun based on @SamVanheer’s comments. I figure that if someone is deliberately running with `cl_lw`enabled that I should avoid adding anything that would affect performance in any way possible.

**Comment by BlackShadow306** [comment] 2019-05-22 16:37
@mikela-valve It seems cl_lw "1" causes double-reloading in several weapons. Like:

357
Glock
MP5
Crossbow

**Comment by mikela-valve** [comment] 2019-06-06 17:37
@BlackShadow306 I believe that was already reported in #2301.

@Matthaiks The gluon gun issue with `cl_lw 1` in single player will take a bit more work to fix as it requires reworking the animation that runs when prediction is enabled. The reason it works with prediction disabled is that the client itself creates the effects rather than the server so they display properly. With prediction enabled it relies on the animation that plays to do all of the effects but the animation was only created with the beam effects and not the flare effect. If you'd kindly make another issue to track that specific work I'd like to close this one as fixed.

**Comment by mikela-valve** [comment] 2019-06-06 18:30
Closing as fixed.

**Closed by mikela-valve** 2019-06-06 18:30 UTC
Labels: Fix proposed, Half-Life, reviewed

**Comment by CS-PRO1** [comment] 2019-06-06 18:34
@mikela-valve Crowbar hitting dead entities was fixed?

**Comment by mikela-valve** [comment] 2019-06-06 18:38
That one I left since it seems to be intentional logic in the crowbar code, I imagine to make it quicker to gib dead things. If that game logic does bother people enough I'd be willing to change it, but I concluded that it wasn't really a bug in the way that the other issues were so I decided to leave it for now.

**Comment by CS-PRO1** [comment] 2019-06-06 18:47
Good, I asked since when I told some people about it they were a bit sad about it since it's become a part of the game's logic and nostalgia for some reason.. Thanks for reply!

**Comment by EgonHoustuvk** [comment] 2019-07-08 22:52
I seem to remember a time when the crowbar behaved normally while gibbing dead bodies, and the rapid swinging bug was introduced in an update at some point. I could be mistaken, since it would have been several years ago when I remembered the crowbar not having this bug.

**Comment by di57inct** [comment] 2019-07-09 00:35
Its always been there as far as I remember.

**Comment by UCyborg** [comment] 2019-07-13 15:22
The crowbar rapid swinging bug exists since patch version 1.1.0.8. It works correctly in all previous versions.

[Video showcasing that and some other differences](https://www.youtube.com/watch?v=uKkJPFmDW9Q)

**Comment by agrastiOs** [comment] 2019-07-16 21:41
@UCyborg Could it be an intended change by Valve because it seems to be intentional logic in the crowbar code? It isn't mentioned in the 1.1.0.8 patch notes, however... I opened a separate issue for this (#2590) just like a separate issue was opened for the Gluon Gun.
