### ISSUE TITLE
[Feature request] Add "sv_full_alltalk" or make "sv_alltalk" more customizable.

### ISSUE THREAD

**Issue by basuritashka** [ValveSoftware/halflife#2273] opened 2019-04-24 23:11 UTC
It is already done on ReGameDLL where you can set a value between 0 and 4. 

`sv_alltalk` on ReGameDLL

`0` dead don't hear alive
`1` no restrictions
`2` teammates hear each other
`3` Same as 2, but spectators hear everybody
`4` alive hear alive, dead hear dead and alive.

**Comment by kisak-valve** [comment] 2019-04-24 23:15
Hello @basuritashka, this is effectively a duplicate of #1161 / #1962. Closing in favor of the existing feature requests.

**Closed by kisak-valve** 2019-04-24 23:15 UTC
