### ISSUE TITLE
Incorrect display of unicode characters in chat with 'dropshadow' flag

### ISSUE THREAD

**Issue by Splatt581** [ValveSoftware/halflife#2582] opened 2019-07-11 17:43 UTC
When `dropshadow` flag is activated (in `platform/resource/TrackerScheme.res`), Unicode characters are cut off on right side. This can be seen in the screenshots below:

Full display without `dropshadow`:
![2](https://user-images.githubusercontent.com/31417200/61072512-85147880-a424-11e9-8e2c-ddf26216c71b.jpg)

Cropped on right side with `dropshadow`:
![1](https://user-images.githubusercontent.com/31417200/61072646-c3aa3300-a424-11e9-8e6c-3663e55833c1.jpg)

**Comment by Mistrick** [comment] 2019-07-11 17:49
duplicate of #1315

**Comment by kisak-valve** [comment] 2019-07-11 17:56
Hello @Splatt581, as noted, this issue is already being tracked at #1315. Closing as a duplicate.

**Closed by kisak-valve** 2019-07-11 17:56 UTC
