### ISSUE TITLE
[Feature Request] _special 

### ISSUE THREAD

**Issue by BlackShadow306** [ValveSoftware/halflife#2384] opened 2019-05-04 01:28 UTC
Can we get _special back please? It was removed because of few blatant people requested.. What's more worse is they probaly doesn't even play the game anymore when they're requested  it. And they still probaly wont. And it was removed carelessly. People had to downgrade their game in order get _special back which is kinda disappointing. So hear us out please.

**Comment by kisak-valve** [comment] 2019-05-04 01:35
Duplicate of #1154 / #1838.

**Closed by kisak-valve** 2019-05-04 01:35 UTC
