### ISSUE TITLE
Make the actual crosshair more customizable (CSGO like)

### ISSUE THREAD

**Issue by basuritashka** [ValveSoftware/halflife#2255] opened 2019-04-24 17:02 UTC
Title.

Nothing else to add, on higher resolutions the Crosshair becomes really thin and a lot harder to see and more even on maps with a lot of brightness.

Example:
`cl_crosshairstyle`
`cl_crosshairdot`
`cl_crosshairthickness`
`cl_crosshair_drawoutline`
`cl_crosshair_outlinethickness`

**Comment by kisak-valve** [comment] 2019-04-24 17:07
Duplicate of #265 / #2105.

**Closed by kisak-valve** 2019-04-24 17:07 UTC
