### ISSUE TITLE
[Half-Life] Getting stuck on transition to c1a2b

### ISSUE THREAD

**Issue by floppyD** [ValveSoftware/halflife#2827] opened 2019-12-14 02:01 UTC
Video related, if you enter c1a2b while touching the wall on left, you'll get stuck.
https://streamable.com/68jdg

Game version:
Protocol version 48
Exe version 1.1.2.2/Stdio (valve)
Exe build: 15:17:55 Jul 24 2019 (8308)

**Comment by BlackShadow** [comment] 2019-12-15 22:50
This is not a C1A2B related only. If you stuck in edges during level change player starts stuck in next level. This happens because the levelchange trigger slighty warps player to the next level. If the player is on edge,  levelchange trigger warps you inside that of that tiny edge.

**Comment by BlackShadow** [comment] 2019-12-15 22:50
This is not C1A2B related only. If you stuck in edges during level change player starts stuck in next level. This happens because the levelchange trigger slighty warps player to the next level. If the player is on edge,  levelchange trigger warps you inside that of that tiny edge.

**Comment by CS-PRO1** [comment] 2019-12-16 11:05
Agreed, happens in many areas especially in level changes through vents

**Comment by Solokiller** [comment] 2021-02-13 17:28
This is a duplicate of #1108. Both are cases of the player getting clipped into geometry during a level transition.

**Comment by kisak-valve** [comment] 2021-02-13 17:51
Thanks @Solokiller, closing in favor of the older issue report.

**Closed by kisak-valve** 2021-02-13 17:51 UTC
Labels: Half-Life
