### ISSUE TITLE
Нitbох nоt fiхеd

### ISSUE THREAD

**Issue by zoruamonster** [ValveSoftware/halflife#2801] opened 2019-12-08 04:31 UTC
Рlеаsе fiх HIТBОХ РRОВLЕМ 
https://github.com/ValveSoftware/halflife/issues/2154
**SkillartzHD opened this issue on 20 Apr** but nоt fiхеd!

**Comment by kisak-valve** [comment] 2019-12-08 13:56
Hello @zoruamonster, please do not intentionally open duplicate issue reports.

Closing as a duplicate of #2154.

**Closed by kisak-valve** 2019-12-08 13:56 UTC

**Comment by zoruamonster** [comment] 2019-12-26 19:54
@kisak-valve but this not fixed, please fix hitbox, or it impossible ?!
