### ISSUE TITLE
HL:OF - Cannot complete the game [SPOILERS]

### ISSUE THREAD

**Issue by nmirthes** [ValveSoftware/halflife#917] opened 2013-04-03 09:32 UTC
![2013-04-03_00001](https://f.cloud.github.com/assets/3878034/332957/2354adc8-9c41-11e2-9e8f-ddc2715ff296.jpg)
Upon defeating the end boss on map of6a5 (Worlds Collide), map of7a0 (Conclusion) fails to load.

**Comment by neagix** [comment] 2015-07-19 16:08
2+ years now, still there

**Comment by alfredVALVEisAshitHEAD** [comment] 2015-08-02 07:51
Alfred-Valve is a shit head. This is more than 2 years since this has been an issue and it is still going on. No progress, no update. Its dead. There is just no ending for this game. The game in general was pretty rough. Enemies and allies would get stuck in doorways or the middle of the hall, sometimes allies would forget to follow and you have to go remind them, the controls were unsteady, crates took a range of shots with the alien volt gun and sometimes would just never break and a knife was necessary. But all of those things are excusable. But not having an ending is a pretty necessary part of the game. Lazy game development. The half life episodes 1 and 2 are great and leagues better than this. But there is no HL3, not now, and probably not ever, so cheap knockoffs are all we've got.

**Comment by di57inct** [comment] 2015-08-02 11:31
It's not his fault alone. Valve is generally like that(doesn't give a single fuck about its users).

**Comment by neagix** [comment] 2015-08-02 12:00
hey, that's a bit harsh, to create a github account just to offend @alfred-valve :) I think your comment should be moderated because of that.

@alfred-valve is (probably) an employee, so he has to do stuff second priorities etc. if his employer doesn't tell him "fix that bug", he probably can't.

But you want to know what is really funny about "community", "open source" and "social" these days? all it takes for you to make things move is make a blog post detailing the average quality of (in this case Valve's) projects on GH, issues open etc with some infogarbage and nice charts, and then make noise on twitter, facebook and the like and maybe in the end you get a response :) I am totally not going to spend my time like that, but if you want things to get done - either fix them yourself (when you can, of course), or alternatively make a "gentle" push for them ;)

Offending doesn't work and it's lame.

**Comment by JoelTroch** [comment] 2015-08-02 12:18
For the people who are complaining about this issue not fixed in 2 years. @alfred-valve said he COULDN'T reproduce the issue on his end. So tell me how he can fix that issue if he can't reproduce it?

This one is for the "toxic" people, I'm talking to the people who made the "fake HL3 commit", that weird GitHub account offending @alfred-valve and anyone mad at Valve not fixing stuff. If you think Valve is gonna change a single line of code after all that stuff, you are wrong.

Feel free to agree, disagree at my opinion. To stay "on-topic", I'm gonna investigate that issue on my end, see if it's still there and fix it IF i can.

@dscharrer Valve isn't allowed to publish the Opposing Force source code because Gearbox Software still have the rights to them, same goes for Blue-Shift.

PS: Sorry for grammar errors and stuff, writing on phone isn't easy.

**Comment by alanjames1987** [comment] 2015-08-03 07:45
@neagix I agree that the comment from @alfredVALVEisAshitHEAD should be moderated. It is not constructive in tracking down the issue or even reporting the issue.

Because Opposing Force is closed source we can't do more than report the issue and attempt to provide all data to debug the issue. Complaining might help but not to the disrespectful level that @alfredVALVEisAshitHEAD has done.

**Comment by stevethepocket** [comment] 2015-08-03 08:09
It's been constructive in demonstrating how devoid of Valve presence this whole site has gotten, at least. Like how gang graffiti in a run-down neighborhood shows that nobody cares about it anymore.

**Comment by malortie** [comment] 2015-08-07 11:52
_The following suggests a fix, but is not limited to this issue._

As stated above, I will try to state everything here, to avoid multiple posting as this does not fit the current issue. I unfortunately had nowhere else to post. Despite this, I feel this needs to be put here to let as many people know as possible.

---

We are able to understand it is beyond Valve's possibilities to solve it since [Gearbox](https://en.wikipedia.org/wiki/Gearbox_Software) is the main developer for both expansions, [Opposing Force](https://en.wikipedia.org/wiki/Half-Life:_Opposing_Force) and [Blue Shift](https://en.wikipedia.org/wiki/Half-Life:_Blue_Shift). 

At this time, and until [Valve](http://www.valvesoftware.com/) manages to contact [Gearbox](https://en.wikipedia.org/wiki/Gearbox_Software) for inquiry about source code and issues, I am currently proposing an alternative, which is an attempt to recode from scratch (using the latest source code from Valve's repository) both games.

[Here is a link to work in progress.](https://youtu.be/2MYqsQTk33M)

Note that Blue-Shift levels run on a modified format of [vbsp](https://developer.valvesoftware.com/wiki/VBSP), which makes them unable to launch in a typical Half-Life mod. I used the tools found in _Blue-Shift: Unlocked_, another mod, to port the game maps to the Half-Life level [vbsp](https://developer.valvesoftware.com/wiki/VBSP) format, so they are able to run. 

Here are links to both [Opposing Force](https://github.com/malortie/halflife/tree/branch-malortie-op4) and [Blue Shift](https://github.com/malortie/halflife/tree/branch-malortie-bshift) branches, if anyone is interested in contributing.

I am aware that this might not be an easy task, and is a project I am willing to invest in, as far as possible and hope to make it successful. I do believe if we can get enough people to contribute, we could finish this project which should result in a legit port of both games, and at the same time, would run on the latest Half-Life version, which provides support for [Steam workshop](https://en.wikipedia.org/wiki/Steam_(software)#Steam_Workshop) along with [Steampipe](https://developer.valvesoftware.com/wiki/SteamPipe). 

Hope it helps.

**Comment by JoelTroch** [comment] 2015-08-07 13:37
@malortie I was already working on that kind of project weeks ago, glad to see I'm not the only one ^^

If you wish I can share some of my work with you (I can't right now due to real life priorities and ARRANGEMENT).

**Comment by malortie** [comment] 2015-08-07 13:58
@JoelTroch 

Thanks for replying.

I sure am interested, as any help is welcomed. 

I made you a contributor on my repository, so that you will be able to commit and make changes. I assume that you have more years of experience than me with commits and anything related to this, so I am pretty convinced that you will do fine.

Other people who wish to contribute should report to the repos specified in my latest post. See Pull Requests. Here are the links. [Opposing Force](https://github.com/malortie/halflife/tree/branch-malortie-op4) and [Blue Shift](https://github.com/malortie/halflife/tree/branch-malortie-bshift).

**Comment by vfjpl** [comment] 2016-07-03 21:57
Still present.

**Comment by UndeadScottsman** [comment] 2016-07-04 04:30
Just a head's up since I see people respond to this from time to time.

Opposing Force is no longer being worked on; any issues left in the game Valve has decided to not fix.  This includes this level transition bug.

If you want a quick and dirty fix, open the console (hit the '~' key) and type "map of7a0" and that will load the next level.

**Comment by SamVanheer** [comment] 2016-08-19 13:15
Based on the reports in this issue and what i've learned by reverse engineering the boss entity, i have come to the conclusion that this is probably caused by an uninitialized variable that triggers a race condition in COFGeneWorm::DyingThink.

This think is set when the Gene Worm dies, and is responsible for teleporting the player by calling touch on the trigger_teleport named "GeneWormTeleport".

However, prior to that chunk of code running, there is another check:

```
  if ( this->m_fSequenceFinished && pev->deadflag == DEAD_DYING )
  {
    UTIL_Remove( this );
    return;
  }
```

What you're seeing here is a check to remove the monster once its "death" sequence has completed.

The reports that players gave about the monster moving really fast is what confirms it. It plays the sequence too quickly, resulting in this check hitting before the player teleport check, which has these conditions:

```
if ( gpGlobals->time - m_flDeathStart >= 15.0 )
```

m_flDeathStart is set to gpGlobals->time the first time the think function runs. There is thus a 15 second time window between starting to die and dying.

The frame settings seem to be the cause of the problem.

This is the code that handles it, called in DyingThink the first time it runs:
```
    pev->frame = 0;
    int iEndingSequence= CBaseAnimating::LookupSequence("death");
    int iDir;
    v9 = iDir == 0;
    v10 = iDir < 0;
    pev->sequence = FindTransition(pev->sequence, iEndingSequence, &iDir);
    if ( iDir <= 0 )
      pev->frame = 255.0;
    else
      pev->frame = 0;
```

The problem appears to be that iDir is not initialized. FindTransition uses the value to determine which node to use as the exit node. This can result in the wrong sequence being returned.

I've experienced stack values having default values on some platforms and garbage on others, which could explain why this only happens on Linux/Mac.

pev->frame is set to 255 if iDir is <= 0, so it's possible that this causes the sequence to play very fast. Since sequences normally play from 0 to 255, the m_fSequenceFinished variable will be set to true on the next frame.

I can't be absolutely sure due to compiler optimizations and disassembler inaccuracies, but this should be double checked.

Since i can't fix this, i'll instead offer a ripent fix to bypass this approach to changing the level: https://dl.dropboxusercontent.com/u/46048979/of6a5_fixed.rar

I've added a trigger_relay named GeneWormDead that triggers the exit sequence, which will change the level. You won't be teleported to a black room, but the rest of the ending will still work as it should.

Note that this includes the bsp as well. If that's a problem, i can exclude it and only upload the .ent file.

**Comment by jeisoncp** [comment] 2018-12-02 23:10
> Still present.

Until today...

**Comment by m-svo** [comment] 2019-01-03 19:07
Just had this issue, the game is up to date. Debian 9 stable, Steam beta.

**Comment by SamVanheer** [comment] 2019-01-25 21:03
I just replicated this after recreating the original source code. Initializing `iDir` to 0 fixes this.

**Comment by alexhultman** [comment] 2019-01-25 21:14
This is interesting. It makes sense that old game bugs never were caught and fixed if the OS never really triggered them. You could probably also find this issue by running valgrind.

**Comment by mikela-valve** [comment] 2019-04-20 03:01
Hi @SamVanheer, this should be fixed in the current OpFor beta.

**Comment by SamVanheer** [comment] 2019-04-20 07:55
I tested it, it looks like i gave you the wrong code. The if check should be inverted:
```
if( iDir > 0 )
	pev->frame = 255;
else
	pev->frame = 0;
```

Right now the boss catapults out of the area and the map never ends, but this change should fix it.

**Comment by mikela-valve** [comment] 2019-04-24 00:42
There might be something else going on since I think the check is correct already. 

It looks like iDir is used as a signedness flag coming out of FindTransition for determining whether the frame starts at the end or at the beginning, but FindTransition presumes that the default direction is positive, so there are a number of paths out of it where it doesn't set iDir (which is how we end up in this in the first place). I think the solution here is just to initialize iDir to 1 instead of 0, then it should properly start the frame at 0 and run the animation successfully.

**Comment by mikela-valve** [comment] 2019-05-21 19:38
Fixed in beta 'Exe build: 11:12:36 May 21 2019 (8244)',

**Comment by mikela-valve** [comment] 2019-06-02 08:39
Closing as fixed.

**Closed** 2019-06-02 08:43 UTC
Labels: Half-Life:Opposing Force, reviewed

**Comment by kaishh** [comment] 2019-06-02 11:27
:tada:

**Comment by kforner** [comment] 2019-06-03 08:27
Wow after 6 years! Thanks
