### ISSUE TITLE
[CS 1.6] Slowly client download

### ISSUE THREAD

**Issue by Soyrce** [ValveSoftware/halflife#2650] opened 2019-07-30 07:44 UTC
So, i set my all link/ sv_ at server.cfg and also amxx.cfg if is matter but sometimes client still got a slow download 3min and some not.
ThaT fastd worked perfect wiht 2GB
What can be wrong?

**Comment by Maxi605** [comment] 2019-07-30 10:54
Did you restarted the server?

**Comment by Soyrce** [comment] 2019-07-30 13:37
Ofc i did a restart server after upload X models to SERVER And fastdo but people should do in console _restart to fix this bug

**Comment by SomewhereLost** [comment] 2019-07-31 05:15
Did you set the values properly?

Me personally have this in amxx.cfg instead of server.cfg

`sv_allowupload "1" 
sv_downloadurl "http://LINK"
sv_allowdownload "1"`

**Comment by Soyrce** [comment] 2019-07-31 06:03
Yeah yeah I'm not a little kid who doesn't understand, I've been dealing with it for years

**Comment by basuritashka** [comment] 2019-07-31 06:05
#2238

**Comment by 4D1G06** [comment] 2019-07-31 11:04
The problem is significantly in your server [configuration], I've never had a single problem with FDL, at least from 2010. Some hosts deny requests from certain games, same goes for HL.

**Comment by Soyrce** [comment] 2019-07-31 13:01
So what i have to do with my host vps, is private

**Comment by Maxi605** [comment] 2019-08-01 01:36
> So what i have to do with my host vps, is private
> 
> My hosting said that i have to turn of the server before upload models and sound to fix fastdl, why?

Probably so it reads the new files beign requested, i don't have this issue with my fastdl or my servers, could be the fastdl you're using is not correctly configurated.

**Comment by wilianmaique** [comment] 2019-08-01 20:56
There is really still this bug., Suppose you are inside the server, there you go and add any plugin that contains models / resources, you upload on the server and fastdownload. When you change the map to update the download of new files are slow, to fix I have to quit the game and enter the server again so the download will get faster.

sorry for my bad english

**Comment by Soyrce** [comment] 2019-08-01 21:31
Exactly Wilian , same prob

**Comment by SamVanheer** [comment] 2019-08-02 06:54
Duplicate of #2238

I explained why this happens there.

**Comment by kisak-valve** [comment] 2019-08-02 10:55
Closing as a duplicate of #2238.

**Closed by kisak-valve** 2019-08-02 10:55 UTC
Labels: Counter-Strike
