### ISSUE TITLE
[GoldSource] Download secondary progress bar doesn't work properly

### ISSUE THREAD

**Issue by s1lentq** [ValveSoftware/halflife#2124] opened 2019-03-29 09:38 UTC
You may notice this when you download a large file using FastDL.
While download a file (e.g >= `100 MB`) secondary progress bar always be 100 percent.
![DownloadProgressPct_1](https://user-images.githubusercontent.com/5860435/55223136-1c700a00-5240-11e9-99fa-b6c9b0742a91.png)

Issue is in the function `DownloadManager::CheckActiveDownload`

![DownloadProgressPct_3](https://user-images.githubusercontent.com/5860435/55223186-3ad60580-5240-11e9-9db2-4d33286ebf4b.png)

![DownloadProgressPct_4](https://user-images.githubusercontent.com/5860435/55224355-eaac7280-5242-11e9-9a6f-a2570a6145fe.png)

In my opinion, a fixes should be like this
![DownloadProgressPct_6](https://user-images.githubusercontent.com/5860435/55224361-eda76300-5242-11e9-9e3b-c356608b2154.png)

Finally, we got the secondary progress bar working correctly
![DownloadProgressPct_2](https://user-images.githubusercontent.com/5860435/55223592-1c243e80-5241-11e9-9eee-9288e98fb4d7.png)

**Comment by s1lentq** [comment] 2019-03-29 09:42
#934 related

**Comment by fl0werD** [comment] 2019-04-20 20:22
bump

**Comment by oaus** [comment] 2019-04-26 03:44
@mikela-valve Is there a possibility to add this feature request https://github.com/ValveSoftware/halflife/issues/934#issuecomment-23310086 , also if Multithreading is too much work then just should just use one progress bar with file size and download speed with the total amount of files that we will download.

Examples:
![E.g. 1](https://user-images.githubusercontent.com/43151226/56782106-e6706800-67a2-11e9-98ce-8efcbd65eba7.png)
![E.g. 2](https://user-images.githubusercontent.com/43151226/56782107-e6706800-67a2-11e9-9cd6-fec5aabdd4d6.png)

**Comment by R4to0** [comment] 2019-05-16 01:17
> 
> 
> also if Multithreading is too much work then just should just use one progress bar with file size and download speed with the total amount of files that we will download.


"Multithreading" is a thing since 2013. If you check active TCP connections you'll notice that 3 files are downloaded at same time (it seems it is set to 5 in the engine, not sure). It just needs to be updated to display them all at same time, or like you suggested, show how many files are being downloaded at that moment.

**Comment by MatiasEsf** [comment] 2019-05-16 04:21
good gif bb

**Comment by mikela-valve** [comment] 2019-05-16 21:08
A fix to the progress bar not updating properly will be included in the next beta update. I won't be adding additional details to the dialog just yet but will consider it for the future and track work on it in #934 if I do.

**Comment by mikela-valve** [comment] 2019-05-21 19:16
Fixed in 'Exe build: 11:11:14 May 21 2019 (8244)'.

**Comment by Mistrick** [comment] 2019-05-21 19:46
now load bar disappeared
connection to server became very fast but without load bar.
i try connect to server with resourses which i don't have and i load all resourses with black screen, console and servers window

**Comment by mikela-valve** [comment] 2019-05-21 20:17
Sorry, just reproduced this based on your info. Part of this request is serviced in Steam and it looks like I was getting a different response based on the version I was using. I'll update beta later with this working.

**Comment by mikela-valve** [comment] 2019-05-23 00:31
This regression should be fixed in the updated beta 'Exe build: 16:32:50 May 22 2019 (8245)'.

**Comment by s1lentq** [comment] 2019-05-23 06:03
I can confirm that this issue is fixed in the current beta

**Comment by mikela-valve** [comment] 2019-06-02 08:38
Closing as fixed.

**Closed** 2019-06-02 08:43 UTC
Labels: Fix proposed
