### ISSUE TITLE
Music cuts out on loading in expansions/mods

### ISSUE THREAD

**Issue by Conor715** [ValveSoftware/halflife#2976] opened 2020-09-20 22:42 UTC
In the base game, the mp3 music will continue to play after a loading screen is triggered, but in mods and official expansions, it just cuts out. I've searched online for a while to find some kind of workaround, but i haven't been able to find anything.

**Comment by BlackShadow** [comment] 2020-09-21 04:28
Duplicate of #570

**Comment by kisak-valve** [comment] 2020-09-21 11:30
Closing in favor of the older issue report.

**Closed by kisak-valve** 2020-09-21 11:30 UTC
