### ISSUE TITLE
[GoldSrc][REQUEST] ViewModel Properties, SS hud.txt and Limit Extension 

### ISSUE THREAD

**Issue by 6y6JIuK** [ValveSoftware/halflife#2215] opened 2019-04-22 15:47 UTC
> #199 Adding opportunity for edit properties of view model like any other entity's properties
```
pev->framerate
pev->frame
Rendering Stuff (issue199)
pev->body   ( btw haves a bad limit in value 255)
pev->skin     ( i think this one haves size equal byte too)
pev->controller

About pev->body values:
Example of the view model that have value of pev->body more than 255
https://www.dropbox.com/s/8hri10ey901ad5p/v_ak47_beta3.mdl?dl=0

For any other entities i can use values more than byte with edited delta.lst, 
there are limited only by integer range, so its not a problem
Example of the player model with a lot of bodygroups
https://www.dropbox.com/s/frcxq8vynw472bk/umb_hum_b5.mdl?dl=0

```

> #440  Posibility to make cache data of hud.txt from server side

```
It can be very useful for mod's customizing: deathmsg icons, hp, ar and etc things
```

> #12 Extending some engine limits
```
There are a lot of old engine limits that should be increased in values
like a models, sounds or buffer size of SVC_SENDRESOURCES (big length of file's path)
```
thanks

**Comment by ArmynC** [comment] 2019-04-22 15:53
These 'tickets' are already opened... if you got something new to add, reply there (or atleast the majority of your request shouldn't be opened already)... Also, you can tag some Valve rep. right in that issue.

**Comment by kisak-valve** [comment] 2019-04-22 17:30
Closing as a duplicate of the existing issue reports.

**Closed by kisak-valve** 2019-04-22 17:30 UTC
