### ISSUE TITLE
Opposing Force voice chat not working

### ISSUE THREAD

**Issue by djearthquake** [ValveSoftware/halflife#3288] opened 2022-07-02 09:32 UTC
Voice chat worked fine when this debuted on Linux in 2013, hasn't since many updates ago.

**Comment by BlackShadow** [comment] 2022-07-18 01:41
Duplicate of #2912

**Comment by kisak-valve** [comment] 2022-07-18 01:45
Thanks @BlackShadow, closing in favor of the older issue report.

**Closed by kisak-valve** 2022-07-18 01:45 UTC
Labels: Linux, Half-Life:Opposing Force
