### ISSUE TITLE
[Half-Life: Opposing Force] Slippery Floor Bug

### ISSUE THREAD

**Issue by andrewgillich** [ValveSoftware/halflife#2946] opened 2020-08-09 19:47 UTC
There is a bug when you step on a slippery floor the slippery effect stays everywhere until you dead.

**Comment by Zhukow** [comment] 2020-08-09 20:29
yes, this problem has been present for a long time in the multiplayer game since it was updated in 2013, look how great everything was in the old build of 2009, before the update there the graphics and sliding were of high quality!

**Comment by Zhukow** [comment] 2020-08-09 21:00
I compared the pirate op4 and the Steam one and came to the conclusion that the game has become worse, you can see for yourself if you want, just create a map op4ctf_wonderland or op4ctf_hairball and run on the ice and you will understand everything yourself, who needs the link to the pirate of 2009 build as well you will be able to see the old wide textures better than those in the steam version. 
! Do not think that this is advertising, this is only a true comparison and analysis of versions !
! I am not encouraging anyone to use a pirate client !
http://new-rutor.org/torrent/137279/half-life-opposing-force-1999-pc/

**Comment by Zhukow** [comment] 2020-08-09 21:17
In general: this problem (slide bug) can be solved, but only on your server, if you replace new steam files on old files in the folder cl_dlls, client.dll and in the folder dlls, opfor.dll

**Comment by BlackShadow** [comment] 2020-08-18 23:57
Duplicate of #1542

**Comment by kisak-valve** [comment] 2020-08-19 00:02
Thanks @BlackShadow, closing in favor of the older issue report.

**Closed by kisak-valve** 2020-08-19 00:02 UTC
Labels: Half-Life:Opposing Force
