### ISSUE TITLE
[Counter-Strike 1.6] Half-Life 25th anniversary makes cs1. 6 unable to run

### ISSUE THREAD

**Issue by DarkReaper231** [ValveSoftware/halflife#3444] opened 2023-11-18 03:32 UTC
Counter Strike 1.6 can't run on Linux if 25th anniversary update is installed. The game launches but displays this error message
![IMG](https://i.imgur.com/DUyWYV0.png)

Installing the pre-anniversary branch on Half Life fixes this issue however this should probably be addressed in less inconvenient way maybe with some if else statement when `-game cstrike` is ran

**Comment by ArijanJ** [comment] 2023-11-18 06:40
Yep, same here. I sent a support ticket (HT-DPHB-XMXH-B6HD) if someone would like to take a look. I thought I would get some actual support since the Steam Deck uses Arch, but I just got a "distro not supported" response.

Here is the full report:
---
Hello,

After the recent 25-year anniversary update for Half-Life (and Counter-Strike 1.6, by extension), the game does not launch on Arch Linux (btw) with an AMD Ryzen 5 5600X.

The only thing that happens when I launch it is a black screen which looks to be around 800x600 pops up briefly and then disappears.

The logs (they are the same whether I do `./hl.sh -game cstrike` or run the game through Steam):

```Using breakpad crash handler
[S_API] SteamAPI_Init(): Loaded '/home/arijan/.local/share/Steam/linux32/steamclient.so' OK.
Setting breakpad minidump AppID = 10
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
11/17 20:06:40 Init: Installing breakpad exception handler for appid(10)/version(9885)/tid(60112)
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
SteamInternal_SetMinidumpSteamID: Caching Steam ID: 76561198246720532 [API loaded yes]
SteamInternal_SetMinidumpSteamID: Setting Steam ID: 76561198246720532
GL_SIZES: r:8 g:8 b:8 a:0 depth:24
could not load library /home/arijan/.local/share/Steam/steamapps/common/Half-Life/cstrike/cl_dlls/client.so
```

This file exists and it's the same file that's been there forever, so I can only assume that some change deeper in Half-Life is causing this.

FWIW, Half-Life launches fine.
I verified the integrity of my game files (both HL and CS) a bunch of times, with no results.

Please let me know if there's anything else that I can provide you guys with.

I would really appreciate it if someone could test this and let me know if there's something silly happening on my side.

Thanks!

**Comment by mpascual** [comment] 2023-11-18 07:21
@ArijanJ is there any way to revert the update? I'm also experiencing this error, seems like an oversight

**Comment by ArijanJ** [comment] 2023-11-18 07:25
> @ArijanJ is there any way to revert the update? I'm also experiencing this error, seems like an oversight

I’m not sure, the OP probably knows as I didn’t think of doing this, but you can try looking in the Betas tab for Half-Life, it might be there.

**Comment by DarkReaper231** [comment] 2023-11-18 07:29
> @ArijanJ is there any way to revert the update? I'm also experiencing this error, seems like an oversight

Yes. Just right click Half Life, go to properties, go to betas and select Pre-anniversary or whatever it's called. Then you can play Counter Strike fine and all other mods/extensions.

**Comment by DarkReaper231** [comment] 2023-11-18 07:29
> > @ArijanJ is there any way to revert the update? I'm also experiencing this error, seems like an oversight
> 
> I’m not sure, the OP probably knows as I didn’t think of doing this, but you can try looking in the Betas tab for Half-Life, it might be there.

Yes it is

**Comment by ArijanJ** [comment] 2023-11-18 07:44
Apparently tons of HL mods are broken, so I doubt they thought about us before pushing the update. Guess we aren’t getting any of the engine improvements :(

**Comment by JoelTroch** [comment] 2023-11-18 09:00
Duplicate of #3411

**Comment by kisak-valve** [comment] 2023-11-18 13:43
Hello @DarkReaper231, as @JoelTroch noted this issue is already being tracked at #3411.

Closing as a duplicate.

**Closed by kisak-valve** 2023-11-18 13:43 UTC
