### ISSUE TITLE
[CS1.6] Ammo is bugged while fast switching a weapon

### ISSUE THREAD

**Issue by norbee16** [ValveSoftware/halflife#2639] opened 2019-07-27 13:57 UTC
If you switch a weapon too fast a bullet will stay in the round magazine which will be still shot and deal damage. (It can be seen in the video)

https://www.youtube.com/watch?v=ROUj5Zvqgzs

**Comment by kisak-valve** [comment] 2019-07-27 14:03
Possible duplicate of #619.

**Comment by uniarch** [comment] 2019-07-27 22:34
As I know it will not deal any damage. Or please record this on some server, where it's dealing it

**Comment by norbee16** [comment] 2019-07-28 16:56
Yeah I was incorrect about it, it does not deal damage, so the problem would be the same what @kisak-valve  wrote.

**Comment by kisak-valve** [comment] 2019-07-28 17:01
Thanks for confirming, closing in favor of the existing issue report.

**Closed by kisak-valve** 2019-07-28 17:01 UTC
Labels: Counter-Strike
