### ISSUE TITLE
Extend Limitations. 

### ISSUE THREAD

**Issue by Skumek** [ValveSoftware/halflife#1605] opened 2015-04-03 19:03 UTC
It would be a good opportunity to slightly increase some max values in the 1.6/CZ engine.

Limits are based on: http://code.google.com/p/sing-engine/.
Relevant limits and value would be : 
- MAX_MODELS 2048 (default: 512) ( unique models (includes sprites and bmodels) )
- MAX_SOUNDS 2048 (default: 512) 
- MAX_BEAMS 512 (default: 64) 
- MAX_TEMPENTS 1024 (default 500) 
- MAX_MAP_MODELS 1024 (default: 256) 
- MAX_MAP_LEAFS 16384 (default: 8192) 

I think it's fair values. Of course higher values are welcomed (like Sing) but as it is, it would already be really useful. i think this would even bring more players to come back to 1.6/CZ since the servers will have more things in them. It will contribute to make everyone happy, Because: The mappers would be able to do better maps (Larger, Much more detail, etc), the coders(AMXX/MODULES) will have more room to do custom things since more resources can be used, the server-developers will see their servers crashing less often.

Thanks for reading, and i hope you will think about doing what many, many people have wanted for years now.

**Comment by Tele42** [comment] 2015-04-11 21:44
Duplicate of #12.

**Comment by SamVanheer** [comment] 2019-05-05 11:36
As stated above this is a duplicate.

**Comment by kisak-valve** [comment] 2019-05-05 13:24
Closing in favor of #12.

**Closed by kisak-valve** 2019-05-05 13:24 UTC
