### ISSUE TITLE
[Counter-Strike: Condition Zero - Deleted Scenes] bugged fog in run level

### ISSUE THREAD

**Issue by Diegoparedeshd1** [ValveSoftware/halflife#3635] opened 2023-11-29 20:03 UTC
The fog is completely broken in the run level when activating the enable shaders option

![Captura de pantalla 2023-11-29 171115](https://github.com/ValveSoftware/halflife/assets/151307139/4292bebf-1698-4a88-979a-afeec71baf7a)

https://www.youtube.com/watch?v=uVZh1uvDo8s

**Comment by funcjay** [comment] 2023-11-29 21:59
The fog and a few other things are generally really weird with shaders enabled, very visible on CSCZDS's Thin Ice mission; the fog is just a straight line and the water looks really bad.

**Comment by Maharic** [comment] 2023-11-29 22:28
![20231129172058_1](https://github.com/ValveSoftware/halflife/assets/151443551/bc78fb10-c7bd-40e2-b124-3982bcd98714)
(^Both Fog and Shader enabled ^)

![20231129172101_1](https://github.com/ValveSoftware/halflife/assets/151443551/54511568-2175-49c7-9584-281cbf8b47a4)
(^Fog enabled without shader^)

![20231129172110_1](https://github.com/ValveSoftware/halflife/assets/151443551/b6fcb81e-9c11-4337-9b9c-216d02c5f234)
(^Fog disabled without shader ^)

Yes, the shader combined with fog is broken.  (shader being applied to fog layer?) 

Fog is in a lot of the CZ maps (if not all of them), but it's a very subtle ambient effect.  With the shader combination it breaks it and makes it unusable.

**Comment by SamVanheer** [comment] 2023-11-29 23:47
Fog is implemented using `glFog` which is part of the fixed function pipeline. Shaders (also known as the programmable pipeline) are a replacement for that so it's not surprising that it's not working correctly. Combining these two features has driver-specific behavior since it's not really meant to be used that way.

The same problem has happened before in other games, for example: https://github.com/HappyFunTimes01/ShaderOverride/blob/b965737c515e27ddf83b3171a7b202ecb499c823/README.md#fog-issue

Fog probably needs to be implemented using a shader when shaders are in use. Chances are this problem also happens when any other fixed function functionality is used so the entire renderer may need a shader-based replacement.

Underwater fog was fixed a few days ago so the same solution may work for this as well.

**Comment by IntriguingTiles** [comment] 2023-11-30 03:11
Seems to be fixed as of Half-Life Build ID 12833965 which released two hours ago with no changelog.

**Comment by Maharic** [comment] 2023-11-30 03:57
![20231129221508_1](https://github.com/ValveSoftware/halflife/assets/151443551/6beaea69-97db-4662-b798-541432ef66f3)

And yes, in the multiplayer component of Condition Zero, `gl_fog` appears to be working properly with shaders enabled.

**Comment by SamVanheer** [comment] 2023-11-30 11:10
Looks like fog was already using shaders when they're enabled so this was probably caused by something else.

**Comment by Diegoparedeshd1** [comment] 2023-11-30 22:05
it was fixed in the last update there was.

**Comment by kisak-valve** [comment] 2024-01-13 02:49
Closing per the last several comments.

**Closed by kisak-valve** 2024-01-13 02:49 UTC
Labels: Condition Zero: Deleted Scenes, Need Retest
