### ISSUE TITLE
fps_override "value" should be saved when changed.

### ISSUE THREAD

**Issue by basuritashka** [ValveSoftware/halflife#2237] opened 2019-04-24 02:13 UTC
As a 144hz user, it's frustrating to define fps_override 1 to get >100 FPS on each CS startup. (without using a .cfg)

**Comment by 2010kohtep** [comment] 2019-04-24 02:27
The fix is quite simple, just add the ```FCVAR_ARCHIVE``` flag to the ```fps_override``` variable. @mikela-valve, why not? :)

**Comment by mikela-valve** [comment] 2019-04-24 02:34
I was going to say the same thing. I’m fine making that and any other cvar’s FCVAR_ARCHIVE that make sense to be automatically persisted unless there are any reasons not to. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by basuritashka** [comment] 2019-04-24 02:40
I dont know if there are more useful cvars that are not being saved, but I would like to have "fps_override" as a permanent change if his value gets changed. My monitor would be very grateful :)

**Comment by FEDERICOMB96** [comment] 2019-04-24 03:14
cl_showfps should get saved too as its more simple than net_graph, also it just use a little space of your screen

**Comment by djdallmann** [comment] 2019-04-24 03:36
And perhaps **gl_ansio** and **cl_filterstuffcmd** :)

**Comment by basuritashka** [comment] 2019-04-24 04:11
If someone else knows more useful cvars that can be added into the `FCVAR_ARCHIVE` param. we can make a great list to @mikela-valve

**Comment by MOCOLONI** [comment] 2019-04-24 16:48
> If someone else knows more useful cvars that can be added into the `FCVAR_ARCHIVE` param. we can make a great list to @mikela-valve

spec_mode & spec_mode_internal seem not get saved even if values are specified in an autoexec file. For example, a value of '3' for both commands means you spectate the target through 'Free Chase Camera' mode. However, every time the game is restarted, the mode is set to 'Free Look'. Pressing Space will be switching between all modes except 'Free Chase Camera' for some reason, which is the one I want to be defaulted to. I can use Ctrl and manually selecting the mode, but it's something I have to do all the time and for some reason its value seems not to be saved in any way and works only when submitted while in a game.

**Comment by basuritashka** [comment] 2019-04-24 17:29
`graphheight ` needs to be `FCVAR_ARCHIVE` also.

**Comment by Sockman1** [comment] 2019-04-24 20:02
gl_texturemode should probably be saved as well.

**Comment by mikela-valve** [comment] 2019-04-25 00:13
It looks like the list so far is:
- [ ] fps_override
- [ ] cl_showfps
- [ ] gl_ansio
- [ ] cl_filterstuffcmd
- [ ] spec_mode
- [ ] spec_mode_internal
- [ ] graphheight
- [ ] gl_texturemode

I know gl_texturemode at least is actually a command and not a cvar so it can't be trivially saved but I'll see what I can do about that and the rest of these.

**Comment by PredatorFly** [comment] 2019-04-25 21:19
ex_interp plz

**Comment by basuritashka** [comment] 2019-04-26 00:40
If you don't mind, maybe we can add:
`developer`
`gl_wireframe`
`sv_cheats`
`cl_showerror`
`cl_showevents`
`cl_showmessage`
`cl_shownet`

**Comment by Sockman1** [comment] 2019-04-26 01:31
I think dev commands like gl_wireframe, sv_cheats, and developer should be kept unarchived so it's easier to restore everything. When I use something like gl_wireframe, for instance, I'm looking for a bug or error, and when I'm done I don't want to try to remember every option I changed and change it back. If you really need to keep these persistent, using launch options works just as well.

**Comment by tschumann** [comment] 2019-04-26 01:33
I agree - debug cvars should not be persisted.

**Comment by basuritashka** [comment] 2019-04-26 01:34
Removed 3 cvars thanks to @Sockman1 and @tschumann

**Comment by dager10** [comment] 2019-04-28 12:20
zoom_sensitivity_ratio should be saved too

**Comment by mikela-valve** [comment] 2019-05-14 23:08
I've added everything noted with the exception of spec_mode/spec_mode_internal as those are actually commands that have multiple parameters and aren't as conducive to being converted to cvars.

gl_texturemode was converted from a command to a cvar so it can be saved automatically through FCVAR_ARCHIVE.

**Comment by MOCOLONI** [comment] 2019-05-15 16:20
> I've added everything noted with the exception of spec_mode/spec_mode_internal as those are actually commands that have multiple parameters and aren't as conducive to being converted to cvars.
> 
> gl_texturemode was converted from a command to a cvar so it can be saved automatically through FCVAR_ARCHIVE.

Just like with "net_graph 0/1/2/3", I thought it would be possible and a good idea for the game to remember the camera mode that was last used.

**Comment by mikela-valve** [comment] 2019-05-15 17:49
@MOCOLONI Actually it looks like spec_mode_internal (and spec_pip) are already archived and are the default reset values for spec_mode. Does setting those to the values you'd use for spec_mode not get it to default to the right view?

**Comment by MOCOLONI** [comment] 2019-05-15 18:42
> @MOCOLONI Actually it looks like spec_mode_internal (and spec_pip) are already archived and are the default reset values for spec_mode. Does setting those to the values you'd use for spec_mode not get it to default to the right view?

Without config files like "autoexec.cfg" nor "userconfig.cfg" it doesn't seem to get saved. I then tried listing them into the "autoexec" one and, like before, it still won't work. However, it Does seem to read the value from the "userconfig.cfg" file.

**Comment by mikela-valve** [comment] 2019-05-15 18:52
@MOCOLONI Could you check your (presuming this is CS) cstrike\config.cfg after setting spec_mode_internal/spec_pip and see if they're written there? 

Archived cvar's are saved to config.cfg, and the order that the configs are loaded in is:
1. autoexec.cfg
1. config.cfg
1. userconfig.cfg
1. game.cfg

**Comment by MOCOLONI** [comment] 2019-05-15 19:15
@mikela-valve Yes, they are.

**Comment by mikela-valve** [comment] 2019-05-15 22:02
Does it just not matter what they're set to (i.e. they're set the same values as your last run but they don't set spec_mode correctly) or do they get set to default values (0 or 1) each time?

**Comment by MOCOLONI** [comment] 2019-05-15 23:59
@mikela-valve I recently joined the beta (though not for the first time) and ever since I found out, just now, that not even the userconfig.cfg file is necessary anymore; both the spec_mode and spec_pip commands get their last-used values stored in the "config.cfg" file. Before, at least for spec_mode, it would always reset to "1".

**Comment by hobokenn** [comment] 2019-05-17 14:09
If it's not too late default_fov, cl_bob and room_off would be nice to have archived.

**Comment by mikela-valve** [comment] 2019-05-17 16:52
I think those all sound fine, thanks!

**Comment by mikela-valve** [comment] 2019-05-21 19:16
Added in 'Exe build: 11:11:14 May 21 2019 (8244)'.

**Comment by MOCOLONI** [comment] 2019-05-21 20:29
@mikela-valve The latest update seems not to show the progress of a connection to the server; it instead leaves a blank (dark) background while loading everything.

**Comment by mikela-valve** [comment] 2019-05-21 20:31
Thanks @MOCOLONI, that was a regression in fixing #2124 that should be fixed later today.

**Comment by di57inct** [comment] 2019-05-21 20:31
@mikela-valve please do the same for cl_filterstuffcmd and rate cvars.

**Comment by mikela-valve** [comment] 2019-05-21 20:33
Sure, I can add `rate`. `cl_filterstuffcmd` is already an archived cvar.

**Comment by mikela-valve** [comment] 2019-05-23 00:32
`rate` has been added as of beta 'Exe build: 16:32:50 May 22 2019 (8245)'.

**Comment by basuritashka** [comment] 2019-05-23 00:40
@mikela-valve I am sure `rate` was already an archived cvar.

**Comment by mikela-valve** [comment] 2019-05-23 00:45
`rate` was not an archived cvar, though it may have been in the past. Were you possibly thinking of `cl_updaterate` which is already one?

**Comment by basuritashka** [comment] 2019-05-23 00:47
On Exe build: 15:58:59 Apr  3 2019 (8196) `rate` gets saved when closing Counter-Strike 1.6

**Comment by basuritashka** [comment] 2019-05-23 01:06
@mikela-valve btw, beta seems to be not working properly.

**Comment by mikela-valve** [comment] 2019-05-23 01:10
It looks like you're right, rate does get saved but not as a cvar, it's saved to hl.conf which gets applied as the rate in any HL-based game that you run. It looks like that value gets loaded after the config files do as well, so I may change it to not set the rate from that file if it has already been set from a user config.

**Comment by mikela-valve** [comment] 2019-05-23 01:10
What isn't working in the beta?

**Comment by basuritashka** [comment] 2019-05-23 01:12
I am on beta according to Steam but in-game I got this version:
Exe build: 15:58:59 Apr  3 2019 (8196)

![imagen](https://user-images.githubusercontent.com/33007491/58218765-34ab5500-7cd6-11e9-8bbe-183c03f5b264.png)

![imagen](https://user-images.githubusercontent.com/33007491/58218779-455bcb00-7cd6-11e9-951d-7fea0491c08f.png)

Note: I was switching between beta and normal CS to test some things. weird.

**Comment by mikela-valve** [comment] 2019-05-23 01:14
Oh, that may be due to CS being on beta but not HL1. They're supposed to switch together when you change between beta and public but sometimes that doesn't work. Try switching in and out of beta for HL.

**Comment by basuritashka** [comment] 2019-05-23 01:23
You are right, but if you got only Counter-Strike 1.6 on your Library, beta won't work at all unless you got HL bought too into your library, that should be intended right?

(I tested it on 2 different Steam accounts, HL plus CS 1.6, works flawlessly and CS 1.6 without HL, beta doesn't work)

**Comment by mikela-valve** [comment] 2019-05-23 01:27
Yep, that’s as expected. Any shared engine changes and other shared code will only be in the HL1 depots, so if you’re only opted in to beta in CS you would have beta versions for whichever CS-specific files are in beta but not any of the shared files.

**Comment by mikela-valve** [comment] 2019-06-02 08:39
Closing as fixed.

**Closed** 2019-06-02 08:43 UTC

**Comment by h0lzed** [comment] 2019-07-17 06:14
@mikela-valve 
If it's not too late r_decals, max_shells, max_smokepuffs, cl_smoothtime would be nice to have archived.

**Comment by mikela-valve** [comment] 2019-07-19 17:13
Added `r_decals`, `max_shells`, `max_smokepuffs`, `cl_smoothtime` from https://github.com/ValveSoftware/halflife/issues/2595#issuecomment-513157949

**Comment by h0lzed** [comment] 2019-07-20 06:21
@mikela-valve r_decals still not archived.

**Comment by basuritashka** [comment] 2019-07-20 06:23
> 
> 
> @mikela-valve r_decals still not archived.

Can confirm, r_decals is not `FCVAR_ARCHIVE`.

**Comment by h0lzed** [comment] 2019-07-20 09:30
Probably it works, but just a little bit strange.
In menu it shows r_decals 4096, but after connecting to a server it shows 0.

**Comment by SamVanheer** [comment] 2019-07-20 09:34
Indeed it isn't archived, however if you join a multiplayer game and `r_decals` is greater than `mp_decals` it forces the value of `r_decals` to that of `mp_decals`. `mp_decals` defaults to 300, and it's also marked as archived.

**Comment by mikela-valve** [comment] 2019-07-23 05:05
@SamVanheer Thanks, I checked that out after reading your comment and changed the way `r_decals` was handled a bit. Rather than making `r_decals` an archived cvar, since that wouldn't have worked well with `mp_decals` resetting it, I introduced a single-player analog to it, `sp_decals` that is used when starting a single-player server.

I also removed the check for setting `r_decals` only if `mp_decals` or `sp_decals` is smaller, instead `r_decals` is always set to the current value of `mp_decals` or sp_decals` on server init, and both `mp_decals` and `sp_decals` are archived.

**Comment by basuritashka** [comment] 2019-07-24 02:27
@mikela-valve The change to *_decals seems to be working great.

If possible to make the following commands as `FCVAR_ARCHIVE`
`con_shifttoggleconsole`
`con_notifytime`

**Comment by basuritashka** [comment] 2019-07-27 18:07
Part 2 - commands that should be saved.

`motdfile`

**Comment by h0lzed** [comment] 2019-07-29 09:23
r_mmx should be archieved.
