### ISSUE TITLE
Major normal download issues

### ISSUE THREAD

**Issue by Freeman-AM** [ValveSoftware/halflife#1425] opened 2013-11-26 08:44 UTC
Here, i will talk about normal download issues : the case were files are not on a fast download url, or the other case were there is no fast download at all.

We are just talking about download from the server, fast download work well for this issue and can "workaround" it.

This issue touch some specific files at least thoses 2 :
wad files (precached from .res)
css files

Recently, i discovered that .css files precached from plugins are touched too when i installed warcraft 3ft mod. (popular mod) http://wc3mods.net/forums/viewtopic.php?f=2&t=3498
wc3.css is needed for motd style and so on.

what the issue does ?
Freeze the game (need a manual shutdown) at download end of the file.
Create a blank folder of the name of the downloaded file in cstrike_downloads (client corruption for this file, ex: if it's a wad, client will never be able to go on that map in any server because of this bugged folder).

Also .css files loose functionnality if not in cstrike folder. (mean they don't work in cstrike_download) when they worked before with 2009 build.
So warcraft motd is now permanently broken.

Please, fix this.

**Comment by kriswema** [comment] 2016-01-02 01:32
Having the same issue with .wad files in Team Fortress Classic. The game crashes after completing a .wad download. If I start the game again and try to connect, the game will again crash due to a file read error.

**Comment by Freeman-AM** [comment] 2018-02-13 12:02
@WPMGPRoSToTeMa Is it patched in rehlds/regamedll ?

**Comment by rtxa** [comment] 2018-05-07 04:31
Hello, this issue is happening to in the latest build of Half-Life. The file is proxboctwadpak.wad
BUILD 7561 SERVER
![imagen](https://user-images.githubusercontent.com/25672911/39685026-3460b336-5196-11e8-8184-34aca2f19880.png)

**Comment by WPMGPRoSToTeMa** [comment] 2018-05-07 14:01
@rtxa this is client-side problem, but it only appears if the server doesn't use FastDL.

**Comment by rtxa** [comment] 2018-05-07 16:05
@WPMGPRoSToTeMa yes, I was having problems with the fastdl yesterday, today I upload it and it works, however the problem is when fastdl is not used...

**Comment by SamVanheer** [comment] 2019-05-04 15:04
@kisak-valve This issue has been fixed, the code in the engine now works like @WPMGPRoSToTeMa suggested.

I don't know which update fixed this though. Ideally somebody should search through the internal commit log to match this up since i can't find the change listed in any update news.

This issue was a duplicate of #160 and #1026, and #1526 and #2015 are known duplicates as well.

Unless somebody still experiences issues downloading WAD files all of these issues should be closed.

#1551 refers to this issue but may also cover another problem that needs to be tested again.

It's possible that the crash referred to there and the freeze referred to by this issue are the same thing, caused by code trying to open a directory as a file and then either freezing or crashing when a read operation is performed on it. In that case the issue should be fixed.

**Comment by kisak-valve** [comment] 2019-06-07 13:10
Closing per the last comment.

**Closed by kisak-valve** 2019-06-07 13:10 UTC
Labels: Counter-Strike, Need Retest
