### ISSUE TITLE
[HL25] "gl_keeptjunctions 0" causes Assertion failed on restart, map change or quit, referencing hw.dll

### ISSUE THREAD

**Issue by N7P0L3ON** [ValveSoftware/halflife#3835] opened 2024-10-02 17:03 UTC
Half-Life multiplayer mods built on the latest Half-Life SDK will crash with 

```
Assertion failed!
Program:...iles (x86)\Steam\steamapps\common\Half-Life\hw.dll
File c:\buildslave\goldsrc_win32\build\GoldSrc\...\GL_RSURF.C
Line: 2575

Expression: surface->polys->polys->numverts == surface->numedges

For information on how your program can cause assertion failures, see the Visual C++ documentation on asserts

(Press Retry to debug the application - JIT must be enabled)

```
![image](https://github.com/user-attachments/assets/eb826116-3191-4089-ac35-f0eee26a1d9b)

This error is observed on map change (restart or after time ends or max frags are reached) or when quit command is send.

This error has something to do with the latest engine update from 12th September.

```
Protocol version 48
Exe version 1.1.2.2/Stdio (valve)
Exe build: 20:26:26 Sep 12 2024 (10185)
```

This error is **NOT** present when starting the mod under `steam_legacy - Pre-25th Anniversary Build`

Please provide more information on what was changed in the latest engine build, or provide a backwards compatibility with the SDK.

Thanks in advance.

**Comment by ScriptedSnark** [comment] 2024-10-02 18:20
It's not related to SDK. New engine build (Windows, build 10185) has some new asserts in `GL_BuildLightmaps` like `surface->polys->next == NULL`, `surface->polys->flags == surface->flags`, `surface->polys->numverts == surface->numedges`. Seems like it doesn't like some maps or lightmap changes including vanilla ones.

**Comment by N7P0L3ON** [comment] 2024-10-02 19:43
That's all cool... but the maps I'm crashing on are Vanilla Half-Life maps like crossfire, undertow, stalkyard... and this included all the new maps added with the 25th update...  all of the maps are copied from the valve/maps directory...

So we definitely need a fix...
I also tested it if the maps are loaded from /valve/maps/ directory instead of the /mod/maps/ directory and the result is the same... crash...

The thing is it does not crash on Half-Life/Opposing Force or TFC/DMC... so it's something the base games take into account... but  it's not taken into account for the mods... Thus I was incline to think it's something to the SDK...

**Comment by 0Ky** [comment] 2024-10-02 20:01
@N7P0L3ON I've updated to the latest version on the client `20:26:26 Sep 12 2024 (10185)` and created a mod using this SDK, which compiles `hl.dll` and `client.dll`. I'm not able to reproduce the issue you're having. Can you please clarify and provide steps to reproduce the issue?

**Comment by N7P0L3ON** [comment] 2024-10-02 21:02
You can do it in multiple ways:
1. Start the game on crossfire (or any other map in that matter), issue a restart command -> will result in the Assert error
2. Start the game on crossfire, wait for the map to change after the timelimit passes -> will result in the Assert error on changelevel
3. Start the game on crossfire, issue the quit command -> will result on the Assert error

**Comment by N7P0L3ON** [comment] 2024-10-02 21:09
https://github.com/user-attachments/assets/187422f6-fd52-4f82-9302-4e15d3b275cb

@0Ky Here's a video reproduction of 3 of the possible ways to get the Assert error
You can also get the assert error on map change via timeleft or fragleft.
Also it does not matter what map you use for this. It will crash no matter the map used.

**Comment by N7P0L3ON** [comment] 2024-10-02 21:29
Also just like @MaZDuR in #3837 I got the crash in TFC as well...

**Comment by sabianroberts** [comment] 2024-10-02 21:40
Are you referring mods using DLLs built from the SDK on this GitHub page or just any multiplayer mods in general? I've tested multiplayer mods and TFC on my end and they work.

**Comment by 0Ky** [comment] 2024-10-02 21:48
@N7P0L3ON I've followed the exact same instructions and it is not crashing on my end, maybe try updating to the latest commit:
```
commit 2c78e5d9948f19812ff59df275e1f58183364d38 (HEAD -> master, origin/master, origin/HEAD)
Author: shawns-valve <shawns@valvesoftware.com>
Date:   Wed Oct 2 14:22:18 2024 -0700
```

**Comment by N7P0L3ON** [comment] 2024-10-02 21:55
Same crash on TFC -> 
![image](https://github.com/user-attachments/assets/e51be351-4346-424f-aa36-5d6b77f67951)
Again on restart.
Obviously something changed in the engine...

**Comment by sabianroberts** [comment] 2024-10-02 21:58
> Replying to https://github.com/ValveSoftware/halflife/issues/3835#issuecomment-2389759856

Just tested TFC and no issue on my end. ¯\_(ツ)_/¯

**Comment by shawns-valve** [comment] 2024-10-02 22:02
I'm not totally clear on the scenario here: 

- Are you seeing this with just the unmodified Steam build of HL/TFC? If so, I would just try doing "Verify integrity of game files" and/or a full uninstall / reinstall. Especially if you've switched Beta branches, e.g. between steam_legacy and 25th anniversary, things often seem to get messed up.

- Is the Steam build fine, but you hit this if you rebuild the HL DLLs from the SDK?

- Or is it only happening with DLLs you've modified?

**Comment by MaZDuR** [comment] 2024-10-02 22:03
> > Replying to [#3835 (comment)](https://github.com/ValveSoftware/halflife/issues/3835#issuecomment-2389759856)
> 
> Just tested TFC and no issue on my end. ¯_(ツ)_/¯

Are you using the steam_legacy branch for half life? as this is an engine mod, it will use what you selected for betas under half life.

Simply start the game.. then either join any server or create your own, it will crash as soon as it begins loading you in.

```
] version
Protocol version 48
Exe version 1.1.2.2/Stdio (tfc)
Exe build: 20:26:26 Sep 12 2024 (10185)
] map 2fort
```

**Comment by sabianroberts** [comment] 2024-10-02 22:11
@MaZDuR I'm on the latest update -- Half-Life and TFC both got updated on Steam recently; TFC updated with rebuilt DLLs, I'm assuming ones based on code consistent with the HL25 SDK. I freshly installed TFC half an hour ago to try this.

**Comment by MaZDuR** [comment] 2024-10-02 22:13
> I'm not totally clear on the scenario here:
> 
>     * Are you seeing this with just the unmodified Steam build of HL/TFC? If so, I would just try doing "Verify integrity of game files" and/or a full uninstall / reinstall. Especially if you've switched Beta branches, e.g. between steam_legacy and 25th anniversary, things often seem to get messed up.
> 
>     * Is the Steam build fine, but you hit this if you rebuild the HL DLLs from the SDK?
> 
>     * Or is it only happening with DLLs you've modified?

I am fairly certain @N7P0L3ON noticed this problem in their own custom mod and reported it; I encountered a bug after seeing an HL update and wanting to see if the HUD menu spacing was finally fixed.. I reported the bug as it is game breaking and prevents anyone from the latest build from playing TFC 'with default settings'
I have since verified.. it persisted.. so I fully deleted half-life and all its mods and only installed TFC.. the issue still persist..

EDIT: there indeed is a file in the Half-Life folder that is both modified but not replaced on updates, I had to manually delete the base files to download a fresh  copy.

**Comment by shawns-valve** [comment] 2024-10-02 22:24
> EDIT: there indeed is a file in the Half-Life folder that is both modified but not replaced on updates, I had to manually delete the base files to download a fresh copy.

Do you know what the file was that didn't get overwritten?

Is the issue fixed after a clean install, or still happening for you?

**Comment by N7P0L3ON** [comment] 2024-10-02 22:24
I have indeed first encountered the bug today in my mod. 
I just did what you requested me to do, I actually removed the whole Half-Life folder and redownloaded Half-Life and TFC. 
I started TFC and got the assert crash.

Then I put my mod folder again. I re-tested it and I have the same crash in my **mod** as well (this was not a surprise I guess).

The only modified files are inside my mod's folder, so nothing is actually modified from the engine files, the yare the stock onese you get when you install the game.

I'm on the newest version of the game, and in this new installation I have **NOT** changed to legacy.

Furthermore, to exclude the possibility of my machine doing the problem, I pushed Steam + Half-Life and TFC on my lab environment and... I have exactly the same crash on the lab instance.

**Comment by shawns-valve** [comment] 2024-10-02 22:39
@N7P0L3ON, do you hit the same issue in Half-Life with stock DLLs? Or only TFC?

I'm attempting to repro this internally, but I haven't been able to hit it yet. If it's occurring consistently for some people but not others, I suppose this could be related to saved user settings / convars / something like that, though I don't yet have a specific theory.

**Comment by N7P0L3ON** [comment] 2024-10-02 22:50
I am hitting this is TFC and in my mod. I don't have it in regular Half-Life. Thus my initial assumption that's something that's added to the engine and in Half-Life, but not in the regular SDK...

I doubt it's possible to be a settings/convars as I use the stock TFC settings and files (I reinstalled TFC as part of HL1 reinstall...).
The setting used for my mod are also the default HL1 files, pulled out of valve folder... I have added additional cvars for modifying the damage and other values, but those do not modify anything on the engine (last time I checked we have no access to the engine... so that's out of the question).

**Comment by N7P0L3ON** [comment] 2024-10-02 23:00
Another thing to note out is that this crash did **NOT** happened in the 25th build before September 12th... And I have not made changes in my mod after September 12th anyway... It has to be the engine update...

**Comment by MaZDuR** [comment] 2024-10-02 23:38
I am unsure what part of my config is causing this issue, but I have attached some of the settings below, if required I can attach my entire userconfig.cfg that can cause this issue.

```
// ----- Video -----

vid_d3d			"0"
gl_flipmatrix		"0"
r_dynamic 		"0"
r_traceglow 		"0"
r_mirroralpha 		"0"
r_shadows 		"0"

//  -------- Textures --------

gl_texturemode	"GL_LINEAR_MIPMAP_LINEAR"				//  Lowest quality of textures (Highest is GL_LINEAR_MIPMAP_LINEAR) lowest is GL_NEAREST
gl_smoothmodels "1"					//  Smooth models
gl_max_size 	"128"					//  Size of Textures, multiples of 16
gl_round_down	"4"
```

**Comment by shawns-valve** [comment] 2024-10-03 00:19
Yeah, it may not be related to config at all, but go ahead and attach the whole thing if you don't mind.

**Comment by MaZDuR** [comment] 2024-10-03 00:38
[config.txt](https://github.com/user-attachments/files/17237703/config.txt)
I had renamed config.cfg ->config.txt and uploaded it, one of the settings in this config causes a 'vanilla installed copy of TFC' to crash with the error message first mentioned when attempting to load into a map

for some reason if I leave this file deleted but then allow my class configs to change the settings, I can continue playing, but then I see the issue next occur _AFTER_ a mapchange occurs, BUT not until I attempt to spawn in.

![error](https://i.imgur.com/UvonRgV.jpeg)

**Comment by shawns-valve** [comment] 2024-10-03 00:57
Aha. It looks like this is triggered by "gl_keeptjunctions 0". Try disabling that and see if it resolves the issue for you.

We'll try to get a patch in as soon as possible -- the assert here is actually just incorrect in the gl_keeptjunctions 0 case.

**Comment by MaZDuR** [comment] 2024-10-03 01:11
> Aha. It looks like this is triggered by "gl_keeptjunctions 0". Try disabling that and see if it resolves the issue for you.
> 
> We'll try to get a patch in as soon as possible -- the assert here is actually just incorrect in the gl_keeptjunctions 0 case.

Yes, this appears to solve my issue.

**Comment by N7P0L3ON** [comment] 2024-10-03 09:05
OK... Question... I had `gl_keeptjunctions 1` and it crash on map change... Now if I set `gl_keeptjunctions 0` it crashed on map start...
![image](https://github.com/user-attachments/assets/2b133637-0faa-4ca0-bf79-4512ce29845a)

What is the correct one?
What does this command do anyway? Can it be removed/disabled?

**Comment by SamVanheer** [comment] 2024-10-03 13:18
> What is the correct one? What does this command do anyway? Can it be removed/disabled?

https://github.com/id-Software/Quake/blob/bf4ac424ce754894ac8f1dae6a3981954bc9852d/QW/docs/glqwcl-readme.txt#L116-L119

Also note that asserts are not crashes. An assert is a warning that a condition that is expected to be true is false, meaning the program's state may be invalid resulting in incorrect behavior, freezes or crashes. You can click ignore to continue the game but it will probably keep hitting the assert making it impossible to continue playing.

This condition checks if the number of vertices in the polygon matches the number of edges (connections between vertices). It should match, unless `gl_keeptjunctions 0` is removing vertices without updating the edge count to match.

If it's still hitting the assert either way then something else is going on, possibly the vertex and/or edge count is being calculated incorrectly.

**Comment by N7P0L3ON** [comment] 2024-10-03 13:23
Sure thing, but then the question is what is calculating it incorrectly... as it was working before that engine update. I should say: before the latest update to the 25th engine... as with the previous version of the 25th engine it was working with no issues...
Additionally the "Ignore" option is not an option since after 2 or 3 ignores it will crash to desktop anyway...

**Comment by SamVanheer** [comment] 2024-10-03 13:39
> Sure thing, but then the question is what is calculating it incorrectly... as it was working before that engine update. I should say: before the latest update to the 25th engine... as with the previous version of the 25th engine it was working with no issues... Additionally the "Ignore" option is not an option since after 2 or 3 ignores it will crash to desktop anyway...

I don't think the assert existed before this update. We'll hear more when it's been investigated.

**Comment by ScriptedSnark** [comment] 2024-10-03 16:03
> It's not related to SDK. New engine build (Windows, build 10185) has some new asserts in `GL_BuildLightmaps` like `surface->polys->next == NULL`, `surface->polys->flags == surface->flags`, `surface->polys->numverts == surface->numedges`. Seems like it doesn't like some maps or lightmap changes including vanilla ones.

As I said, those asserts exist in newer engine builds. `gl_keeptjunctions` can be a solution for some maps but this problem can't be fixed with this at all. Why was those surface asserts implemented, though? Older engine versions didn't have any issues with mismatches. Removing those asserts fix the crash without any side effect. At least, I patched them with NOPs and nothing bad happened when viewing maps. Maybe it's better to enable assertions when developer mode is active so there won't be any kind of those crashes for regular player?

**Comment by N7P0L3ON** [comment] 2024-10-03 17:13
> Replying to https://github.com/ValveSoftware/halflife/issues/3835#issuecomment-2391789769

Can you elaborate more on how you disabled them? Maybe you have a repo somewhere you can show?

**Comment by ScriptedSnark** [comment] 2024-10-03 17:19
> Can you elaborate more on how you disabled them? Maybe you have a repo somewhere you can show?

Basic HEX patching. You can also hook wassert to disable specific errors. I wouldn't recommend to do these things. Not safe, risky. It's better to be fixed officially. That's just my personal workaround for that issue. You can also downgrade engines to build 9920 as a temporary solution.

**Comment by shawns-valve** [comment] 2024-10-03 18:52
It's fine to disable the assert if you have that ability; the assert is just incorrect.

If you're interested, the history of this change:
- Pre-25th anniversary, whenever you changed your brightness setting, we restarted the entire engine (unloaded and reloaded the engine DLL). 
- The 25th anniversary update changed this to just rebuild lightmaps instead of restarting the engine. But during the lightmap build, the vertex data for every surface would get reallocated, and due to how the Quake hunk allocator works, the old vertex data didn't get freed until you changed levels. This effectively introduced a memory leak where you could crash the game if you changed brightness enough times in a row.
- The October 2 update avoids reallocating the vertex data if it already exists. The asserts here are just intended to verify that the vertex data still matches the surface it's paired with (e.g. same flags and vertex count). But gl_keeptjunctions 0 means the vertex count may not match, which is okay in this case -- we just failed to test this because all of the Valve mods use gl_keeptjunctions 1.

**Comment by N7P0L3ON** [comment] 2024-10-03 23:15
That's good to know.... however my mod crashes even with `gl_keeptjunctions 1`... I hope there will be a fix for this...
Or maybe another cvar to reintroduce the 25th anniversary update version of the behavior...

**Comment by shawns-valve** [comment] 2024-10-03 23:35
What's the scenario where it crashes with gl_keeptjunctions 1? That sounds like a different issue -- is it hitting the same assert?

**Comment by N7P0L3ON** [comment] 2024-10-04 08:26
It crash with exactly the same assert on the same line.

**Comment by SamVanheer** [comment] 2024-10-04 08:51
It would help to know which mod it is, which map and the sequence of events that lead up to the crash. Provide a download link if possible.

**Comment by N7P0L3ON** [comment] 2024-10-04 09:50
I can provide download for my mod that experience the issue (it's still not released...), however I cannot opensource my repo to the public as it contain a lot of custom code for new weapons, game modes, etc and more...

On another note, I just did a plain fork of the HL SDK, compiled it with VS 2019 and in one out of 6-7 restarts I still get the assert crash/issue on crossfire...

**Comment by N7P0L3ON** [comment] 2024-10-04 11:44
Hello @shawns-valve , we have this one figured out... thanks to @bacontsu and @BlueNightHawk 

The problem is we have code that's used to create/draw shader water and shader skybox... What it does is it set numverts to a negative value so that the brushes for water and the skybox aren't drawn... and instead of that we have the shaders... something like Half-Life 2... but in Half-Life 1 engine...

And the problem is that the engine update just broke that one via the checks you introduced... Any chance you might have it only to check for the Valve official games, and if it's not official folder ( valve, cstrike, tfc, gearbox, czero, dmc and rocochet) not to perform those checks?

This will save a lot of mods from crashing due to custom renderer functions implemented... Not doing this will simply limit the mod makers... Adding the additional check will make sure those are not altered in official games clients (if they are considered hacks), while preserving the mod makers creativity.

Thanks.

**Comment by ScriptedSnark** [comment] 2024-10-04 12:51
I can confirm that `gl_keeptjunctions 0` or custom renderer in client DLL (tested with [Trinity Engine](https://github.com/TheOverfloater/trinity-engine)) can trigger `surface->polys->polys->numverts == surface->numedges` assertion.

**Comment by N7P0L3ON** [comment] 2024-10-04 13:15
On mods using custom or modified renderers `gl_keeptjunctions 0` and `gl_keeptjunctions 1` will both give the same assert on exact same line... just if it's value `0` it will be triggered on trying to start the map/joining server, and if it's value `1` it will be triggered on restart, map change or quit.

**Comment by shawns-valve** [comment] 2024-10-10 00:57
Today's patch disables this assert, which fixes the gl_keeptjunctions 0 case. I haven't tried one of these third-party renderers yet, so I'm not sure if there are still issues there, but hopefully things just work now.

**Comment by N7P0L3ON** [comment] 2024-10-10 06:58
Hello @kisak-valve I just tested the new patch, and yes, It appears the problem is no longer present. I can confirm that for Flatline Arena (my mod, where I use custom renderer).

Maybe @ScriptedSnark can check that one from his side on Trinity?

**Comment by ScriptedSnark** [comment] 2024-10-10 07:04
> Hello @kisak-valve I just tested the new patch, and yes, It appears the problem is no longer present. I can confirm that for Flatline Arena (my mod, where I use custom renderer).
> 
> Maybe @ScriptedSnark can check that one from his side on Trinity?

Yes, seems like everything is ok from my side with new engine update.

**Comment by shawns-valve** [comment] 2024-10-10 18:10
Closing until/unless something else comes up

**Closed as completed by shawns-valve** 2024-10-10 18:10 UTC
Labels: Team Fortress Classic, SDK
