### ISSUE TITLE
 [Counter-Strike: Condition Zero: Deleted Scenes] Skybox Is Broken

### ISSUE THREAD

**Issue by DudeWithTheFood** [ValveSoftware/halflife#3729] opened 2023-12-23 23:41 UTC
For some reason, every time i play a mission that isn't sandstorm, the skybox has this weird effect, i can't fix it. I've tried verifying the files, but nothing works. is there any fix to this?
![BrokenSkybox](https://github.com/ValveSoftware/halflife/assets/103080644/65660bec-1a32-491b-ad1a-0c65d366b3c7)
Here's an example

**Comment by Diegoparedeshd1** [comment] 2023-12-25 00:35
How strange, I just tried it on my computer and the problem did not happen.

**Comment by SmileyAG** [comment] 2023-12-25 09:08
Can you type `gl_dump` in the console and see if `GL_ARB_multitexture` or `GL_SGIS_multitexture` extension in the list?

If both of them is not in list, then it means that the engine enabled texture sorting, in which case this relates directly to #3389 issue, and therefore that can be closed as a sort of duplicate

**Comment by DudeWithTheFood** [comment] 2023-12-26 07:12
yeah, the GL_ARB_multitexture didn't show up, but how do i disable texture sorting. i tried searching, i can't figure out how to fix it.
i just want to play condition zero man

**Comment by kisak-valve** [comment] 2023-12-26 13:33
Closing as a duplicate of #3389.

Please use the older issue report for continued discussion of this issue.

**Closed by kisak-valve** 2023-12-26 13:33 UTC
Labels: Condition Zero: Deleted Scenes
