### ISSUE TITLE
Texturemode

### ISSUE THREAD

**Issue by tequierohabibi** [ValveSoftware/halflife#2735] opened 2019-10-12 16:02 UTC
Before the last update when we check the box  "low video quality" the command gl_texturemode it changes from GL_LINEAR_MIPMAP_LINEAR in GL_LINEAR_MIPMAP_NEAREST. Now when i check the box, GL_LINEAR_MIPMAP_LINEAR  it stays the same and I have to change that from console. 
I checked this after a clean install of the game and the problem persists.

**Comment by Sockman1** [comment] 2019-10-12 21:57
This is likely because gl_texturemode was made into an archived variable. I think it had to be made into a cvar because of that change and that probably lead to this issue.

**Comment by mikela-valve** [comment] 2019-10-21 20:41
Hi @tequierohabibi, this should be fixed in the latest beta. It should now set `gl_texturemode` to `GL_LINEAR_MIPMAP_NEAREST` and `gl_ansio` to `4` when in low video quality mode and set them back to `GL_LINEAR_MIPMAP_LINEAR` and `16` when low quality mode is disabled.

**Comment by Sockman1** [comment] 2019-10-24 19:54
I can confirm that everyone works as expected. gl_texturemode still saves and is set properly by the quality setting along with gl_ansio.

**Comment by mikela-valve** [comment] 2019-10-25 18:11
Thanks @Sockman1, closing as fixed.

**Closed by mikela-valve** 2019-10-25 18:11 UTC
