### ISSUE TITLE
[Half-Life] Z-fighting in c2a5w/c2a5c

### ISSUE THREAD

**Issue by floppyD** [ValveSoftware/halflife#2829] opened 2019-12-16 22:16 UTC
Pic related. The sign flickers in OpenGL and doesn't appear at all in Software.
c2a5w:
![opengl](https://user-images.githubusercontent.com/29208110/70947339-b0386f00-2037-11ea-90df-8d5e51ac73a8.png)
![software](https://user-images.githubusercontent.com/29208110/70947353-b6c6e680-2037-11ea-9ce9-5fb31c4ba2d6.png)

c2a5c:
![hl_2019_12_16_23_44_42_365](https://user-images.githubusercontent.com/29208110/70960725-96f6e900-205e-11ea-97fd-648c96a26c2b.png)

Game version:
Protocol version 48
Exe version 1.1.2.2/Stdio (valve)
Exe build: 15:17:55 Jul 24 2019 (8308)

**Comment by BlackShadow** [comment] 2019-12-17 17:45
It's a renderer issue not map. Renderer has some problems rendering infodecal entity.

**Comment by oaus** [comment] 2019-12-17 19:26
@kisak-valve this issue is a duplicate of: https://github.com/ValveSoftware/halflife/issues/693

**Comment by kisak-valve** [comment] 2019-12-17 20:26
Thanks @oaus, closing in favor of the older issue report.

**Comment by CS-PRO1** [comment] 2019-12-22 19:05
@kisak-valve I guess you missclicked. It's not closed :]

**Closed** 2019-12-22 19:13 UTC
Labels: Half-Life
