### ISSUE TITLE
The language problem continues even after the last update yesterday

### ISSUE THREAD

**Issue by Diegoparedeshd1** [ValveSoftware/halflife#3846] opened 2024-10-03 22:22 UTC
![284009819-265df2f1-43d5-43a5-8e26-54d7f448dfbf (1)](https://github.com/user-attachments/assets/8beafab7-95ae-42e6-93c9-5c411df148c0)

This issue is present if you run the game in any language other than English and affects ALL Goldsource based games.

And there is also the problem in the demo uplink where you can't hear the npc voices and the titles are incorrect if you run the game in any language other than english

**Comment by kisak-valve** [comment] 2024-10-03 23:33
Hello @Diegoparedeshd1, please do not intentionally open duplicate issue reports.

Closing as a duplicate of #3465.

**Closed as not planned by kisak-valve** 2024-10-03 23:33 UTC
