### ISSUE TITLE
[DoD goldsrc] Linux server = broken

### ISSUE THREAD

**Issue by bulletlottery** [ValveSoftware/halflife#3788] opened 2024-06-17 18:25 UTC
The wall penetration system does not work properly on 1000fps Linux servers resulting in the DoD community having to use 500 fps windows servers which deliver very subpar performance when it comes to bullet registration!

check it this video ( first one is linux and second test is windows 500fps ) 
https://youtu.be/LrLG5ONG3hw

need a fix asap valve!

**Comment by kisak-valve** [comment] 2024-06-17 18:59
Hello @bulletlottery, again, please do not intentionally open duplicate issue reports.

Closing as a duplicate of #3294.

**Closed by kisak-valve** 2024-06-17 18:59 UTC
