### ISSUE TITLE
[HL25] gamestartup.mp3 starts to play during the startup video

### ISSUE THREAD

**Issue by gryfhorn** [ValveSoftware/halflife#3508] opened 2023-11-20 03:31 UTC
If there is a gamestartup.mp3 file in the media folder and there is also startup video(s), the gamestartup mp3 will start to play during the startup videos.

**Comment by JoelTroch** [comment] 2023-11-20 14:29
Duplicate of #3438

**Comment by kisak-valve** [comment] 2023-11-20 14:50
Closing as a duplicate.

**Closed by kisak-valve** 2023-11-20 14:50 UTC
