### ISSUE TITLE
Curve crosshair

### ISSUE THREAD

**Issue by dproto** [ValveSoftware/halflife#1191] opened 2013-06-01 07:13 UTC
hi guys, noticed a problem with the crosshairs.
top of the crosshair is crooked, and moves out of sync with the rest.

**Comment by SamVanheer** [comment] 2019-05-05 10:19
#1202 seems to be the same issue, and is already on track to be fixed. I think this one can be closed.

**Comment by mikela-valve** [comment] 2019-05-15 17:55
Closing as duplicate of #1202.

**Closed by mikela-valve** 2019-05-15 17:55 UTC
Labels: Counter-Strike
