### ISSUE TITLE
NON-URGENT request/suggestion

### ISSUE THREAD

**Issue by 12souza** [ValveSoftware/halflife#3844] opened 2024-10-03 18:07 UTC
Thank you for all of your latest work on keeping tfc up to date and fixing some of the finer details of the game.  This isnt exactly an issue but more of a suggestion/request if it is at all possible to get a speedcap server side variable.  I understand this may introduce some work on the client as well, but it would revive a lot of community events that TFC had in the past.  

Right now the speedcap is set at 170 and it hard resets your speed to 100%... I am hoping we can get a sv_speedcap 170 for which that can be adjusted to whatever a server would like the same way gravity, air-acceleration and all that is done.

As of now, it is technically possible to remove the cap with community sided work.  There is a plugin that removes the speed cap from the server side so players can exceed the cap but get a bit of a rubberbanding effect as the server tells the client it should be in a certain spot due to the lack of a speed cap that the client was anticipating would exist and it then plays catch up.  This can be fixed with a client-side hack, which is obviously ill-advised.

Therefore, hoping we can make a variable speedcap native within the game? :)

**Comment by SamVanheer** [comment] 2024-10-03 18:43
Isn't this request functionally identical to #11? This refers to the anti-bunnyhopping speed cap in the player movement code.

**Comment by 12souza** [comment] 2024-10-03 19:05
You are correct.. did not see that.. apologies

**Comment by kisak-valve** [comment] 2024-10-03 19:51
Closing as a duplicate of #11.

**Closed as not planned by kisak-valve** 2024-10-03 19:51 UTC
