### ISSUE TITLE
[DoD goldsrc] broken scopes

### ISSUE THREAD

**Issue by bulletlottery** [ValveSoftware/halflife#3786] opened 2024-06-17 17:54 UTC
The scopes sprites on the sniper/fg42 are broken when the new widescreen fov is enabled 

Need a fix asap !!!

**Comment by kisak-valve** [comment] 2024-06-17 18:43
Hello @bulletlottery, please do not intentionally open duplicate issue reports. Closing as a duplicate of #3583.

**Closed by kisak-valve** 2024-06-17 18:43 UTC
