### ISSUE TITLE
[GoldSrc] (8254 Build) "restart" command doesn't work in single player

### ISSUE THREAD

**Issue by BlackShadow306** [ValveSoftware/halflife#2496] opened 2019-06-02 15:11 UTC
Latest Beta build  (8254) broke restart command in single player mode. Instead of restarting the level it's just kicks you to the main menu.

**Comment by agrastiOs** [comment] 2019-06-02 20:35
Works for me.

**Comment by eat1k** [comment] 2019-06-02 20:40
```
Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
Exe build: 17:59:58 May 31 2019 (8254)
```

It works fine for me, too.

**Comment by BlackShadow306** [comment] 2019-06-02 21:03
@agrastiOs did you tried this on latest beta build? and Half-Life singleplayer

@eat1k this issue occurs in single player.

**Comment by BlackShadow306** [comment] 2019-06-02 21:04
@mikela-valve can you kindly confirm on your side as well?


You can reproduce this issue by creating a single player in Half-Life and type restart to the console

**Comment by eat1k** [comment] 2019-06-02 21:30
> @eat1k this issue occurs in single player.

Yes, I understood it. I tested it in the latest beta in single player. I have no issues.

**Comment by voed** [comment] 2019-06-02 21:38
I confirm. Its because of loopback i guess
![image](https://user-images.githubusercontent.com/10352360/58767688-df095f00-8597-11e9-8f52-e74016456b1c.png)

**Comment by mikela-valve** [comment] 2019-06-03 00:00
I can confirm that this is happening. It's due to #2138. Basically `new` is executed in many different ways and is triggered both by the client and by the engine in different cases, so in this case things are working fine in multiplayer but not in singleplayer. I'll make an update to HL1 shortly that fixes this. It won't be a new version you can see with the `version` command as it won't cause a client recompile but I'll update this thread with the build ID that you can see in the 'Local Files' section of the game info in Steam.

**Comment by mikela-valve** [comment] 2019-06-03 18:44
This should be fixed now in HL1 beta BuildID 3884097.

**Comment by BlackShadow306** [comment] 2019-06-03 18:45
Can confirm. Fixed.

**Comment by agrastiOs** [comment] 2019-06-04 15:42
You should close the issue @BlackShadow306.

**Closed** 2019-06-04 15:42 UTC
