### ISSUE TITLE
GL_ARB_multitexture forced on

### ISSUE THREAD

**Issue by Enokilis** [ValveSoftware/halflife#2268] opened 2019-04-24 19:04 UTC
If the engine finds the OpenGL extension string of GL_ARB_multitexture, it will make use of hardware multitexturing capabilities to draw lightmaps and detail textures.
Unfortunately, this breaks the functionality of gl_overbright, and the only way to restore it is to manually disable the OpenGL extension at the driver level. The lacking functionality of this feature is often incorrectly attributed to a total removal in the Steam version of the game, but the reason for its presence in older versions of the game is that the engine instead checked for an OpenGL extension string named GL_SGIS_multitexture, and because this string is obsolete and not reported in modern graphics drivers, the engine assumes that multitexturing is not supported.
A simple option to toggle multitexturing independently of its driver availability in the game would eliminate this problem.

**Comment by SamVanheer** [comment] 2019-04-24 19:10
Duplicate of #1891 

See #230 for some more information, overbright and multitexture may be compatible after all.

**Comment by kisak-valve** [comment] 2019-04-24 19:12
Hello @Enokilis, as noted by @SamVanheer, this issue is already being tracked at #1891. Feel free to add this to the existing issue report.

Closing as a duplicate.

**Closed by kisak-valve** 2019-04-24 19:12 UTC
