### ISSUE TITLE
[cs16] shield hitbox problem and others problems with hitboxes and desyns

### ISSUE THREAD

**Issue by hackovh** [ValveSoftware/halflife#2586] opened 2019-07-15 19:34 UTC
video https://youtu.be/-3jLTLs-qkY https://youtu.be/umEO6BDsEwM
fix https://github.com/ValveSoftware/halflife/issues/2243 and fix 45pitch

**Comment by hackovh** [comment] 2019-07-15 19:41
ez fix valve!1

**Comment by SamVanheer** [comment] 2019-07-16 08:37
Is this a new issue or is this caused by #2154?

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-07-16 11:41
What does 45 pitch mean?
@hackovh

**Comment by hackovh** [comment] 2019-07-16 11:45
> 
> 
> What does 45 pitch mean?
> @hackovh

compression angles aka -45 45 pitch limit model

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-07-16 12:30
So, gaityaw fix help's with hitboxes bug? Or what?
You can try to make gaitway networked with delta.lst file in cstrike folder.

**Comment by hackovh** [comment] 2019-07-16 15:08
> So, gaityaw fix help's with hitboxes bug? Or what?
> You can try to make gaitway networked with delta.lst file in cstrike folder.

networked gaityaw fix big desyns hitboxes

**Comment by PRinceBhai** [comment] 2019-07-16 18:35
Remember those ones that were fixed in 2013? Lmao another decade is now on queque.

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-07-16 18:55
True.

**Comment by zoruamonster** [comment] 2019-12-26 19:53
@mikela-valve you can't fix hitbox problem ?)) you is very bad encoder ?))

**Comment by kisak-valve** [comment] 2019-12-26 20:33
@zoruamonster, congratulations, you have forced a response.

Unfortunately, your continued unconstructive feedback has resulted in being blocked from this issue tracker. [Spamming](https://github.com/ValveSoftware/halflife/issues/2835) [multiple](https://github.com/ValveSoftware/halflife/issues/2801) [issue](https://github.com/ValveSoftware/Dota-Underlords/commit/9f609e81551f6c9cfccae56f9c706d88febc953e#commitcomment-36585401) [trackers](https://github.com/ValveSoftware/openvr/commit/4864a545d03a831c4e37958e15321e1f9aee4a17#commitcomment-36585396) and [abusing](https://github.com/ValveSoftware/halflife/issues/2821) this issue tracker will not encourage anyone to investigate issues you're encountering.

As a friendly reminder, I'm a moderator for these issue trackers and not a halflife dev. Please find a different community to troll.

**Comment by farifa4523** [comment] 2020-01-12 15:33
@kisak-valve @tycho @mikela-valve please fix it!!! Now 2020 year!!!

**Comment by karaul0v2020** [comment] 2020-01-17 17:14
@tycho @mikela-valve please fix this issue in 2020 year!

**Comment by 0karaulov** [comment] 2020-01-26 05:46
@tycho @mikela-valve please fix this issue in 2020 year!

**Comment by 0karaulov** [comment] 2020-01-26 08:21
@kisak-valve  @mikela-valve @tycho please fix this issue in 2020 year, or you are very bad coder encoder?

**Comment by e-karaulov** [comment] 2020-01-27 17:03
![4EpVzYu 1](https://user-images.githubusercontent.com/60312041/73196065-01ac4180-4140-11ea-96a1-300a7b9b90c7.png)

please fix hit box....

**Comment by seypaa** [comment] 2020-01-28 06:20
@e-karaulov f*ck off, you moron

**Comment by megacoderencoderdecoder** [comment] 2020-02-06 06:32
@mikela-valve why not fixed, you wrote 24 May 2019 year this message: 
```


Hi all, I just wanted to assure you that I am going to look at this issue after the current release that is going through beta. Unless you have additional technical details or other pertinent information to add to help in fixing this, please refrain from making comments as it makes it more difficult to sift through the comments to help work through the issue.Thanks!
--



```

keep your word and correct this fatal error!

**Comment by Solokiller** [comment] 2020-02-06 08:06
Please stop bumping this issue, it will be done when it's done.

**Comment by megacoderencoderdecoder** [comment] 2020-02-06 12:20
> Please stop bumping this issue, it will be done when it's done.

Maybe they just forgot , and need remind about it)))

**Comment by kisak-valve** [comment] 2020-02-06 13:40
If the only point of this issue report is to collect spam and indirectly reference #2154, then this is a duplicate. When there's a change worth retesting in the game, it will be communicated clearly.

Closing as a duplicate. Locking due to the ongoing spam from throwaway accounts.

**Closed by kisak-valve** 2020-02-06 13:40 UTC
Labels: Counter-Strike
