### ISSUE TITLE
[HL1] [Request] How to get old view bobbing from the original WON release back?

### ISSUE THREAD

**Issue by DrFerret** [ValveSoftware/halflife#3352] opened 2023-06-28 21:41 UTC
I know there is already a thread for this, but I wasn’t sure if it was for WON, Steam, or both. I’m trying to get this working on the WON v1.1.1.2 file. After v1.1.0.8, the view bobbing was removed. I don’t really want to download any mods if it’s possible. I just want to code it in if I can. This thread explains how to code it in but I’m not sure what version it’s for: https://github.com/ValveSoftware/halflife/issues/1544

**Comment by kisak-valve** [comment] 2023-06-28 21:45
Hello @DrFerret, please do not intentionally open duplicate issue reports.

Closing as a duplicate of #1544.

**Closed by kisak-valve** 2023-06-28 21:45 UTC
