### ISSUE TITLE
Most Mods won't even launch.

### ISSUE THREAD

**Issue by OpenRift412** [ValveSoftware/halflife#3412] opened 2023-11-17 18:51 UTC
Don't know how much of a hole you guys dug yourselves into here, but here's some of the errors I've gotten.

I know we can just switch back to the Legacy Branch for mods, but I hope this isn't going to be your only solution to this problem going forward.

Half-Life: Echoes
![image](https://github.com/ValveSoftware/halflife/assets/29780788/1b0dd9cc-f0b5-4664-873e-64a3eee23260)
![image](https://github.com/ValveSoftware/halflife/assets/29780788/661c67db-a4ab-4c99-a70c-8066079c0475)

They Hunger
![image](https://github.com/ValveSoftware/halflife/assets/29780788/2571ddcf-d701-4c90-bd4e-6fc07de2db7f)

**Comment by debasish-mihup** [comment] 2023-11-17 18:55
same here.

**Comment by exegg** [comment] 2023-11-17 19:00
All the games based on HL1 are broken right now.

**Comment by JoelTroch** [comment] 2023-11-17 19:22
The `maxWidth >= width` assertion is likely caused by addons and/or mods that changed GameUI files (the `resource` folder in the concerned game/mod).

A workaround for said assertion is to uninstall such addons or in the case of a mod, try renaming its `resource` folder to something.

Community mods that will eventually require an update to apply the changes from the 25th anniversary build.

**Comment by JoelTroch** [comment] 2023-11-17 21:35
**UPDATE:** community mod developers can "fix" the assertion by editing the `resource/TrackerScheme.res` file (if present and modified by addon/mod) and adding the following key/value pairs in the `BaseSettings` section:

```
"ProportionalBaseWidth" "1280"
"ProportionalBaseHeight" "720"
```

**Comment by di57inct** [comment] 2023-11-18 10:40
> **UPDATE:** community mod developers can "fix" the assertion by editing the `resource/TrackerScheme.res` file (if present and modified by addon/mod) and adding the following key/value pairs in the `BaseSettings` section:
> 
> ```
> "ProportionalBaseWidth" "1280"
> "ProportionalBaseHeight" "720"
> ```

copying the lines in cstrike or czero doesn't fix them though

**Comment by JoelTroch** [comment] 2023-11-18 12:33
> > **UPDATE:** community mod developers can "fix" the assertion by editing the `resource/TrackerScheme.res` file (if present and modified by addon/mod) and adding the following key/value pairs in the `BaseSettings` section:
> > ```
> > "ProportionalBaseWidth" "1280"
> > "ProportionalBaseHeight" "720"
> > ```
> 
> copying the lines in cstrike or czero doesn't fix them though

The "fix" I mentioned above is for addons and mods made by the **community**, not by Valve.

Counter-Strike (including Condition Zero and Deleted Scenes) are under Valve's responsibility. You can either wait for Valve to fix these games or if you cannot wait, switch your Half-Life 1 installation to the `steam_legacy` branch.

And to be perfectly clear: the "fix" I mentioned is only for assertions involving `maxWidth >= width` on the `ListPanel.cpp` file. For other assertions (such as the ones involving "modules"), these are other problems and this "fix" won't fix it.

**Comment by di57inct** [comment] 2023-11-18 13:17
Understood, thank you :)

**Comment by OpenRift412** [comment] 2023-11-22 22:28
Seems like most mods work now, except Half-Life: Echoes still gets the same error as before. 

Also while menus are functional now for most mods, some mods that don't have a custom title screen won't load the base game's title screen or animated logo. Don't know if that's resolvable through updates or if modders would have to update their mod once the SDK comes out. Hopefully the former.

**Comment by Srandista** [comment] 2023-11-22 22:50
Echoes works for me now (unlike before, when 25th anniversary patch was released). Have you tried doing clean installation of Echoes? I just did that to be sere and sure enough, I can run it without any issues (with or without cross build patch).

**Comment by OpenRift412** [comment] 2023-11-22 23:21
> Echoes works for me now (unlike before, when 25th anniversary patch was released). Have you tried doing clean installation of Echoes? I just did that to be sere and sure enough, I can run it without any issues (with or without cross build patch).

Oh, okay yeah that seemed to fix it. Thanks!

**Comment by shawns-valve** [comment] 2024-10-04 06:04
A number of mod compatibility issues have been fixed in patches late last year, as well as in the October 2, 2024 HL Steam update. If there's a particular mod that isn't working now but works with the steam_legacy engine, please open a specific issue for that mod.

**Closed by shawns-valve** 2024-10-04 06:04 UTC
