### ISSUE TITLE
[CS 1.6] Monitor Refresh Rate issue. [Feature Request?]

### ISSUE THREAD

**Issue by idderf** [ValveSoftware/halflife#45] opened 2013-02-15 09:56 UTC
Ever since the beta launch, and the removal of the -freq launch option, everyone has had cs run at 60hz. The only way to get a higher refresh rate is to use a third party software called refresh lock, which locks certain monitor refresh rates to certain resolutions. If you just brought back the -freq launch option everyone would be pleased.

**Comment by djdallmann** [comment] 2017-07-24 18:41
-freq only works sometimes but without -nofbo, not sure of the cause.

**Comment by i486** [comment] 2018-03-30 00:14
Any news on this?

**Comment by i486** [comment] 2018-03-30 00:34
I really don't understand why they made -freq not working when we are using -nofbo option.
-freq should be working when using -nofbo option.

**Comment by i486** [comment] 2018-03-30 00:37
I don't want to use the refreshlock or any external program.
I don't want to use 75Hz supported resolution everytime i have to launch CS 1.6. Looks weird and besides i ALT+TAB a lot.

**Comment by mikela-valve** [comment] 2019-04-20 03:38
Hi all, this should be fixed in the latest HL1/OpFor/TFC/CS betas. The -freq parameter is now respected when used with -nofbo and the resulting full-screen setting will attempt to use the specified refresh rate.

When used without -nofbo, -freq will still attempt to set the refresh rate of the screen to the specified value but will only succeed if the monitor supports that setting at the current desktop resolution.

**Comment by i486** [comment] 2019-04-26 17:43
OMG OMG OMG

REAL MVP mikela

Thanks!

**Comment by i486** [comment] 2019-04-26 17:59
-freq with nofbo works!

But graphic is looking very pixelated even with or without nofbo/freq

<blockquote class="imgur-embed-pub" lang="en" data-id="aRAHPn2"><a href="//imgur.com/aRAHPn2">View post on imgur.com</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

**Comment by basuritashka** [comment] 2019-04-26 18:00
> 
> 
> -freq with nofbo works!
> 
> But graphic is looking very pixelated even with or without nofbo/freq
> 
> [img][https://i.imgur.com/aRAHPn2.png[/img]](https://i.imgur.com/aRAHPn2.png%5B/img%5D)

#1650 related.

**Comment by mikela-valve** [comment] 2019-05-14 23:05
Closing as done.

**Closed by mikela-valve** 2019-05-14 23:05 UTC
Labels: Counter-Strike, Feature Request, reviewed
