### ISSUE TITLE
SayText message is broken in recent builds

### ISSUE THREAD

**Issue by 2010kohtep** [ValveSoftware/halflife#2531] opened 2019-06-16 09:34 UTC
In the latest build, the ```SayText``` message can't process chat message from some plugins correctly. Instead of a chat message, the letter ```s``` is written.

![image](https://user-images.githubusercontent.com/2564175/59562109-49f37500-9031-11e9-855a-db71ba69728c.png)

It happens due to the code in the ```__MsgFunc_SayText``` function, which removes the ```%``` characters from ```String1```. Some game plugins store formatting rules in this line.

![image](https://user-images.githubusercontent.com/2564175/59562160-e61d7c00-9031-11e9-8e1b-3f89d289d77b.png)

In the image below, you can see that the message is completely correct, but the latest builds of the game cannot correctly process it.

![image](https://user-images.githubusercontent.com/2564175/59562179-1e24bf00-9032-11e9-930c-2c32e2ab229e.png)

**Comment by SamVanheer** [comment] 2019-06-16 10:30
Possible duplicate of #1819

**Comment by 2010kohtep** [comment] 2019-06-16 10:38
@SamVanheer, this problem arose in the 8xxx build generation. The problem is missing in the 7960 build. Perhaps the problems are similar, but they are not identical.

**Comment by RauliTop** [comment] 2019-06-17 10:25
@mikela-valve both problems should be fixed on Next release, please

**Comment by mikela-valve** [comment] 2019-06-17 18:14
@2010kohtep That's weird that 7960 didn't have this change in it as it looks like Alfred added it in mid-2013. Do you happen to know what the build date is for 7960?

This might require a choice between security and convenience though, at least without rewriting `SayTextPrint` to handle localization differently. As you'd figure, percent characters are stripped from that due to it being used as a printf formatter later when localization tokens are replaced in it. I'd have to look more closely at strings passed to SayTextPrint to see if there is a different way I can process the text effectively to still handle localization correctly.

Could you give me some examples of how rules are stored? Possibly I could find some compromise that could add some special handling for `%` like still stripping it out of the string but adding it as a separate message, appending it to the message or something else that wouldn't require a rewrite of `SayTextPrint`.

**Comment by basuritashka** [comment] 2019-06-17 18:16
@mikela-valve 
![image](https://user-images.githubusercontent.com/33007491/59626649-6ca58c80-910a-11e9-8786-53175adffc0f.png)

**Comment by mikela-valve** [comment] 2019-06-17 20:17
Thanks @basuritashka. It looks like 7960 should have this same `%` filtering and should work the same so it's quite strange if it didn't have that filtering in it. 

@2010kohtep are you sure this is actually different from #1819 as @SamVanheer pointed out? I don't see anything different happening in this issue other than the string arguments subsequently being ignored due to the `%` in the format specifier being stripped out. 

The main issue that complicates allowing format specifiers in the input string is that `SayTextPrint` handles both localized and non-localized input strings so there numerous ways things could go wrong at the moment if they weren't filtered. I may be able to update `SayTextPrint` to allow format specifiers in the input string so long as there aren't any localization tokens in the string and filter out any excess specifiers before formatting it but I'll have to do a bit more investigation first.

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-06-18 01:06
Yes. It's seems like different issues.
It's not duplicate.

**Comment by mikela-valve** [comment] 2019-06-18 01:20
I'm not sure I follow, how exactly is it different? 

#1819 is caused by the `%` being stripped from the input string to `MsgFunc_SayText` and this is also caused by the `%` being stripped leading to only `s` being displayed instead of being replaced by `☹*DEAD* ♥Player☹ :  test 123`. It's fine if there are multiple issues I just want to clarify what they are.

**Comment by mikela-valve** [comment] 2019-06-18 22:03
@2010kohtep I updated `SayTextPrint` as I described above where it's able to have up to four format specifiers that the four string parameters are mapped to. Any format specifier beyond the fourth or any specifier that is not `%s` will be filtered as it is currently. This will be included in the next beta release.

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-06-19 14:08
Check %s0.

**Comment by mikela-valve** [comment] 2019-06-19 14:14
@afwn90cj93201nixr2e1re Sorry, forgot to mention that I did fix that bug as well when working on this. Thanks!

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-06-19 14:16
But what 'bout icons in tab, xD?
It's easy to implement defuse/bomb icon, for each team, and for VIP you can add just icon with 'V' letter.

**Comment by mikela-valve** [comment] 2019-06-21 00:26
This should be fixed in beta update '15:46:27 Jun 11 2019 (8265)'.

**Comment by Mistrick** [comment] 2019-06-21 09:47
@mikela-valve I think you broke some lang keys.
Current output
```
Time Remaining:  11: .2s
```
title.txt
```
Game_timelimit
{
Time Remaining:  %s:%.2s
}
```

**Comment by mikela-valve** [comment] 2019-06-21 18:17
Thanks @Mistrick, I changed where the format stripping was occurring which happened to mistakenly apply it to pre-formatted strings like that one. I've fixed it to filter the input strings in the same place as before.

**Comment by mikela-valve** [comment] 2019-06-21 21:18
@Mistrick This should be fixed now in beta.

**Comment by mikela-valve** [comment] 2019-06-26 17:57
Closing as fixed.

**Closed by mikela-valve** 2019-06-26 17:57 UTC
