### ISSUE TITLE
Blacklist servers from the Internet tab

### ISSUE THREAD

**Issue by basuritashka** [ValveSoftware/halflife#2236] opened 2019-04-24 01:58 UTC
Title. There are certain "fake" servers on the Internet tab, with this, you should perma-blacklist the IP and it wont appear on the Internet tab FOR you.

**Comment by kisak-valve** [comment] 2019-04-24 02:06
Hello @basuritashka, this is effectively a duplicate of #1993 / #2064. Closing in favor of the existing issue reports.

**Closed by kisak-valve** 2019-04-24 02:06 UTC
