### ISSUE TITLE
[CS 1.6] Chat UTF-8 problem

### ISSUE THREAD

**Issue by wilianmaique** [ValveSoftware/halflife#2651] opened 2019-07-30 14:40 UTC
UTF8 is working on the console, and in normal chat, but in the upper left chat log is still bugged.

Image: https://i.imgur.com/x2XrU7X.jpg

**Comment by Mistrick** [comment] 2019-07-30 14:51
Duplicate of #2415

**Comment by kisak-valve** [comment] 2019-07-30 15:12
Closing in favor of the existing issue report.

**Closed by kisak-valve** 2019-07-30 15:12 UTC
Labels: Counter-Strike
