### ISSUE TITLE
[CS 1.6] game_team_master entity issue

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/halflife#667] opened 2013-03-01 11:38 UTC
game_team_master and game_team_set are available in counter-strike, but those entities works just in half-life. The reason behind it is that half-life use different team identification rather counter-strike afaik. I wonder if this can be fixed to work with terrorist and counter-terrorist teams in counter-strike? The only entity that is able to distinguish counter-strike teams is func_buyzone, so I assume it should be somewhat possible to alternate work of mentioned entities (for cs 1.6). Best regards!

**Comment by SamVanheer** [comment] 2019-05-04 21:01
Duplicate of #197

**Comment by kisak-valve** [comment] 2019-05-04 21:04
Closing per the last comment.

**Closed by kisak-valve** 2019-05-04 21:04 UTC
Labels: Feature Request, reviewed
