### ISSUE TITLE
[DMC] DeathMatch Classic crashes when you try to connect to/host the server after 25th anniversary update

### ISSUE THREAD

**Issue by TheESN** [ValveSoftware/halflife#3479] opened 2023-11-19 02:20 UTC
After 25th anniversary update, DMC cannot start new game or join to the existing game. After loading screen it just closes its own window

**Comment by kisak-valve** [comment] 2023-11-19 02:30
Hello @TheESN until Deathmatch Classic gets an update, you should be able to workaround this issue by switching Half-Life in your Steam library to the `steam_legacy` beta branch.

**Comment by Ch0wW** [comment] 2023-11-20 21:50
It looks like the problem is fixed with the Nov 19 update.

**Comment by kisak-valve** [comment] 2023-12-23 02:17
Closing per the last comment.

**Closed by kisak-valve** 2023-12-23 02:17 UTC
Labels: Deathmatch Classic, Need Retest
