### ISSUE TITLE
Block getting md5 hashes | Getting free bans on some servers

### ISSUE THREAD

**Issue by afwn90cj93201nixr2e1re** [ValveSoftware/halflife#2596] opened 2019-07-18 15:47 UTC
@kisak-valve don't close it for few (for example 2) day's.

@mikela-valve  check it, https://github.com/ValveSoftware/halflife/issues/2158#issuecomment-512873173.

![изображение](https://user-images.githubusercontent.com/9306996/61472256-2192c980-a995-11e9-81e6-77351e80da59.png)
![изображение](https://user-images.githubusercontent.com/9306996/61472270-28214100-a995-11e9-83c9-517b194d286e.png)

**Comment by kisak-valve** [comment] 2019-07-18 15:58
@afwn90cj93201nixr2e1re, please do not intentionally open duplicate issue reports. This is against the [Code of Conduct](https://github.com/ValveSoftware/halflife#conduct) for this issue tracker.

Closing as a duplicate of #2158.

**Closed by kisak-valve** 2019-07-18 15:58 UTC

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-07-18 16:02
Please don't be noisy.

@mikela-valve didn't check issues on last pages.

**Comment by eat1k** [comment] 2019-07-18 19:35
Just don't play these servers if you get ban. These are their servers. They can do whatever they want there.

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-07-18 21:10
Just remove your server from steam master server and im not gonna play on it, ok?
