### ISSUE TITLE
Deathmatch Classic PlayerModel Color bug

### ISSUE THREAD

**Issue by shytzedaka** [ValveSoftware/halflife#1738] opened 2016-08-12 08:30 UTC
There is this Bug In which there is No preview of the Color you Select of your Player model In Multiplayer.

IE. When you pick a playermodel in lets say Deathmatch Classic Or Half life 1 (Multiplayer) The Color Slide Does not Show a Change Of Color in the Preview. altho In-game it Changes. 

Please fix?

**Comment by SamVanheer** [comment] 2019-05-04 21:57
Duplicate of #1477

**Comment by kisak-valve** [comment] 2019-05-04 22:03
Closing per the last comment.

**Closed by kisak-valve** 2019-05-04 22:03 UTC
