### ISSUE TITLE
Problem with FastDL and server resources...

### ISSUE THREAD

**Issue by Zetz512** [ValveSoftware/halflife#2731] opened 2019-10-11 12:50 UTC
With the latest update, i can't download from servers with FastDL (Fast Download), because that get stuck like this

![123](https://user-images.githubusercontent.com/26032689/66652399-05a56980-ec0c-11e9-83eb-2d6e08f7ee01.png)

And when i disable the fastdl (sv_downloadurl "") 

I get this in console...

![1234](https://user-images.githubusercontent.com/26032689/66652471-28d01900-ec0c-11e9-91ca-580ed044a356.png)

And i can play normally without any crash but the models are dont downloaded i see invisible...

![12345](https://user-images.githubusercontent.com/26032689/66653237-ef001200-ec0d-11e9-9c95-89d6fc866f06.png)

**Comment by BlackShadow** [comment] 2019-10-11 20:44
I can't reproduce it, probaly server related.

**Comment by mikela-valve** [comment] 2019-10-11 23:43
Thanks @BlackShadow, if anyone else can try reproing this as well that would be great.

@Zetz512 I'm not aware of anything changing in the way FastDL works in this release but there could be something it was relying on that changed. I just updated the HL1 beta version to reduce the strictness of that 'Invalid file type' check when you have FastDL disabled that should allow it to work for downloading game things like models and sounds again. The version displayed in the console will be the same as the current public version but the BuildID in the Local Files section of the game properties will be `4280512` for the beta version.

**Comment by basuritashka** [comment] 2019-10-11 23:44
@mikela-valve There was another friend that could not download some files properly too (same problem as @Zetz512), not sure how tho. I cannot reproduce it either.

**Comment by mikela-valve** [comment] 2019-10-11 23:51
@basuritashka Did you happen to be testing with the same download server as your friend at the time or does it just work for you on other servers you've tried?

**Comment by basuritashka** [comment] 2019-10-11 23:53
I tested both IP from my friend and from @Zetz512 itself, I was able to download everything properly on latest stable version and it was for sure using FastDL properly.

Yesterday photo from a friend that got stuck on downloading a map.
![image](https://user-images.githubusercontent.com/33007491/66690846-2223bf00-ec69-11e9-9a0f-b8e7d99479b8.png)

**Comment by mikela-valve** [comment] 2019-10-12 00:00
If your friend is able to consistently get stuck like that it would be great if you could have them try the beta to see if it does anything to fix it. I haven't traced through the logic yet to see if FastDL does anything different but it's possible it could hit the same file safety checks that regular resource downloading does and just hang like that instead of erroring.

**Comment by Zetz512** [comment] 2019-10-12 01:29
Good, i recently try the beta and the fastdl download now skip/continue but the invalid file types still persist and dont download anything you can see in the image...

![Screenshot_3123123](https://user-images.githubusercontent.com/26032689/66692612-784b2f00-ec76-11e9-9ac2-e47a0e413cb1.png)

**Comment by mikela-valve** [comment] 2019-10-12 02:12
Sorry about that, somehow that beta version didn't have the latest changes in it. The update I just added should work now, BuildID `4280961`.

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-10-12 13:00
i like dat, can you add new cvar, for skip downloading all files, and replace ptr's to blank files, like blank.mp3, blank.mdl etc excluding .bsp? we need that for some debug sometimes.

**Comment by Zetz512** [comment] 2019-10-12 17:52
Now i dont see the same error and when connect server dont get stuck downloading a file...

But this errors you see in the image, this is like can't connect to fastdl to download the resources or something like that.

![bugfastdl](https://user-images.githubusercontent.com/26032689/66705641-ad4f9400-ecff-11e9-9472-415ad3d68281.png)

and the other error is like a X file dont be found on the server and can't be download them

http://prntscr.com/piel9y

In a old client, can download all resources and join normally to the server..

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-10-12 19:39
can you execute developer 1, then connect to the server and disconnect after join, then execute condump and attach file here.

**Comment by Zetz512** [comment] 2019-10-12 19:45
Ok, here is...

[condump000.txt](https://github.com/ValveSoftware/halflife/files/3721090/condump000.txt)

**Comment by BlackShadow** [comment] 2019-10-12 19:51
I think it's a server directory issue

As seen on log "models\Skins_P\v_awp.mdl" it can't find the file because it's using "\" instead "/"

Server owner misconfigured FastDL it seems.

It should been like this if the FastDL was configured correctly:


Requesting HTTP download of 
http://31.28.170.122/fast31095/cstrike/models/player/dangerTT/dangerTT.mdl 
Saved http://31.28.170.122/fast31095/cstrike/models/player/dangerTT/dangerTT.mdl  to disk

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-10-12 20:14
http://fastdl2.arrowhosted.com/afuqkmbi/101_27033/cstrike/models\Skins_P\v_awp.mdl

:/
try to change one path of random model in you source to forward slash, and check is that downloaded.

Seems like something in steamclient.dll (SteamHTTP) or url normalisation in goldsrc engine was changed.

**Comment by Zetz512** [comment] 2019-10-13 03:15
.-. , and how i can change that slash...

**Comment by Zetz512** [comment] 2019-10-13 03:44
:o, i will try this, ty.

**Comment by rtxa** [comment] 2019-10-18 03:44
Any news with this issue? I can confirm this is happening to me with the last update. Using an older build bypass the problem.

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-10-18 03:55
show any additional logs with developer 1.

as you can see it's expected and fixed for op by replacing wrong paths: https://github.com/ValveSoftware/halflife/issues/2731#issuecomment-541383221

**Comment by mikela-valve** [comment] 2019-10-21 20:44
Hi @Zetz512 and @rtxa, this should be fixed now in the latest beta for the case that @Zetz512 posted where backslashes are used in the URL. Backslashes are now auto-converted to forward slashes for download URL's that are sent to Steam to be handled.

**Comment by RauliTop** [comment] 2019-10-22 07:39
> Hi @Zetz512 and @rtxa, this should be fixed now in the latest beta for the case that @Zetz512 posted where backslashes are used in the URL. Backslashes are now auto-converted to forward slashes for download URL's that are sent to Steam to be handled.

Don't forget Next release milestone

**Comment by mikela-valve** [comment] 2019-10-22 07:44
Thanks @RauliTop! These will actually go out in a small update to fix issues arising from the last release so I'll actually add a new milestone for that.

**Comment by Zetz512** [comment] 2019-10-22 17:00
Gj thanks for fast answer! Sry if this dont goes with this topic, but you can see my other suggest about v_models rendermode? This is a little thing will can be amazing

**Comment by Splatt581** [comment] 2019-10-22 17:24
@mikela-valve by the way, it may also be worth removing backslash or doing auto-convertion to forward slash for precaching server resources in `SV_CreateGenericResources`.

**Comment by mikela-valve** [comment] 2019-10-23 17:25
@Splatt581 It looks like we currently don't allow any backslashes in the resource path, regardless of where it is in the path (should error with `Can't precache resource with invalid relative path <path>`). It looks like forward slashes are the only allowed path separator. The `.res` file itself does already have forward/backslash conversion. 

Could you clarify what should be changed please? Feel free to open another issue or update another if there is one open already for this.

Thanks!

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-10-24 03:47
> Backslashes are now auto-converted to forward slashes for download URL's that are sent to Steam to be handled.

For what?

**Comment by Splatt581** [comment] 2019-10-24 17:12
> @Splatt581 It looks like we currently don't allow any backslashes in the resource path, regardless of where it is in the path (should error with `Can't precache resource with invalid relative path <path>`). It looks like forward slashes are the only allowed path separator. The `.res` file itself does already have forward/backslash conversion.
> 
> Could you clarify what should be changed please? Feel free to open another issue or update another if there is one open already for this.
> 
> Thanks!

It seems that conversion does not occur, because I tried to precache `asd\asd.txt` file via `.res` file of map on latest beta dlls of Windows version of engine and got `Can't precache resource with invalid relative path asd\asd.txt` error. As I understand it, `SV_CreateGenericResources` function should follow same checks as `IsSafeFileToDownload`, that's why I proposed to do the conversion.

**Comment by mikela-valve** [comment] 2019-10-24 19:17
Ok, good. That's what I thought would happen so I just wanted to confirm. I think it would be fine to change it around to match `IsSafeFileToDownload`. Rather than converting the slashes I'll just make both backslashes and forward slashes allowed in the path as long as they are not being used to form an absolute path. This matches the behaviour of `IsSafeFileToDownload`.

The latest beta should have this change in it. If all is good with it I'll update the public version with this beta.

**Comment by Splatt581** [comment] 2019-10-25 16:19
Thanks! Everything works fine.

**Comment by mikela-valve** [comment] 2019-10-25 18:11
Thanks @Splatt581! Closing as fixed.

**Closed by mikela-valve** 2019-10-25 18:11 UTC
Labels: Counter-Strike
