### ISSUE TITLE
Plеаsе fiх fuсking hitbохеs!!!!

### ISSUE THREAD

**Issue by msozn1qwcxn7** [ValveSoftware/halflife#2841] opened 2020-01-08 12:16 UTC
https://github.com/ValveSoftware/halflife/issues/2154

![56459250-92781480-6399-11e9-9f02-27f160164b1b 1](https://user-images.githubusercontent.com/59650465/71977375-a9ada980-3229-11ea-8263-6d7c87fde9e2.gif)

Sorry for bad japan language

**Comment by kisak-valve** [comment] 2020-01-08 13:01
Closing as a duplicate of #2154.

**Closed by kisak-valve** 2020-01-08 13:01 UTC
