### ISSUE TITLE
cs 1.6

### ISSUE THREAD

**Issue by elmatadour** [ValveSoftware/halflife#1625] opened 2015-06-01 12:52 UTC
Error: server failed to transmit file 'sound/misc/dohoo.wav'
Error: server failed to transmit file 'sound/misc/dohnuts.wav'
Error: server failed to transmit file 'sound/misc/doh2.wav'
Error: server failed to transmit file 'sound/misc/doh3.wav'
Error: server failed to transmit file 'sound/misc/doh4.wav'
Error: server failed to transmit file 'sound/misc/doh5.wav'
Error: server failed to transmit file 'sound/misc/doh7.wav'

**Comment by JoelTroch** [comment] 2015-06-01 12:56
Those are custom sounds which aren't part of stock CS 1.6. I'm afraid you won't get support for that here.

**Comment by SamVanheer** [comment] 2019-05-05 11:39
This issue concerns a server attempting to send custom files to the client, it's not a bug so this issue can be closed.

**Comment by kisak-valve** [comment] 2019-05-05 13:26
Closing per the last comment.

**Closed by kisak-valve** 2019-05-05 13:26 UTC
