### ISSUE TITLE
[TFC] hand-held grenade pop-up bug, latency based

### ISSUE THREAD

**Issue by SpiderWaffle** [ValveSoftware/halflife#1561] opened 2014-10-24 05:02 UTC
This bug was BY FAR AND AWAY the largest game impacting bug of the ADL Attack Defend League, even more so than players playing with hacks. The HH grenade jump is the MOST important tool for an offense on most attack defend maps, when that is stripped away from them, it's virtually impossible to win or play a game that resembles competitive quality game-play that we know and love.

When attempting a hand-held grenade jump with a normal grenade (or mirv I suppose) where a player will let the grenade timer run out to explode on himself while moving in a desired direction, usually via a jump, circle jump, bhop jump, or rocket jump. Normally this should apply the damage boost in the same direction the player was moving because the grenade explodes slightly behind the player along his movement vector.

This happens in client servers 100% of the time where there is no latency, and likely 100% or 99.9% on lan servers with very low ping. It's when the server starts to get a ping over 100-120 that you see a huge drop success rate, it is also very dependent on the server network settings and various other network factors, like some attack defend specializing servers found settings that allowed player perform the proper HH nade jumps with responsibly high pings near 100% of the time.

So on higher latency servers depending on their settings, a HH nade jump would "pop-up" the player, that is the nade would explode directly underneath the player, completely regardless of the player's velocity vector at time of detonation. Sometimes this could happen 50% of the time, in a basically random fashion, or even nearly 100% of the time if the connection is extra "special"

A very similar phenomenon is experienced with HH concision grenades, in which rather than receiving a normal HH conc boost, the player will receive no boost. It also very much dependent on the network, and confirmed as well be to related the players current speed at time of conc detonation. For example, when moving at 450 units/s with 90 ping on a given server, your HH concs might work properly 90% of the time, same speed with 50 ping on same server they might work 99.9% of the time. When moving at 800 units/s and 90 ping expect to see a significant drop from 90% to maybe 30% and with 50 ping perhaps small drop from 99.9% to 90%

Back when I played in the ADL (attack defend league) dishonest, low integrity clans like game face, who were rostered with various known and proven hackers, were rumored, and largely confirmed with self statistics, to even change their server settings to prevent the offence from HH grenade jumping against them at high success rate, and then switching their server settings when they were offense to grant 100% HH success rate.

**Comment by kisak-valve** [comment] 2019-07-18 13:14
Closing as a duplicate of #1481.

**Closed by kisak-valve** 2019-07-18 13:14 UTC
