### ISSUE TITLE
Options in 'Content' section is overlapped

### ISSUE THREAD

**Issue by Diegoparedeshd1** [ValveSoftware/halflife#3726] opened 2023-12-19 23:43 UTC
When are you going to fix this problem? This problem has been going on for a month and they haven't fixed it.
It occurs in both the Spanish and Italian languages.
![284009819-265df2f1-43d5-43a5-8e26-54d7f448dfbf](https://github.com/ValveSoftware/halflife/assets/151307139/89b14609-72ab-44d8-84e4-fafdc6ee8235)

**Comment by kisak-valve** [comment] 2023-12-20 00:03
Hello @Diegoparedeshd1, please do not intentionally open duplicate issue reports.

Closing as a duplicate of #3465.

**Closed by kisak-valve** 2023-12-20 00:03 UTC
