### ISSUE TITLE
[Feature Request] Texture resolution limits

### ISSUE THREAD

**Issue by BlackShadow306** [ValveSoftware/halflife#2461] opened 2019-05-23 16:37 UTC
It well be damn good if we can remove the 512x512 texture limit! 👍

**Comment by kisak-valve** [comment] 2019-05-23 17:05
Possible duplicate of #12.

**Comment by SamVanheer** [comment] 2019-05-23 17:21
The limit has to do with the engine using a buffer that's 512 x 1024 x 4 bytes large (RGBA takes up 4 bytes per pixel). Increasing the limit involves increasing the size of the buffer as well, or using a dynamically allocated one.

Link to the relevant code in Quake:
https://github.com/id-Software/Quake/blob/bf4ac424ce754894ac8f1dae6a3981954bc9852d/WinQuake/gl_draw.c#L1007-L1024
https://github.com/id-Software/Quake/blob/bf4ac424ce754894ac8f1dae6a3981954bc9852d/WinQuake/gl_draw.c#L1096-L1128

Dynamic memory allocation isn't that expensive anymore, so maybe it could be worth experimenting to see how much of a performance impact it has. An upper limit is probably still needed because `GL_MAX_TEXTURE_SIZE` is an API-implementation defined limit, so the engine should query that value and rescale textures to fit. Halving size until it fits will maintain texture size ratio so that's probably the best solution if textures are too large.

**Comment by GBCS-PRO** [comment] 2019-05-23 18:03
Agreed, this limit was already removed in all un-official goldsrc titles (Sven co-op, paranoia 2, etc..) So I don't see a reason why this limit is still there. 1024 is good enough for an old engine imo

**Closed** 2019-06-09 00:16 UTC
Labels: Feature Request
