### ISSUE TITLE
Gauss gun unintended behaviors

### ISSUE THREAD

**Issue by larb0b** [ValveSoftware/halflife#3716] opened 2023-12-17 17:06 UTC
The Gauss gun has weird behaviors that are most likely unintended.

For example:
* If you shoot the lamps in crossfire, the Gauss blast usually ends up killing multiple players in the room above, even those not near the lamp.
* Sometimes, if you shoot a Gauss blast at a wall (can be far away), you get self Gauss'd and die

These issues have been worked around in mods such as AG, but it'd be nice if these behaviors were toggleable with server-side vars.

Here's a brief video that goes into more detail (not by me): https://www.youtube.com/watch?v=gG1gKd_nYX0

**Comment by kisak-valve** [comment] 2023-12-17 18:09
Hello @larb0b, this reads like a duplicate of #1545. Closing in favor of the older issue report.

**Closed by kisak-valve** 2023-12-17 18:09 UTC

**Comment by bucketss** [comment] 2025-02-25 05:34
feature not bug
