### ISSUE TITLE
[GoldSource/Steam/Feature Request] Enable Proton on Windows-only mods

### ISSUE THREAD

**Issue by LucesEnBabel** [ValveSoftware/halflife#2269] opened 2019-04-24 19:15 UTC
Currently the only way to play Windows mods on proton is to force the Proton setting on the base game (Half-Life). 

Forcing Proton on the mods but not on Half-Life has absolutely no effect because native Half-Life is still being executed.

Maybe a value defined in the `liblist.gam` file to automatically enable Proton on mods?

This feature would require to download both Linux and Windows binaries when downloading Half-Life, it already does for the gamedll but not sure on the engine files.

**Comment by Sockman1** [comment] 2019-04-24 19:55
This seems like more of an issue with proton and less with half-life itself, I'd post this issue there instead.

**Comment by mikela-valve** [comment] 2019-04-24 20:38
I spoke with the developer working on Proton support and confirmed that we don't currently enable/disable the Proton configuration on dependencies of games where it is set, only on the games where it is explicitly set. As we already do set dependency configurations for other settings (such as beta configuration) it would make sense to do so for Proton as well.

Since this isn't actually an HL1 issue I'm going to close this but this is noted now on our internal task list for Proton. Thanks!

**Closed by mikela-valve** 2019-04-24 20:38 UTC
Labels: Feature Request, Linux, Steam Client
