### ISSUE TITLE
[CS 1.6] Can't start CS 1.6

### ISSUE THREAD

**Issue by Maxi605** [ValveSoftware/halflife#2526] opened 2019-06-11 23:41 UTC
A few days ago this happened to me, somehow steam thinks i'm playing the game when is not running (I was playing, closed the game and continues to say i'm still playing), the only solution to this is to restart the computer, another problem is that hl.exe stays open and the game doesn't start (After closing the game hl.exe never closes), i'm running the normal version of the game so i don't know what the problem could be. Another person told me he's having the same issue.
![1](https://user-images.githubusercontent.com/40327830/59313906-3474f880-8c89-11e9-8bf5-f9ef8f2b33c6.jpg)
![2](https://user-images.githubusercontent.com/40327830/59313907-3474f880-8c89-11e9-9313-fac7a7a5cf99.jpg)
![3](https://user-images.githubusercontent.com/40327830/59313908-3474f880-8c89-11e9-9d1c-02f637fc0611.jpg)

**Comment by BlackShadow306** [comment] 2019-06-12 00:45
I believe this issue started to happen latest hl.exe builds. @mikela-valve any ideas about this issue?

**Comment by BlackShadow306** [comment] 2019-06-12 00:52
I believe this issue started to happen latest hl.exe builds.

**Comment by hashnimmo** [comment] 2019-06-12 04:54
To temporarily minimize the times you restart your computer and waiting it all to boot up, go to your **Task Manager** > **Options** > Select **Always on top** and whenever this game hangs up for god knows what, just press **WINDOWS KEY** + **D** to switch to the desktop. Then **ALT** + **TAB** to the Task Manager. Select processes tab, right click on hl.exe and finally **end the task**.

**Comment by mikela-valve** [comment] 2019-06-12 05:07
Is this only happening with a beta version or for the current public release as well? Also, is it all games, just CS/HL1/etc?

If you’re running a beta version, try switching into and out of the beta for both the game and HL1 as well and see if that helps with anything.

**Comment by Maxi605** [comment] 2019-06-13 07:13
> Is this only happening with a beta version or for the current public release as well? Also, is it all games, just CS/HL1/etc?
> 
> If you’re running a beta version, try switching into and out of the beta for both the game and HL1 as well and see if that helps with anything.

Hi there, current public release, haven't try on beta, will now.

**Comment by Maxi605** [comment] 2019-06-13 19:04
yes, the issue is on the beta aswell, just opened the game, only opened hl.exe and the game never started
![Sin título](https://user-images.githubusercontent.com/40327830/59460189-de24c880-8df4-11e9-94c9-7ffd6f7053dd.jpg)

**Comment by Maxi605** [comment] 2019-06-17 07:04
Update on the topic, since i started using the beta the only problem i encounter was sometimes the hl.exe executing but the game never opened, hoped off the beta for a bit and everything was ok, closed the game and Steam says i'm still running it, so that issue still happens to me outside of beta.

**Comment by pizzahut2** [comment] 2019-06-17 16:42
Could it be caused by a Windows 7 security update? I've seen some reports here which all were running Windows 7 SP1, and the time since the problem occurrs might match Microsoft's monthly patch day:

https://forums.esclan.net/index.php/topic,7912.0.html

**Comment by Maxi605** [comment] 2019-06-18 04:04
> Could it be caused by a Windows 7 security update? I've seen some reports for TFC with Windows 7 SP1 as OS, and the time since the problem occurs might match Microsoft's monthly patch day:
> 
> https://forums.esclan.net/index.php/topic,7912.0.html

I'm using W7 so yeah, could be, the only difference is that if i'm running the beta the game doesn't appear to be running when is not

**Comment by Maxi605** [comment] 2019-06-18 06:52
So, found the source of the issue i think, when i launch the game the file rundll32 is getting executed and consuming my entire CPU and it prevents the game from launching, if i close rundll32, i'll start up again whenever i start the game and the game won't open.

**Comment by RauliTop** [comment] 2019-06-18 07:17
Could be caused because you have a No-Steam version of CS 1.6

Are you sure you don't have it? Compability problems are happen when the two versions are installed and executed first one and then another (not simultaneously, because you can't).

**Comment by Maxi605** [comment] 2019-06-18 07:28
> Could be caused because you have a No-Steam version of CS 1.6
> 
> Are you sure you don't have it? Compability problems are happen when the two versions are installed and executed first one and then another (not simultaneously, because you can't).

Hi there, i have a no-steam version of the game installed, yes, but i just re-installed the game since the issue with the rundll32 (Probably a virus) and the issue seems fixed, no rundll32 anymore and the game seems to start correctly.

And no, i never attempted to run both versions at the same time (If that's what you're saying)

My guess is that i got into a malicious server (doubt it) but somehow got infected with something that was running when executing the game, odd, im scanning with avast now and already reinstalled the game

**Comment by kisak-valve** [comment] 2019-06-18 12:34
Closing per the last comment.

**Closed by kisak-valve** 2019-06-18 12:34 UTC
Labels: Counter-Strike, Windows
