### ISSUE TITLE
[GoldSrc] func_friction broken in Multiplayer

### ISSUE THREAD

**Issue by BlackShadow** [ValveSoftware/halflife#2542] opened 2019-06-21 13:11 UTC
For some reason when player touches func_friction entity it creates slippy walking effect. This issue occurs only in Multiplayer games. This issue happens in every Multiplayer Goldsrc game so far.

Video about the bug: https://streamable.com/qn4ep

**Comment by Sockman1** [comment] 2019-06-21 13:39
I think I found the cause in the PM_MOVE function in pm_shared.c:

```
// In single player, reset friction after each movement to FrictionModifier Triggers work still.
	if ( !pmove->multiplayer && ( pmove->movetype == MOVETYPE_WALK  ) )
	{
		pmove->friction = 1.0f;
	}
```
Basically it's only resetting friction every frame in singleplayer. I don't know why it isn't used for mutiplayer.

**Comment by BlackShadow306** [comment] 2019-06-21 13:48
@Sockman1 Thanks for pointing this out. I was able to fix this issue by adding else check.

```
	// In single player, reset friction after each movement to FrictionModifier Triggers work still.
	if (!pmove->multiplayer && (pmove->movetype == MOVETYPE_WALK))
	{
		pmove->friction = 1.0f;
	}
	else 
	{
		pmove->friction = 1.0f;
	}
```

**Comment by SamVanheer** [comment] 2019-06-21 14:09
If i had to guess this is because it won't predict movement correctly when you have a lot of lag. The predicted movement will not account for friction for some frames, but when you get resynced with the server it'll snap you back.

**Comment by kisak-valve** [comment] 2019-08-17 12:28
Hello, as @SamVanheer pointed out, this is a duplicate of #1542, so I've transferred the discussion here to https://github.com/ValveSoftware/halflife/issues/1542#issuecomment-522232486. Please continue the discussion on that issue report.

**Closed by kisak-valve** 2019-08-17 12:28 UTC
