### ISSUE TITLE
Linux software renderer missing geometry

### ISSUE THREAD

**Issue by VirtualBrightPlayz** [ValveSoftware/halflife#3421] opened 2023-11-17 20:14 UTC
On Linux, the software renderer does not render every part of the map in the Training Room.
System info (in case it is needed):
OS: Pop!_OS 22.04 LTS
Windowing System: X11
CPU: AMD Ryzen 7 5700X
GPU: AMD Radeon RX 6600 XT
RAM: 32 GB DDR4
![20231117131418_1](https://github.com/ValveSoftware/halflife/assets/21286339/ce8459d7-b4c1-4236-a8fb-0376886683a8)
![20231117131426_1](https://github.com/ValveSoftware/halflife/assets/21286339/62510086-b8fa-46ef-b8dc-d42deed7c299)

**Comment by ACBob** [comment] 2023-11-17 21:48
![Screenshot_2023-11-17_21-37-34](https://github.com/ValveSoftware/halflife/assets/46695136/e698ad9b-4bd5-48ee-85ac-d85fb8c2b908)
![Screenshot_2023-11-17_21-37-20](https://github.com/ValveSoftware/halflife/assets/46695136/0698449b-fa59-4692-b14d-c5489a566edb)

![Screenshot_2023-11-17_21-39-24](https://github.com/ValveSoftware/halflife/assets/46695136/c0f98ac0-a39c-49a3-936c-80235b749ec2)
![Screenshot_2023-11-17_21-39-11](https://github.com/ValveSoftware/halflife/assets/46695136/be1ba278-4bad-40cc-862e-d811387f2546)

decided to give this a test myself, it seems that it's related to any alpha tested material or surface? (I think the elevator disappears because of the grate in its floor, it's probably one entity or something)
It applies in the campaign as well, translucent or alpha tested materials disappear.

it also seems that _some_ water is incorrect, like the screenshot of the water in the training room, but this water in residue processing is unaffected (maybe because it renders as the drippy effect rather than wavy like the other surface?).

![Screenshot_2023-11-17_21-45-33](https://github.com/ValveSoftware/halflife/assets/46695136/8293ed84-c92c-4848-b606-b5d136516413)
![Screenshot_2023-11-17_21-44-19](https://github.com/ValveSoftware/halflife/assets/46695136/c4a34936-af53-4daf-b027-8f5d91b6a5fa)

**Comment by iodream** [comment] 2023-11-17 21:56
Not sure if this is related but i have a weird texture/effect glitch at this location at this angle. if i take 2 more steps forward it disappears

![Screenshot_20231117_223307](https://github.com/ValveSoftware/halflife/assets/42720874/b748b403-1c1e-4e0d-beac-e822e9f3a8da)

System info (in case it is needed):
OS: Fedora 39 KDE
Windowing System: X11
GPU: intel HD 3000
mesa 23.2.1-2
Software renderer

**Comment by necrophcodr** [comment] 2023-11-17 22:58
I can definitely reproduce these as well on the software renderer.

OS: NixOS 23.11
Windowing System: Wayland (Plasma)
GPU: AMD Radeon 6700 XT

**Comment by terminalarch** [comment] 2023-11-18 16:08
@FridgeRacer Try setting default_fov to 90 in the console, that fixed it for me. Geometry glitch still happens though

**Comment by VirtualBrightPlayz** [comment] 2023-11-21 21:46
After the Nov. 21 update the issue in my original screenshots has been solved.

**Comment by iodream** [comment] 2023-11-21 22:14
I can now see geometry as well and the water is fixed for me too

**Comment by necrophcodr** [comment] 2023-11-21 22:50
Yep, this issue definitely appears to be resolved by now. @VirtualBrightPlayz if this issue is resolved for you as well, are you able to mark it as such?

**Closed** 2023-11-22 00:12 UTC
Labels: Half-Life, Linux, Need Retest
