### ISSUE TITLE
Incorrect display of the map overview on widescreen high resolutions

### ISSUE THREAD

**Issue by Splatt581** [ValveSoftware/halflife#2223] opened 2019-04-22 16:34 UTC
Example in the screenshot below, 1600x900 resolution used

[https://i.imgur.com/oMoph79.jpg](https://i.imgur.com/oMoph79.jpg)

**Comment by djdallmann** [comment] 2019-04-22 21:59
Can confirm, not sure what resolution this starts at or if it's only widescreen. I play 1920x1080 wide and it's there.

**Comment by basuritashka** [comment] 2019-04-24 03:36
That happens because the overview file itself has a pre-defined resolution when it gets created, we need a new method to generate a friendly overview file and making it work on every native resolution.

**Comment by oaus** [comment] 2019-04-25 04:14
Duplicate of https://github.com/ValveSoftware/halflife/issues/226

**Comment by kisak-valve** [comment] 2019-04-25 12:49
Closing as a duplicate of #226.

**Closed by kisak-valve** 2019-04-25 12:49 UTC
