### ISSUE TITLE
[Half-Life] Missing Localization Strings

### ISSUE THREAD

**Issue by LucesEnBabel** [ValveSoftware/halflife#2387] opened 2019-05-04 05:48 UTC
Half-Life has missing localization strings in its spectator mode menu.

![image](https://user-images.githubusercontent.com/25283175/57174477-a26a0c80-6e0d-11e9-98a3-46f4a1ba6b4a.png)

![image](https://user-images.githubusercontent.com/25283175/57174481-adbd3800-6e0d-11e9-9c4b-02339d29d207.png)
(Note how the selected mode is localized correctly, but not the menu list elements)

`Spec_ModeN` strings are referenced in the game's `titles.txt` file but it seems to have no effect.

(Line 742)
```
Spec_Mode1
{
Locked Chase-Camera
}

Spec_Mode2
{
Free Chase-Camera
}

Spec_Mode3
{
Free-Look
}

Spec_Mode4
{
First Person
}

Spec_Mode5
{
Free Map Overview
}

Spec_Mode6
{
Chase Map Overview
}
```

`Valve_xxxx` strings are referenced in the game's `spectatormenu.txt` file, but the localization strings are nowhere to be seen.
(line 23)
```
"5" "#Valve_Close" 	"spec_menu 0"

"4" "#Valve_Help"	"spec_help"

"3" "#Valve_Settings"
{	
	TOGGLE 	"4" "#Valve_Chat_Messages"	"hud_saytext"
	
	TOGGLE	"3" "#Valve_Show_Status"	"spec_drawstatus"
	
	TOGGLE	"2" "#Valve_View_Cone"		"spec_drawcone"
	
	TOGGLE	"1" "#Valve_Player_Names"	"spec_drawnames"
}

TOGGLE	"2" "#Valve_Auto_Director"	"spec_autodirector"
"1" "#Valve_Show_Score"	"togglescores"
```

https://github.com/ValveSoftware/halflife/issues/2316 references a Join Team VGUI menu, however, it also lacks localization strings.

**Comment by SamVanheer** [comment] 2019-05-04 08:13
Duplicate of #2311

**Comment by mikela-valve** [comment] 2019-06-18 21:58
@SamVanheer Actually this proved to go even deeper than the actual keys used by the buttons. The spectate GUI is VGUI1 not VGUI2, and as such the controls don't automatically localise themselves, so the buttons were just not having their text localised at all. 

I've fixed that issue and added the missing settings strings to the titles.txt so this issue should be fixed in the next beta.

**Comment by mikela-valve** [comment] 2019-06-21 00:25
This should be fixed in beta update '15:46:27 Jun 11 2019 (8265)'.

**Comment by LucesEnBabel** [comment] 2019-06-21 03:17
Tested it in Linux, works without problems so far. I will comment on this same issue if there are problems.

Thank you @mikela-valve!.

**Closed** 2019-06-21 14:55 UTC
Labels: Half-Life, localization
