### ISSUE TITLE
Missing gamestartup.mp3 in game files

### ISSUE THREAD

**Issue by maciek10372** [ValveSoftware/halflife#2690] opened 2019-08-23 16:27 UTC
This file should be located in media folder inside cstrike, but unfortunately It is missing.

**Comment by SamVanheer** [comment] 2019-08-23 17:27
It's not missing, the user interface plays that file if it exists. It was added for mods and used for Condition Zero, but older games don't have it so the mp3 playback system warns about it.

Mod versions of CS may have had such a file but if that's the case then it was removed later on.

@kisak-valve you can close this issue as not a bug.

**Comment by kisak-valve** [comment] 2019-08-23 17:52
Closing as a duplicate of #2423.

**Closed by kisak-valve** 2019-08-23 17:52 UTC
Labels: Counter-Strike, Feature Request
