### ISSUE TITLE
HUD Scaling on Counter-Strike

### ISSUE THREAD

**Issue by oxou** [ValveSoftware/halflife#3756] opened 2024-02-11 08:20 UTC
# Counter-Strike
![cs](https://github.com/ValveSoftware/halflife/assets/102489121/8cca44ec-3d25-4588-8678-1266b892f900)

# Half-Life
![hl](https://github.com/ValveSoftware/halflife/assets/102489121/a430da6d-6def-412f-b5fa-3d461309dddf)

I tried manually modifying `cstrike/sprites/hud.txt` to match `valve/sprites/hud.txt` but everything breaks.

**Comment by 0Ky** [comment] 2024-02-11 12:27
This is a duplicate of issue #3548, all other GoldSrc games have incorrect HUD scaling, not just Counter-Strike.

**Comment by oxou** [comment] 2024-02-11 12:53
@0Ky That's a bummer.

**Comment by kisak-valve** [comment] 2024-02-11 13:58
Closing as a duplicate of #3548.

**Closed by kisak-valve** 2024-02-11 13:58 UTC
