### ISSUE TITLE
MOUSE ACC

### ISSUE THREAD

**Issue by kazi6** [ValveSoftware/halflife#2790] opened 2019-11-18 20:17 UTC
and 1 more thing 

the sensitivity is the speed that the mouse travels with ACCEL OFF ( on the surface ).

Now that speed has been change for the same sensitivity.

For example you set the mouse sensitivity to 1.5 and you move the mouse 20 cm on the mousemat witch is 180\* ( recorded the mouse movement with Oscar Editor Mouse software ) after the update same movement was LONGER more like 190\* ~ 200\* WHY.

It was a recorded mouse movement for 800 Hz mouse settings and ingame 1.5 sens. and after the update with the same settings the mouse movement was LONGER witch means that the INPUT was changed.

Alfred do you thing that we users are idiots or retarded?

Put back the Input as before 24.02.2013. ;)

_Originally posted by @AndreiRomania in https://github.com/ValveSoftware/halflife/issues/66#issuecomment-13618057_

**Comment by kisak-valve** [comment] 2019-11-18 20:22
Hello @kazi6, there's no value in fragmenting this discussion. If you have something to add, write a comment on that issue report. Closing as a duplicate of #66.

**Closed by kisak-valve** 2019-11-18 20:22 UTC
