### ISSUE TITLE
/spec BUG

### ISSUE THREAD

**Issue by MatiasGFaria** [ValveSoftware/halflife#2932] opened 2020-07-27 19:46 UTC
hello sorry for the inglesh I am using the google translator, the question is that when an admin uses the / spec command a player is left floating in the air and to solve that the admin has to leave and re-enter the server.

I leave you an image so that you know how the user is bugged when an admin uses the command / spec

image: https://prnt.sc/tphssy

**Comment by Drakunovu** [comment] 2020-07-28 20:29
I think that error is from some plugin of AMXX, because I think that command is isn't in the game originally.

**Comment by metita** [comment] 2020-07-31 02:43
This is just a error from coding side, nothing to do with CS or Half-Life itself, should be closed, just poor coding.

**Comment by afwn90cj93201nixr2e1re** [comment] 2020-08-03 22:13
It's not related to coding at all, but related to serverside engine, possible you are using old engine, this bug present on 5xxx as i know.

**Comment by metita** [comment] 2020-08-03 22:14
/spec is not a native GoldSrc command, there are better ways to send people to Spectator Team without any problems, as I said this is just poor coding and nothing to do with the game itself.

**Comment by afwn90cj93201nixr2e1re** [comment] 2020-08-04 15:13
> there are better ways to send people to Spectator Team without any problems

There are better ways, there are better ways, there are better ways...
You saw the plugin code? No, you don't. How you can know how he transfer player to spectator team? No how? Ok. It's actually not realted to team change at all...

> as I said this 
> as I said this 
> as I said this 

I saw you code, and you low knowledge guy.


https://github.com/ValveSoftware/halflife/issues/2556
it's first bug.
> //Demos
1 - Flying Models
Situation: When you start to record a demo.
Comment: The 'Flying models' are displayed until the model jumps or ducks or walks up or down a slope.


I can replicate it without using external plugins. We can chooseteam with M key (chooseteam) and then going to spectator (6), it's news for you?
Guy writed about `/spec` coz  he doesn't know anything deeply, he should write something like 'joining to spec team while you alive causing players near you floating' instead this one title.

@kisak-valve actually it's old bug and can be fixed just by updating serverside platform (i mean it's **exactly duplicate**), **ask** TS for providing **info about version** (`version` in console) in future, tbh this issue is not informative.
And there's also little band of South America guys which are treating everyone, you don't see that, but we are.

@MatiasGFaria attach .amxx file and post there `version` cmd output (from serverside).

**Comment by afwn90cj93201nixr2e1re** [comment] 2020-08-04 15:27
@kisak-valve can be closed as duplicate of #76.

**Comment by afwn90cj93201nixr2e1re** [comment] 2020-08-04 15:31
> there are better ways to send people to Spectator Team without any problems

There are better ways, there are better ways, there are better ways...
You saw the plugin code? No, you don't. How you can know how he transfer player to spectator team? No how? Ok. It's actually not realted to team change at all...

> as I said this 
> as I said this 
> as I said this 

I saw you code, and you low knowledge guy.

http://amx-x.ru/viewtopic.php?f=19&t=568
It's actually can happend after kicking player with amx_kick, you gonna say that this is poor coding? Lol...

Just read it again and again untill you don't get that this bug have nothing todo with amxmodx...
https://github.com/ValveSoftware/halflife/issues/76#issuecomment-16490251


And this

https://github.com/ValveSoftware/halflife/issues/907

and this

https://github.com/ValveSoftware/halflife/issues/2556
it's first bug.
> //Demos
1 - Flying Models
Situation: When you start to record a demo.
Comment: The 'Flying models' are displayed until the model jumps or ducks or walks up or down a slope.


I can replicate it without using external plugins. We can chooseteam with M key (chooseteam) and then going to spectator (6), it's news for you?
Guy writed about `/spec` coz  he doesn't know anything deeply, he should write something like 'joining to spec team while you alive causing players near you floating' instead this one title.

It's fixed especially in ReHLDS, which used by you, that's why you don't see that. But in poor engine it's still exists.

@kisak-valve actually it's old bug and can be fixed just by updating serverside platform with #907 (i mean it's **exactly duplicate**), **ask** TS for providing **info about version** (`version` in console) in future, tbh this issue is not informative.
And there's also little band of South America guys which are treating everyone, you don't see that, but we are.
Can be closed as **dupe** of #76 and #907

@MatiasGFaria attach .amxx file and post there `version` cmd output (from serverside).

**Comment by metita** [comment] 2020-08-04 21:08
I am talking about the issue itself, not about other bugs that are similar to this one, he is talking about a third-party plugin, that is pretty much bad coding, anyway he does not give any information about what the command do.

This should be closed.

**Comment by kisak-valve** [comment] 2020-08-04 21:38
Closing as a duplicate of #907.

**Closed** 2020-08-04 21:37 UTC
Labels: 3rd party plugin, Counter-Strike
