### ISSUE TITLE
[Request] Adding missing resources to the list of files of CS 1.6

### ISSUE THREAD

**Issue by Splatt581** [ValveSoftware/halflife#2410] opened 2019-05-10 19:23 UTC
The 'Counter-Strike Base Content' depot (https://steamdb.info/depot/11/) contains the file `cstrike/maps/de_cbble_detail.txt` is a settings file for detailed textures. But to use it will not work, since these detailed textures are not in the file list of this depot. They are in CZ, here is a list of textures that need to be added to depot, corresponding to the file:
```
gfx/detail/dt_conc.tga
gfx/detail/dt_grass1.tga
gfx/detail/dt_ground2.tga
gfx/detail/dt_ground3.tga
gfx/detail/dt_metal1.tga
gfx/detail/dt_smooth1.tga
gfx/detail/dt_snow2.tga
gfx/detail/dt_stone1.tga
gfx/detail/dt_stone3.tga
gfx/detail/dt_wood.tga
gfx/detail/dt_wood1.tga
```

Perhaps in the future, the list will be supplemented.

**Comment by kisak-valve** [comment] 2019-05-10 19:50
Duplicate of #1523.

**Closed by kisak-valve** 2019-05-10 19:50 UTC
