### ISSUE TITLE
[HL25] Gauss Gun beam colors are still broken.

### ISSUE THREAD

**Issue by flrys** [ValveSoftware/halflife#3487] opened 2023-11-19 15:56 UTC
In the original WON release the single shots of the gauss gun used to be orange rather than yellow, and the secondary shot got more and more white and less transparent as you charged it. Issue may have been reported before but I still haven't noticed it fixed yet despite HL25 having restored similar WON features. #2865 
Example of this broken feature : https://youtu.be/hG5c-LRVHSk?t=415

**Comment by kisak-valve** [comment] 2023-11-19 16:05
Hello @flrys, there's no value in fragmenting the discussion of this issue across multiple issue reports.

Closing as a duplicate of #2865.

**Closed by kisak-valve** 2023-11-19 16:05 UTC
