### ISSUE TITLE
Scoreboard HP and Money not working on server

### ISSUE THREAD

**Issue by NeoMatrixPublic** [ValveSoftware/halflife#2783] opened 2019-11-10 18:02 UTC
Hi @mikela-valve  i have on my server in **game.cfg** mp_scoreboard_showhealth and mp_scoreboard_showhealth both set to 3 and its not working, my CS 1.6 is updated and also is my server it has latest amxmodx metamod and **ReHLDS**. but no one can see HP and Money in their scoreboard. server was restarted many times to try and enable this also tried adding it to server.cfg but nothing happened. :S how can i set it to work pls help all my players and admins are asking for this function :)

**BUILD 1999 SERVER (0 CRC)** _it was updated 2 weeks ago_

**Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
Exe build: 15:17:55 Jul 24 2019 (8308)**

https://user-images.githubusercontent.com/57591399/68544397-0c69fc80-03c3-11ea-8b5e-c6a4c66d28ae.png

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-11-10 18:04
meta version
amxx version
meta plugins
game version

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-11-10 18:11
Also im not sure about game.cfg exists in official gamedll(also im sure that u r not executing it thru server.cfg or other autoexecuted cfgs), so, can you also execute this cmd `cvarlist log`?

Then attach created file (in cstrike dir) here.

**Comment by NeoMatrixPublic** [comment] 2019-11-10 18:15
Metamod-r v1.3.0.128, API (5:13)
Metamod-r build: 17:47:54 Aug 24 2018
Metamod-r from: https://github.com/theAsmodai/metamod-r/commit/0cf2f70

AMX Mod X 1.9.0.5249 (http://www.amxmodx.org)
Authors:
	David "BAILOPAN" Anderson, Pavol "PM OnoTo" Marko
	Felix "SniperBeamer" Geyer, Jonny "Got His Gun" Bergstrom
	Lukasz "SidLuke" Wlasinski, Christian "Basic-Master" Hammacher
	Borja "faluco" Ferrer, Scott "DS" Ehlert
Compiled: Jun 19 2019 13:31:53
Built from: https://github.com/alliedmodders/amxmodx/commit/6cecb34
Build ID: 5249:6cecb34
Core mode: JIT+ASM3

ReGameDLL version: 5.11.0.417-dev+m
Build date: 23:32:30 Sep 22 2019
Build from: https://github.com/s1lentq/ReGameDLL_CS/commit/0b517e0

linux addons/reunion/reunion_mm_i386.so
linux addons/amxmodx/dlls/amxmodx_mm_i386.so
linux addons/voicetranscoder/VoiceTranscoder.so
linux addons/reauthcheck/reauthcheck_mm_i386.so

[cvarlistlog.txt](https://github.com/ValveSoftware/halflife/files/3828784/cvarlistlog.txt)

**Comment by basuritashka** [comment] 2019-11-10 18:17
ReGameDLL needs to have -beta on launch parameters (ReHLDS) and then it will work, you are not using HLDS latest version to make it work naturally.

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-11-10 18:20
> ReGameDLL version: 5.11.0.417-dev+m

How issue related to this repo?

So, cvars also not exists.
![изображение](https://user-images.githubusercontent.com/9306996/68548601-21b54a00-0408-11ea-84c8-d7e9607ef760.png)


Also you 'r using modified version of regamedll.

**Comment by NeoMatrixPublic** [comment] 2019-11-10 18:24
i have mp_scoreboard_showhealth and mp_scoreboard_showmoney in both game.cfg and server.cfg but they are not working ... 

what should i do? why its not there when i check cvarlist ?

**Comment by basuritashka** [comment] 2019-11-10 18:28
-beta on ReHLDS parameter launch options, this is not a bug, you are using ReGameDLL which is not officially updated to match the latest update on CS 1.6.

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-11-10 18:34
В общем объясню тебе по русски, ты используешь модфицированную версию regamedll, которая собрана хрен знает кем, на это нам указывает постфикс +m, который добавляется к версии на этапе сборки.

Кем она собрана и какие возможности там реализованы - неизвестно никому.

Микела тебе здесь не поможет, это не оффициальная версия геймдлл, он ее не поддерживает.


@kisak-valve  it's unofficial modification, how it's related to official repo? It's another dist. chanels, not related to SteamCMD.

**Comment by NeoMatrixPublic** [comment] 2019-11-10 18:38
ok ok i will check with my hosting provider :) 

thanks for all the answers...

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-11-10 18:39
Name of hosting? Myarena, right?

**Comment by kisak-valve** [comment] 2019-11-10 18:49
Hello @NeoMatrixPublic, as noted by @afwn90cj93201nixr2e1re, ReHLDS is a re-implementation of the dedicated server and outside the scope of this issue tracker. Issues with it should be reported to that project.

That set aside, I didn't summary close this issue because there was a reasonably productive troubleshooting dialog in progress.

Feel free to continue discussing this issue, but I don't see anything here which is actionable for a Valve dev unless you can reproduce the issue with Valve's implementation of the dedicated server.

**Closed by kisak-valve** 2019-11-10 18:49 UTC
Labels: Counter-Strike, Dedicated Server

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-11-10 19:12
![изображение](https://user-images.githubusercontent.com/9306996/68549231-845e1400-040f-11ea-8739-5cae4248fc17.png)
[cs.zip](https://github.com/ValveSoftware/halflife/files/3828861/cs.zip)

Or you can just replace your library with that.
