### ISSUE TITLE
Cstrike -> Movement bug

### ISSUE THREAD

**Issue by deprale** [ValveSoftware/halflife#2929] opened 2020-07-12 08:30 UTC
IF you look up with an usp and shoot really fast with it while holding w or s you're gonna go opposite direction. +forward will become +back and vice-versa.

**Comment by basuritashka** [comment] 2020-07-22 06:53
Already reported by me a few months ago

**Comment by JoelTroch** [comment] 2020-08-03 21:58
This issue is a duplicate of #2248

**Comment by metita** [comment] 2020-08-03 21:59
@kisak-valve This is a duplicate as @JoelTroch stated.

**Closed** 2020-08-03 22:49 UTC
Labels: Counter-Strike
