### ISSUE TITLE
[HL25/CS] Bug in content option and translation (spanish)

### ISSUE THREAD

**Issue by mlibre2** [ValveSoftware/halflife#3615] opened 2023-11-26 01:38 UTC
![image](https://github.com/ValveSoftware/halflife/assets/112137590/67be95a7-7ec3-4308-a25a-47ceb477e42a)

![image](https://github.com/ValveSoftware/halflife/assets/112137590/eff4b9d5-35b1-4efb-80c2-e2ddd35891c6)

lost its alignment in turn disabling being able to select

> [!NOTE]
> - [ ] beta - Beta
> - [ ] steam_legacy
> - [x] HL 25th Build

**Comment by kisak-valve** [comment] 2023-11-26 02:20
Most likely a duplicate of #3465.

**Comment by mlibre2** [comment] 2023-11-26 02:53
@kisak-valve besides, it also seems to have a partial translation problem. even though it is configured in Spanish.

**Comment by Maxi605** [comment] 2023-11-27 22:29
> Most likely a duplicate of #3465.

Yes. It's the same issue, it seems to affect all goldsource games when using the spanish translation.

**Comment by Maxi605** [comment] 2023-11-27 22:29
> @kisak-valve besides, it also seems to have a partial translation problem. even though it is configured in Spanish.

It's more than likely a translation issue, i tested it in english and it displayed correctly.

**Comment by kisak-valve** [comment] 2023-11-27 22:42
Closing in favor of the older issue report.

**Closed by kisak-valve** 2023-11-27 22:42 UTC
Labels: duplicate, Counter-Strike, localization
