### ISSUE TITLE
[Feature Request][HL] [OF] [BS] Add back view roll 

### ISSUE THREAD

**Issue by Yetoo1** [ValveSoftware/halflife#2859] opened 2020-02-13 21:11 UTC
It would be great if the view tilt could be added back into HL, OF, and BS. The WON version of Half-Life and expansions has this prior to 1.1.0.8 (according to this comment: https://github.com/ValveSoftware/halflife/issues/2424#issuecomment-495392961) and I don't understand why it was removed. I feel it made gun play and navigation more fun and inclusion into the steam edition would bring it closer to the original release.

**Comment by DiseCoding-or-DiseGames** [comment] 2020-02-15 17:21
**Grey Source** actually adds this feature back. **Grey Source** is a modified version of GoldSource that I'm working on. You can download **Grey Source 2019** here: https://www.moddb.com/engines/grey-source/downloads/grey-source-2019-build-1911

**Comment by chipsnapper** [comment] 2020-02-25 20:49
This is actually a point of contention in the Half-Life fanbase - viewroll was removed from GoldSrc in WON Update 1.1.1.0. If it were to be implemented, I suggested binding it to a convar so that people can turn it off if they wish.

**Comment by sabian-heatwave** [comment] 2020-02-26 19:19
> This is actually a point of contention in the Half-Life fanbase - viewroll was removed from GoldSrc in WON Update 1.1.1.0. If it were to be implemented, I suggest binding it to a convar so that people can turn it off if they wish.

Grey Source actually does this too. 
In the console, type ‘cl_viewrollangle 0’ to turn it off. To turn it back on, type ‘cl_viewrollangle 0.65’. You can bind a key to these commands.

**Comment by Solokiller** [comment] 2021-02-07 13:08
This issue is a duplicate of #1544.

**Comment by kisak-valve** [comment] 2021-02-07 13:21
Closing as a duplicate.

**Closed by kisak-valve** 2021-02-07 13:21 UTC
Labels: Feature Request, Half-Life, Half-Life:Blue Shift, Half-Life:Opposing Force
