### ISSUE TITLE
[CS 1.6] Fullbright support for v_* models - $texrendermode

### ISSUE THREAD

**Issue by Zetz512** [ValveSoftware/halflife#2747] opened 2019-10-26 21:29 UTC
This can be a thing to be added in the future/next release ?

Preview:

![SKIN1](https://user-images.githubusercontent.com/26032689/67626199-693fb180-f81e-11e9-806a-9e21290acd48.png)
![SKIN2](https://user-images.githubusercontent.com/26032689/67626203-6ba20b80-f81e-11e9-89da-9669ff606c92.png)

Complete tutorial (from SvenCoop)
http://www.the303.org/tutorials/sven_fullbright.htm

ty for answers

**Comment by kisak-valve** [comment] 2019-10-26 22:01
Hello @Zetz512, please do not intentionally open duplicate issue reports.

Closing as a duplicate of #2559.

**Closed by kisak-valve** 2019-10-26 22:01 UTC
