### ISSUE TITLE
[CS/CS:Z] FPS drop problem with Intel GPUs -> allow r_dynamic 0 in multiplayer

### ISSUE THREAD

**Issue by Lewzke** [ValveSoftware/halflife#2796] opened 2019-11-28 10:39 UTC
Well this game should run effortlessly on the modern iGPU-s, because they perform even better than old flagship GPUs, but unfortunately the OpenGL rendering with the the Intel drivers get's fps drops with dynamic lightning events, like flashlight, grenade, custom maps with a lot of action. you can google about this problem and there is no other solution just to turn off the dynamic lightning ingame, but currently you cannot set r_dynamic 0 in multiplayer, just in HL singleplayer. The -nofbo, low video quality check, no vsync and fps_max 100 helps but this fps drop is different story. Lot of people had trouble after the removal of the D3D rendering, and this setting should help for everyone. 

This comment describes in depth about this issue: https://github.com/ValveSoftware/halflife/issues/2565#issuecomment-509409690

The problem is still relevant after 2013. I understand that there is no easy way to fix this problem, because it's engine-OpenGL related, but I don't understad why r_dynamic 0 was removed from goldsrc multiplayer. The flashlight doesn't work with r_dynamic 0 i know, but in CS 1.6 you don't need that anyway, lot of servers and tournaments disable that default. This is the only easy solution for this problem. No need to rewrite anything, just allow this cvar command: **r_dynamic 0** 
 If you guys decided to go with OpenGL Linux multiplatform support, than you should think about these problems too.  D3D was removed and that's okay, but not solving this issue is not okay. 
**Every new and modern Intel GPU and few ATI high end cards suffers this issue.** I also played Half-Life singleplayer and r_dynamic 0 solved the fps drops with grenades and explosions. 

Look at these cases: 
https://github.com/ValveSoftware/halflife/issues/1462
https://github.com/ValveSoftware/halflife/issues/1909
https://github.com/ValveSoftware/halflife/issues/2066
https://github.com/ValveSoftware/halflife/issues/1578
https://github.com/ValveSoftware/halflife/issues/2565
https://github.com/ValveSoftware/halflife/issues/376

CPU: i5 3380M, GPU: Intel HD4000, -nofbo and 1024x768 res look at the fps drop: 

![de_alexandra0011](https://user-images.githubusercontent.com/40172594/69799229-2e40ed00-11d3-11ea-9b2f-085890f0d9a2.jpg)
![de_alexandra0012](https://user-images.githubusercontent.com/40172594/69799241-339e3780-11d3-11ea-94d0-e1f18cce20b5.jpg)
![de_alexandra0014](https://user-images.githubusercontent.com/40172594/69799437-91cb1a80-11d3-11ea-8501-9a023938c26d.jpg)
![de_alexandra0015](https://user-images.githubusercontent.com/40172594/69799439-9263b100-11d3-11ea-8f75-6705638be7d3.jpg)

**Comment by kisak-valve** [comment] 2019-11-28 12:46
Hello @Lewzke, as you've noted, this issue is already being tracked in various issue reports.

Closing as a duplicate of #1578.

**Closed by kisak-valve** 2019-11-28 12:46 UTC

**Comment by Lewzke** [comment] 2019-11-28 12:52
Can you do me a favor? Talk about the r_dynamic 0 with the valve team. Thank you!
Best regards, Lewzke

**Comment by Lewzke** [comment] 2019-11-28 12:58
> Hello @Lewzke, as you've noted, this issue is already being tracked in various issue reports.
> 
> Closing as a duplicate of #1578.

Can you do me a favor? Talk about the r_dynamic 0 with the valve team. Thank you!
Best regards, Lewzke

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-11-29 23:08
OS?

**Comment by Lewzke** [comment] 2019-11-30 11:05
> OS?

Windows 10 64bit, up to date, Intel driver up to date.

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-11-30 16:29
I asked for writing some patch instead waiting.

**Comment by Lewzke** [comment] 2019-11-30 17:00
> I asked for writing some patch instead waiting.

Good to hear that. If I can help you with testing, just ask me.

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-12-01 16:51
hw.dll:
![изображение](https://user-images.githubusercontent.com/9306996/69917139-3b343980-147c-11ea-9975-53716ac1cad0.png)
(72 5F 64 79  6E 61 6D 69 63 00 31 00)
![изображение](https://user-images.githubusercontent.com/9306996/69916733-28b80100-1478-11ea-815d-e8642d059d05.png)
(change 31 -> 30)
You can do it with https://github.com/Garey27/Binary-AutoPatcher or  just open hw.dll in HexEditor and find this patter(on screen) and change it manually.

Or you can patch it right here(different ways on screen):
![изображение](https://user-images.githubusercontent.com/9306996/69917015-4d61a800-147b-11ea-92a6-b09bcc0dd14e.png)
![изображение](https://user-images.githubusercontent.com/9306996/69917090-dc6ec000-147b-11ea-82e9-860b15141117.png)

**Comment by Lewzke** [comment] 2019-12-01 16:58
> hw.dll:
> ![изображение](https://user-images.githubusercontent.com/9306996/69917139-3b343980-147c-11ea-9975-53716ac1cad0.png)
> (72 5F 64 79 6E 61 6D 69 63 00 31 00)
> ![изображение](https://user-images.githubusercontent.com/9306996/69916733-28b80100-1478-11ea-815d-e8642d059d05.png)
> (change 31 -> 30)
> You can do it with https://github.com/Garey27/Binary-AutoPatcher or just open hw.dll in HexEditor and find this patter(on screen) and change it manually.
> 
> Or you can patch it right here(different ways on screen):
> ![изображение](https://user-images.githubusercontent.com/9306996/69917090-dc6ec000-147b-11ea-82e9-860b15141117.png)
Thank you!
Nice find, this can cause ValveAntiCheat ban? Modified dlls are not recomended in VAC servers. anyway this will be released or you are not related to the valve?

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-12-01 17:01
No, it's just patching, vac 2 searching for cheat patterns in memory. So, if you don't wanna be catched for modified dll by servers, you can use some soft for replacing original md5 for server queries. But i don't think that you really need it, coz it's impossible to get all md5 hashes of hw.dl since 2000.

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-12-01 17:03
Im not sure about it's gonna work, test it. Maybe we should patch it in another dll too.

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-12-01 17:31
Seems like a problem here, wait 5 min pls:
![изображение](https://user-images.githubusercontent.com/9306996/69917673-f27f7f00-1481-11ea-881c-83eaa8680559.png)
 im gonna try write new patch.

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-12-01 17:32
![изображение](https://user-images.githubusercontent.com/9306996/69917685-19d64c00-1482-11ea-9ca1-36793838f1f5.png)

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-12-01 17:48
![изображение](https://user-images.githubusercontent.com/9306996/69917697-4b4f1780-1482-11ea-800c-73a68d0904d1.png)

`D9 05 34 6C E4 01 DC 1D 40 D0 E1 01 DF E0 F6 C4 44 7B 12 68 A4 68 E4 01 68 28 6C E4 01`
->
`D9 05 34 6C E4 01 DC 1D 10 D3 E1 01 DF E0 F6 C4 44 7A 12 68 A4 68 E4 01 68 28 6C E4 01`
Was:
![изображение](https://user-images.githubusercontent.com/9306996/69917864-3b383780-1484-11ea-913c-306406bce6af.png)
![изображение](https://user-images.githubusercontent.com/9306996/69917876-59059c80-1484-11ea-85fa-20e1c1d6bba6.png)


Now:
![изображение](https://user-images.githubusercontent.com/9306996/69917706-54d87f80-1482-11ea-9a80-ada43042154d.png)
![изображение](https://user-images.githubusercontent.com/9306996/69917707-5d30ba80-1482-11ea-9c6c-09e7aef6558a.png)

**Comment by Lewzke** [comment] 2019-12-01 18:01
Looks like it works now, it's disabled for me too. But using this patch is not safe everywhere, I play on fastcup.net and they have better anticheat than VAC. Thank you for the work!

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-12-01 18:39
So, gameguard checking game files consinstency, don't patch files.

**Comment by Lewzke** [comment] 2019-12-13 13:23
I think I found something interesting about this problem: 
"
The GoldSrc engine was written long before modern graphics programming techniques such as vertex buffer objects were around. The OpenGL in GoldSrc (and all other OpenGL games of the time) were executing OpenGL instructions in immediate mode, meaning that everything to be drawn on screen must be sent to the GPU and redrawn every frame -- the GPU forgets everything when it comes to rendering the next frame. AMD (and ATI) GPU's have bad performance issues with immediate mode OpenGL, whereas nVidia GPU's handle this much quicker.

You can experience the same issue in Minecraft (before 1.8), as that was entirely using immediate mode OpenGL too. I have exactly the same issue with my AMD R9 280X, where as my (years older) nVidia GTX 560Ti handled Sven Co-op and Minecraft much faster. I did ask AMD about this but they blamed the games (GoldSrc and Minecraft), due to them not making the best use of a modern OpenGL API. I guess nVidia were just nicer when it came to retaining strong compatibility with older software.

Direct3D did have a couple of bugs but I kind of wish it was still present, as it was a much nicer option for those of us with AMD and Intel GPU's. Direct3D has pretty much forced programmers to use vertex buffer objects for many years now, which is why that was much faster for us.

In answer to your question about what you can do unless you want to swap your GPU for an nVidia one you're not going to get an improvement. We would like to re-write all the rendering functions to make use of VBO's but this is a massive job. It certainly won't be done for 5.0, but it will be done...eventually. "

**Comment by Lewzke** [comment] 2019-12-13 13:37
> Hello @Lewzke, as you've noted, this issue is already being tracked in various issue reports.
> 
> Closing as a duplicate of #1578.

Hi kisak, i think I found something about this issue, so you can do something about these open issues, can you ask mikela to review this thing? 
Thank you,
Best Regards, Lewzke 

"The GoldSrc engine was written long before modern graphics programming techniques such as vertex buffer objects were around. The OpenGL in GoldSrc (and all other OpenGL games of the time) were executing OpenGL instructions in immediate mode, meaning that everything to be drawn on screen must be sent to the GPU and redrawn every frame -- the GPU forgets everything when it comes to rendering the next frame. AMD (and ATI) GPU's have bad performance issues with immediate mode OpenGL, whereas nVidia GPU's handle this much quicker.

You can experience the same issue in Minecraft (before 1.8), as that was entirely using immediate mode OpenGL too. I have exactly the same issue with my AMD R9 280X, where as my (years older) nVidia GTX 560Ti handled Sven Co-op and Minecraft much faster. I did ask AMD about this but they blamed the games (GoldSrc and Minecraft), due to them not making the best use of a modern OpenGL API. I guess nVidia were just nicer when it came to retaining strong compatibility with older software.|

**Comment by rinohl** [comment] 2020-06-13 11:38
Hello, I would like to do this (deactivate the dynamic lights) but in half life I suppose it is the same, but I have no idea of programming the truth or I don't know if they could provide me with the file

**Comment by Lewzke** [comment] 2020-06-13 12:03
> Hello, I would like to do this (deactivate the dynamic lights) but in half life I suppose it is the same, but I have no idea of programming the truth or I don't know if they could provide me with the file

Hi, I have the mod, but I not recommend using it, beacuse this can be interpreted by VAC as a cheat, one of my friend used it last year and I think he's account is fine. 
[https://web.tresorit.com/l/UYtkP#1o3ADDQD3oXe32fxqZy_Qg]

**Comment by rinohl** [comment] 2020-06-13 13:11
> > Hello, I would like to do this (deactivate the dynamic lights) but in half life I suppose it is the same, but I have no idea of programming the truth or I don't know if they could provide me with the file
> 
> Hi, I have the mod, but I not recommend using it, beacuse this can be interpreted by VAC as a cheat, one of my friend used it last year and I think he's account is fine. 
> [here you can download](https://web.tresorit.com/l/UYtkP#1o3ADDQD3oXe32fxqZy_Qg)

won't you have one that works in nosteam? or ask too much haha

**Comment by rinohl** [comment] 2020-09-10 19:12
> > Hello, I would like to do this (deactivate the dynamic lights) but in half life I suppose it is the same, but I have no idea of programming the truth or I don't know if they could provide me with the file
> 
> Hi, I have the mod, but I not recommend using it, beacuse this can be interpreted by VAC as a cheat, one of my friend used it last year and I think he's account is fine.
> [here you can download](https://web.tresorit.com/l/UYtkP#1o3ADDQD3oXe32fxqZy_Qg)

hi friend, thanks for the file, could you do the same of r_dynamic in this one? I tried to do it myself but couldn't because of my limited knowledge 
[FIXED SPECIAL HW.zip](https://github.com/ValveSoftware/halflife/files/5204151/FIXED.SPECIAL.HW.zip)

**Comment by afwn90cj93201nixr2e1re** [comment] 2020-09-10 19:51
`D9 05 1C 43 E4 01 DC 1D 10 B3 E1 01 DF E0 F6 C4 44 7A 12 68 E4 3F E4 01`
->
`D9 05 1C 43 E4 01 DC 1D 40 B0 E1 01 DF E0 F6 C4 44 7B 12 68 E4 3F E4 01`

**Comment by rinohl** [comment] 2020-09-10 20:05
> `D9 05 1C 43 E4 01 DC 1D 10 B3 E1 01 DF E0 F6 C4 44 7A 12 68 E4 3F E4 01`
> ->
> `D9 05 1C 43 E4 01 DC 1D 40 B0 E1 01 DF E0 F6 C4 44 7B 12 68 E4 3F E4 01`

do you do it with hex editor?

**Comment by rinohl** [comment] 2020-09-10 20:10
> `D9 05 1C 43 E4 01 DC 1D 10 B3 E1 01 DF E0 F6 C4 44 7A 12 68 E4 3F E4 01`
> ->
> `D9 05 1C 43 E4 01 DC 1D 40 B0 E1 01 DF E0 F6 C4 44 7B 12 68 E4 3F E4 01`

![Captura](https://user-images.githubusercontent.com/66871137/92797522-87f05d80-f388-11ea-963c-32bb78a85b92.PNG)

**Comment by afwn90cj93201nixr2e1re** [comment] 2020-09-10 20:24
![изображение](https://user-images.githubusercontent.com/9306996/92799628-78324280-f3a3-11ea-8b55-78254ee6c6a3.png)
Replace
Hex

**Comment by afwn90cj93201nixr2e1re** [comment] 2020-09-10 20:27
try to swtich values

`D9 05 1C 43 E4 01 DC 1D 10 B3 E1 01 DF E0 F6 C4 44 7A 12 68 E4 3F E4 01`
->
`D9 05 1C 43 E4 01 DC 1D 40 B0 E1 01 DF E0 F6 C4 44 7B 12 68 E4 3F E4 01`


->

`D9 05 1C 43 E4 01 DC 1D 40 B0 E1 01 DF E0 F6 C4 44 7B 12 68 E4 3F E4 01`
->
`D9 05 1C 43 E4 01 DC 1D 10 B3 E1 01 DF E0 F6 C4 44 7A 12 68 E4 3F E4 01`

**Comment by rinohl** [comment] 2020-09-10 20:31
> try to swtich values
> 
> `D9 05 1C 43 E4 01 DC 1D 10 B3 E1 01 DF E0 F6 C4 44 7A 12 68 E4 3F E4 01`
> ->
> `D9 05 1C 43 E4 01 DC 1D 40 B0 E1 01 DF E0 F6 C4 44 7B 12 68 E4 3F E4 01`
> 
> ->
> 
> `D9 05 1C 43 E4 01 DC 1D 40 B0 E1 01 DF E0 F6 C4 44 7B 12 68 E4 3F E4 01`
> ->
> `D9 05 1C 43 E4 01 DC 1D 10 B3 E1 01 DF E0 F6 C4 44 7A 12 68 E4 3F E4 01`

I don't have the same values, change from 1 to 0 (31 to 30) but it is still activated in the game

**Comment by afwn90cj93201nixr2e1re** [comment] 2020-09-10 20:34
:/ 

as i said
switch them

![изображение](https://user-images.githubusercontent.com/9306996/92801264-fba06380-f3a4-11ea-814d-f5d95429d600.png)

**Comment by afwn90cj93201nixr2e1re** [comment] 2020-09-10 20:39
https://i.imgur.com/wWELtsU.png

**Comment by rinohl** [comment] 2020-09-10 20:47
> https://i.imgur.com/wWELtsU.png

![Captura](https://user-images.githubusercontent.com/66871137/92803345-b7559900-f38d-11ea-9b90-cba1111d3ac2.PNG)
![Captura2](https://user-images.githubusercontent.com/66871137/92803350-b886c600-f38d-11ea-9d48-03c9b36815fc.PNG)

**Comment by afwn90cj93201nixr2e1re** [comment] 2020-09-10 20:48
close hex editor, file in using...

**Comment by afwn90cj93201nixr2e1re** [comment] 2020-09-10 20:51
![](https://i.imgur.com/VDZLQwA.png)

**Comment by rinohl** [comment] 2020-09-10 20:58
@afwn90cj93201nixr2e1re 
but I need to use that hw.dll because it fixes some half life stuff

**Comment by rinohl** [comment] 2020-09-10 21:02
@afwn90cj93201nixr2e1re 
![Captura](https://user-images.githubusercontent.com/66871137/92805815-cdfcef80-f38f-11ea-954b-f207053a33f1.PNG)
![Captura2](https://user-images.githubusercontent.com/66871137/92805817-cf2e1c80-f38f-11ea-9a9c-6f5a025d0d11.PNG)

**Comment by afwn90cj93201nixr2e1re** [comment] 2020-09-10 21:20
https://bit.ly/2GSuF1z

**Comment by rinohl** [comment] 2020-09-10 21:31
> https://bit.ly/2GSuF1z

my game is closed

**Comment by tfcccc** [comment] 2025-01-28 17:56
They not only didn't allow us to change this, but they also prevented us from seeing what's done here and modifying the values using a hex editor! They really couldn't care less about anything! My video card is AMD and I can't play 25 year old game!
